// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/dnjtechteam/dnj-game-api/internal/domain/activity/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityRepositoryInterface creates a new instance of MockActivityRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityRepositoryInterface {
	mock := &MockActivityRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityRepositoryInterface is an autogenerated mock type for the ActivityRepositoryInterface type
type MockActivityRepositoryInterface struct {
	mock.Mock
}

type MockActivityRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityRepositoryInterface) EXPECT() *MockActivityRepositoryInterface_Expecter {
	return &MockActivityRepositoryInterface_Expecter{mock: &_m.Mock}
}

// FindAuthorizedForUpdate provides a mock function for the type MockActivityRepositoryInterface
func (_mock *MockActivityRepositoryInterface) FindAuthorizedForUpdate(ctx context.Context, activityID string, actorUserID uint64, global bool) (*entities.Activity, error) {
	ret := _mock.Called(ctx, activityID, actorUserID, global)

	if len(ret) == 0 {
		panic("no return value specified for FindAuthorizedForUpdate")
	}

	var r0 *entities.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool) (*entities.Activity, error)); ok {
		return returnFunc(ctx, activityID, actorUserID, global)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool) *entities.Activity); ok {
		r0 = returnFunc(ctx, activityID, actorUserID, global)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, bool) error); ok {
		r1 = returnFunc(ctx, activityID, actorUserID, global)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAuthorizedForUpdate'
type MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call struct {
	*mock.Call
}

// FindAuthorizedForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID string
//   - actorUserID uint64
//   - global bool
func (_e *MockActivityRepositoryInterface_Expecter) FindAuthorizedForUpdate(ctx interface{}, activityID interface{}, actorUserID interface{}, global interface{}) *MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call {
	return &MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call{Call: _e.mock.On("FindAuthorizedForUpdate", ctx, activityID, actorUserID, global)}
}

func (_c *MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call) Run(run func(ctx context.Context, activityID string, actorUserID uint64, global bool)) *MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call) Return(activity *entities.Activity, err error) *MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call {
	_c.Call.Return(activity, err)
	return _c
}

func (_c *MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call) RunAndReturn(run func(ctx context.Context, activityID string, actorUserID uint64, global bool) (*entities.Activity, error)) *MockActivityRepositoryInterface_FindAuthorizedForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionStatus provides a mock function for the type MockActivityRepositoryInterface
func (_mock *MockActivityRepositoryInterface) TransitionStatus(ctx context.Context, activityID string, from entities.Status, to entities.Status, updatedAt time.Time) error {
	ret := _mock.Called(ctx, activityID, from, to, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for TransitionStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.Status, entities.Status, time.Time) error); ok {
		r0 = returnFunc(ctx, activityID, from, to, updatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActivityRepositoryInterface_TransitionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionStatus'
type MockActivityRepositoryInterface_TransitionStatus_Call struct {
	*mock.Call
}

// TransitionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID string
//   - from entities.Status
//   - to entities.Status
//   - updatedAt time.Time
func (_e *MockActivityRepositoryInterface_Expecter) TransitionStatus(ctx interface{}, activityID interface{}, from interface{}, to interface{}, updatedAt interface{}) *MockActivityRepositoryInterface_TransitionStatus_Call {
	return &MockActivityRepositoryInterface_TransitionStatus_Call{Call: _e.mock.On("TransitionStatus", ctx, activityID, from, to, updatedAt)}
}

func (_c *MockActivityRepositoryInterface_TransitionStatus_Call) Run(run func(ctx context.Context, activityID string, from entities.Status, to entities.Status, updatedAt time.Time)) *MockActivityRepositoryInterface_TransitionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entities.Status
		if args[2] != nil {
			arg2 = args[2].(entities.Status)
		}
		var arg3 entities.Status
		if args[3] != nil {
			arg3 = args[3].(entities.Status)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockActivityRepositoryInterface_TransitionStatus_Call) Return(err error) *MockActivityRepositoryInterface_TransitionStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActivityRepositoryInterface_TransitionStatus_Call) RunAndReturn(run func(ctx context.Context, activityID string, from entities.Status, to entities.Status, updatedAt time.Time) error) *MockActivityRepositoryInterface_TransitionStatus_Call {
	_c.Call.Return(run)
	return _c
}
