// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnjtechteam/dnj-game-api/internal/domain/adminoperation/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminOperationRepositoryInterface creates a new instance of MockAdminOperationRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminOperationRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminOperationRepositoryInterface {
	mock := &MockAdminOperationRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdminOperationRepositoryInterface is an autogenerated mock type for the AdminOperationRepositoryInterface type
type MockAdminOperationRepositoryInterface struct {
	mock.Mock
}

type MockAdminOperationRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminOperationRepositoryInterface) EXPECT() *MockAdminOperationRepositoryInterface_Expecter {
	return &MockAdminOperationRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAdminOperationRepositoryInterface
func (_mock *MockAdminOperationRepositoryInterface) Create(ctx context.Context, operation *entities.AdminOperation) (*entities.AdminOperation, error) {
	ret := _mock.Called(ctx, operation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.AdminOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.AdminOperation) (*entities.AdminOperation, error)); ok {
		return returnFunc(ctx, operation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.AdminOperation) *entities.AdminOperation); ok {
		r0 = returnFunc(ctx, operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AdminOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.AdminOperation) error); ok {
		r1 = returnFunc(ctx, operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminOperationRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAdminOperationRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - operation *entities.AdminOperation
func (_e *MockAdminOperationRepositoryInterface_Expecter) Create(ctx interface{}, operation interface{}) *MockAdminOperationRepositoryInterface_Create_Call {
	return &MockAdminOperationRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, operation)}
}

func (_c *MockAdminOperationRepositoryInterface_Create_Call) Run(run func(ctx context.Context, operation *entities.AdminOperation)) *MockAdminOperationRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.AdminOperation
		if args[1] != nil {
			arg1 = args[1].(*entities.AdminOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminOperationRepositoryInterface_Create_Call) Return(adminOperation *entities.AdminOperation, err error) *MockAdminOperationRepositoryInterface_Create_Call {
	_c.Call.Return(adminOperation, err)
	return _c
}

func (_c *MockAdminOperationRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, operation *entities.AdminOperation) (*entities.AdminOperation, error)) *MockAdminOperationRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByActorAndIdempotencyKey provides a mock function for the type MockAdminOperationRepositoryInterface
func (_mock *MockAdminOperationRepositoryInterface) FindByActorAndIdempotencyKey(ctx context.Context, actorUserID uint64, key string) (*entities.AdminOperation, error) {
	ret := _mock.Called(ctx, actorUserID, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByActorAndIdempotencyKey")
	}

	var r0 *entities.AdminOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (*entities.AdminOperation, error)); ok {
		return returnFunc(ctx, actorUserID, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) *entities.AdminOperation); ok {
		r0 = returnFunc(ctx, actorUserID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AdminOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(ctx, actorUserID, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByActorAndIdempotencyKey'
type MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call struct {
	*mock.Call
}

// FindByActorAndIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID uint64
//   - key string
func (_e *MockAdminOperationRepositoryInterface_Expecter) FindByActorAndIdempotencyKey(ctx interface{}, actorUserID interface{}, key interface{}) *MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call {
	return &MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call{Call: _e.mock.On("FindByActorAndIdempotencyKey", ctx, actorUserID, key)}
}

func (_c *MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call) Run(run func(ctx context.Context, actorUserID uint64, key string)) *MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call) Return(adminOperation *entities.AdminOperation, err error) *MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call {
	_c.Call.Return(adminOperation, err)
	return _c
}

func (_c *MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, actorUserID uint64, key string) (*entities.AdminOperation, error)) *MockAdminOperationRepositoryInterface_FindByActorAndIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}
