// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnjtechteam/dnj-game-api/internal/domain/emailsignupcode/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailSignupCodeRepositoryInterface creates a new instance of MockEmailSignupCodeRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailSignupCodeRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailSignupCodeRepositoryInterface {
	mock := &MockEmailSignupCodeRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailSignupCodeRepositoryInterface is an autogenerated mock type for the EmailSignupCodeRepositoryInterface type
type MockEmailSignupCodeRepositoryInterface struct {
	mock.Mock
}

type MockEmailSignupCodeRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailSignupCodeRepositoryInterface) EXPECT() *MockEmailSignupCodeRepositoryInterface_Expecter {
	return &MockEmailSignupCodeRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEmailSignupCodeRepositoryInterface
func (_mock *MockEmailSignupCodeRepositoryInterface) Create(ctx context.Context, code *entities.EmailSignupCode) (*entities.EmailSignupCode, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.EmailSignupCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.EmailSignupCode) (*entities.EmailSignupCode, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.EmailSignupCode) *entities.EmailSignupCode); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.EmailSignupCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.EmailSignupCode) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailSignupCodeRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEmailSignupCodeRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - code *entities.EmailSignupCode
func (_e *MockEmailSignupCodeRepositoryInterface_Expecter) Create(ctx interface{}, code interface{}) *MockEmailSignupCodeRepositoryInterface_Create_Call {
	return &MockEmailSignupCodeRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, code)}
}

func (_c *MockEmailSignupCodeRepositoryInterface_Create_Call) Run(run func(ctx context.Context, code *entities.EmailSignupCode)) *MockEmailSignupCodeRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.EmailSignupCode
		if args[1] != nil {
			arg1 = args[1].(*entities.EmailSignupCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailSignupCodeRepositoryInterface_Create_Call) Return(emailSignupCode *entities.EmailSignupCode, err error) *MockEmailSignupCodeRepositoryInterface_Create_Call {
	_c.Call.Return(emailSignupCode, err)
	return _c
}

func (_c *MockEmailSignupCodeRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, code *entities.EmailSignupCode) (*entities.EmailSignupCode, error)) *MockEmailSignupCodeRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmailForUpdate provides a mock function for the type MockEmailSignupCodeRepositoryInterface
func (_mock *MockEmailSignupCodeRepositoryInterface) FindByEmailForUpdate(ctx context.Context, email string) (*entities.EmailSignupCode, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmailForUpdate")
	}

	var r0 *entities.EmailSignupCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.EmailSignupCode, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.EmailSignupCode); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.EmailSignupCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmailForUpdate'
type MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call struct {
	*mock.Call
}

// FindByEmailForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockEmailSignupCodeRepositoryInterface_Expecter) FindByEmailForUpdate(ctx interface{}, email interface{}) *MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call {
	return &MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call{Call: _e.mock.On("FindByEmailForUpdate", ctx, email)}
}

func (_c *MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call) Run(run func(ctx context.Context, email string)) *MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call) Return(emailSignupCode *entities.EmailSignupCode, err error) *MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call {
	_c.Call.Return(emailSignupCode, err)
	return _c
}

func (_c *MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call) RunAndReturn(run func(ctx context.Context, email string) (*entities.EmailSignupCode, error)) *MockEmailSignupCodeRepositoryInterface_FindByEmailForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockEmailSignupCodeRepositoryInterface
func (_mock *MockEmailSignupCodeRepositoryInterface) Update(ctx context.Context, code *entities.EmailSignupCode) (*entities.EmailSignupCode, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.EmailSignupCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.EmailSignupCode) (*entities.EmailSignupCode, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.EmailSignupCode) *entities.EmailSignupCode); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.EmailSignupCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.EmailSignupCode) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailSignupCodeRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEmailSignupCodeRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - code *entities.EmailSignupCode
func (_e *MockEmailSignupCodeRepositoryInterface_Expecter) Update(ctx interface{}, code interface{}) *MockEmailSignupCodeRepositoryInterface_Update_Call {
	return &MockEmailSignupCodeRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, code)}
}

func (_c *MockEmailSignupCodeRepositoryInterface_Update_Call) Run(run func(ctx context.Context, code *entities.EmailSignupCode)) *MockEmailSignupCodeRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.EmailSignupCode
		if args[1] != nil {
			arg1 = args[1].(*entities.EmailSignupCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailSignupCodeRepositoryInterface_Update_Call) Return(emailSignupCode *entities.EmailSignupCode, err error) *MockEmailSignupCodeRepositoryInterface_Update_Call {
	_c.Call.Return(emailSignupCode, err)
	return _c
}

func (_c *MockEmailSignupCodeRepositoryInterface_Update_Call) RunAndReturn(run func(ctx context.Context, code *entities.EmailSignupCode) (*entities.EmailSignupCode, error)) *MockEmailSignupCodeRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}
