// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/dnjtechteam/dnj-game-api/internal/app/messages"
	entities0 "github.com/dnjtechteam/dnj-game-api/internal/domain/activity/entities"
	"github.com/dnjtechteam/dnj-game-api/internal/domain/favorite/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFavoriteRepositoryInterface creates a new instance of MockFavoriteRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteRepositoryInterface {
	mock := &MockFavoriteRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFavoriteRepositoryInterface is an autogenerated mock type for the FavoriteRepositoryInterface type
type MockFavoriteRepositoryInterface struct {
	mock.Mock
}

type MockFavoriteRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteRepositoryInterface) EXPECT() *MockFavoriteRepositoryInterface_Expecter {
	return &MockFavoriteRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFavoriteRepositoryInterface
func (_mock *MockFavoriteRepositoryInterface) Create(ctx context.Context, favorite *entities.Favorite) (bool, error) {
	ret := _mock.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Favorite) (bool, error)); ok {
		return returnFunc(ctx, favorite)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Favorite) bool); ok {
		r0 = returnFunc(ctx, favorite)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Favorite) error); ok {
		r1 = returnFunc(ctx, favorite)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavoriteRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFavoriteRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - favorite *entities.Favorite
func (_e *MockFavoriteRepositoryInterface_Expecter) Create(ctx interface{}, favorite interface{}) *MockFavoriteRepositoryInterface_Create_Call {
	return &MockFavoriteRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, favorite)}
}

func (_c *MockFavoriteRepositoryInterface_Create_Call) Run(run func(ctx context.Context, favorite *entities.Favorite)) *MockFavoriteRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Favorite
		if args[1] != nil {
			arg1 = args[1].(*entities.Favorite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavoriteRepositoryInterface_Create_Call) Return(b bool, err error) *MockFavoriteRepositoryInterface_Create_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFavoriteRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, favorite *entities.Favorite) (bool, error)) *MockFavoriteRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOperation provides a mock function for the type MockFavoriteRepositoryInterface
func (_mock *MockFavoriteRepositoryInterface) CreateOperation(ctx context.Context, operation *entities.ParticipantOperation) (*entities.ParticipantOperation, error) {
	ret := _mock.Called(ctx, operation)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperation")
	}

	var r0 *entities.ParticipantOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.ParticipantOperation) (*entities.ParticipantOperation, error)); ok {
		return returnFunc(ctx, operation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.ParticipantOperation) *entities.ParticipantOperation); ok {
		r0 = returnFunc(ctx, operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ParticipantOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.ParticipantOperation) error); ok {
		r1 = returnFunc(ctx, operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavoriteRepositoryInterface_CreateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOperation'
type MockFavoriteRepositoryInterface_CreateOperation_Call struct {
	*mock.Call
}

// CreateOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - operation *entities.ParticipantOperation
func (_e *MockFavoriteRepositoryInterface_Expecter) CreateOperation(ctx interface{}, operation interface{}) *MockFavoriteRepositoryInterface_CreateOperation_Call {
	return &MockFavoriteRepositoryInterface_CreateOperation_Call{Call: _e.mock.On("CreateOperation", ctx, operation)}
}

func (_c *MockFavoriteRepositoryInterface_CreateOperation_Call) Run(run func(ctx context.Context, operation *entities.ParticipantOperation)) *MockFavoriteRepositoryInterface_CreateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.ParticipantOperation
		if args[1] != nil {
			arg1 = args[1].(*entities.ParticipantOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavoriteRepositoryInterface_CreateOperation_Call) Return(participantOperation *entities.ParticipantOperation, err error) *MockFavoriteRepositoryInterface_CreateOperation_Call {
	_c.Call.Return(participantOperation, err)
	return _c
}

func (_c *MockFavoriteRepositoryInterface_CreateOperation_Call) RunAndReturn(run func(ctx context.Context, operation *entities.ParticipantOperation) (*entities.ParticipantOperation, error)) *MockFavoriteRepositoryInterface_CreateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFavoriteRepositoryInterface
func (_mock *MockFavoriteRepositoryInterface) Delete(ctx context.Context, userID uint64, activityID string) (bool, error) {
	ret := _mock.Called(ctx, userID, activityID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (bool, error)); ok {
		return returnFunc(ctx, userID, activityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) bool); ok {
		r0 = returnFunc(ctx, userID, activityID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(ctx, userID, activityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavoriteRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFavoriteRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - activityID string
func (_e *MockFavoriteRepositoryInterface_Expecter) Delete(ctx interface{}, userID interface{}, activityID interface{}) *MockFavoriteRepositoryInterface_Delete_Call {
	return &MockFavoriteRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, activityID)}
}

func (_c *MockFavoriteRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, userID uint64, activityID string)) *MockFavoriteRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavoriteRepositoryInterface_Delete_Call) Return(b bool, err error) *MockFavoriteRepositoryInterface_Delete_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFavoriteRepositoryInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uint64, activityID string) (bool, error)) *MockFavoriteRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindOperation provides a mock function for the type MockFavoriteRepositoryInterface
func (_mock *MockFavoriteRepositoryInterface) FindOperation(ctx context.Context, actorUserID uint64, idempotencyKey string) (*entities.ParticipantOperation, error) {
	ret := _mock.Called(ctx, actorUserID, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for FindOperation")
	}

	var r0 *entities.ParticipantOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (*entities.ParticipantOperation, error)); ok {
		return returnFunc(ctx, actorUserID, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) *entities.ParticipantOperation); ok {
		r0 = returnFunc(ctx, actorUserID, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ParticipantOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(ctx, actorUserID, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavoriteRepositoryInterface_FindOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOperation'
type MockFavoriteRepositoryInterface_FindOperation_Call struct {
	*mock.Call
}

// FindOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID uint64
//   - idempotencyKey string
func (_e *MockFavoriteRepositoryInterface_Expecter) FindOperation(ctx interface{}, actorUserID interface{}, idempotencyKey interface{}) *MockFavoriteRepositoryInterface_FindOperation_Call {
	return &MockFavoriteRepositoryInterface_FindOperation_Call{Call: _e.mock.On("FindOperation", ctx, actorUserID, idempotencyKey)}
}

func (_c *MockFavoriteRepositoryInterface_FindOperation_Call) Run(run func(ctx context.Context, actorUserID uint64, idempotencyKey string)) *MockFavoriteRepositoryInterface_FindOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavoriteRepositoryInterface_FindOperation_Call) Return(participantOperation *entities.ParticipantOperation, err error) *MockFavoriteRepositoryInterface_FindOperation_Call {
	_c.Call.Return(participantOperation, err)
	return _c
}

func (_c *MockFavoriteRepositoryInterface_FindOperation_Call) RunAndReturn(run func(ctx context.Context, actorUserID uint64, idempotencyKey string) (*entities.ParticipantOperation, error)) *MockFavoriteRepositoryInterface_FindOperation_Call {
	_c.Call.Return(run)
	return _c
}

// ListVisible provides a mock function for the type MockFavoriteRepositoryInterface
func (_mock *MockFavoriteRepositoryInterface) ListVisible(ctx context.Context, userID uint64, generatedAt time.Time, page uint64) (*messages.PaginatedResponse[entities0.PublicActivity], error) {
	ret := _mock.Called(ctx, userID, generatedAt, page)

	if len(ret) == 0 {
		panic("no return value specified for ListVisible")
	}

	var r0 *messages.PaginatedResponse[entities0.PublicActivity]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, time.Time, uint64) (*messages.PaginatedResponse[entities0.PublicActivity], error)); ok {
		return returnFunc(ctx, userID, generatedAt, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, time.Time, uint64) *messages.PaginatedResponse[entities0.PublicActivity]); ok {
		r0 = returnFunc(ctx, userID, generatedAt, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.PaginatedResponse[entities0.PublicActivity])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, time.Time, uint64) error); ok {
		r1 = returnFunc(ctx, userID, generatedAt, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavoriteRepositoryInterface_ListVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVisible'
type MockFavoriteRepositoryInterface_ListVisible_Call struct {
	*mock.Call
}

// ListVisible is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - generatedAt time.Time
//   - page uint64
func (_e *MockFavoriteRepositoryInterface_Expecter) ListVisible(ctx interface{}, userID interface{}, generatedAt interface{}, page interface{}) *MockFavoriteRepositoryInterface_ListVisible_Call {
	return &MockFavoriteRepositoryInterface_ListVisible_Call{Call: _e.mock.On("ListVisible", ctx, userID, generatedAt, page)}
}

func (_c *MockFavoriteRepositoryInterface_ListVisible_Call) Run(run func(ctx context.Context, userID uint64, generatedAt time.Time, page uint64)) *MockFavoriteRepositoryInterface_ListVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFavoriteRepositoryInterface_ListVisible_Call) Return(paginatedResponse *messages.PaginatedResponse[entities0.PublicActivity], err error) *MockFavoriteRepositoryInterface_ListVisible_Call {
	_c.Call.Return(paginatedResponse, err)
	return _c
}

func (_c *MockFavoriteRepositoryInterface_ListVisible_Call) RunAndReturn(run func(ctx context.Context, userID uint64, generatedAt time.Time, page uint64) (*messages.PaginatedResponse[entities0.PublicActivity], error)) *MockFavoriteRepositoryInterface_ListVisible_Call {
	_c.Call.Return(run)
	return _c
}
