// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/dnjtechteam/dnj-game-api/internal/app/messages"
	entities1 "github.com/dnjtechteam/dnj-game-api/internal/domain/activity/entities"
	entities0 "github.com/dnjtechteam/dnj-game-api/internal/domain/favorite/entities"
	"github.com/dnjtechteam/dnj-game-api/internal/domain/game/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGameRepositoryInterface creates a new instance of MockGameRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameRepositoryInterface {
	mock := &MockGameRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGameRepositoryInterface is an autogenerated mock type for the GameRepositoryInterface type
type MockGameRepositoryInterface struct {
	mock.Mock
}

type MockGameRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameRepositoryInterface) EXPECT() *MockGameRepositoryInterface_Expecter {
	return &MockGameRepositoryInterface_Expecter{mock: &_m.Mock}
}

// ApplyAward provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) ApplyAward(ctx context.Context, participantID string, result entities.Result, points int, entry *entities.PointEntry) error {
	ret := _mock.Called(ctx, participantID, result, points, entry)

	if len(ret) == 0 {
		panic("no return value specified for ApplyAward")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.Result, int, *entities.PointEntry) error); ok {
		r0 = returnFunc(ctx, participantID, result, points, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGameRepositoryInterface_ApplyAward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyAward'
type MockGameRepositoryInterface_ApplyAward_Call struct {
	*mock.Call
}

// ApplyAward is a helper method to define mock.On call
//   - ctx context.Context
//   - participantID string
//   - result entities.Result
//   - points int
//   - entry *entities.PointEntry
func (_e *MockGameRepositoryInterface_Expecter) ApplyAward(ctx interface{}, participantID interface{}, result interface{}, points interface{}, entry interface{}) *MockGameRepositoryInterface_ApplyAward_Call {
	return &MockGameRepositoryInterface_ApplyAward_Call{Call: _e.mock.On("ApplyAward", ctx, participantID, result, points, entry)}
}

func (_c *MockGameRepositoryInterface_ApplyAward_Call) Run(run func(ctx context.Context, participantID string, result entities.Result, points int, entry *entities.PointEntry)) *MockGameRepositoryInterface_ApplyAward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entities.Result
		if args[2] != nil {
			arg2 = args[2].(entities.Result)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 *entities.PointEntry
		if args[4] != nil {
			arg4 = args[4].(*entities.PointEntry)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_ApplyAward_Call) Return(err error) *MockGameRepositoryInterface_ApplyAward_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGameRepositoryInterface_ApplyAward_Call) RunAndReturn(run func(ctx context.Context, participantID string, result entities.Result, points int, entry *entities.PointEntry) error) *MockGameRepositoryInterface_ApplyAward_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteParticipationStates provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) CompleteParticipationStates(ctx context.Context, runID string, status entities.ParticipationStatus) error {
	ret := _mock.Called(ctx, runID, status)

	if len(ret) == 0 {
		panic("no return value specified for CompleteParticipationStates")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.ParticipationStatus) error); ok {
		r0 = returnFunc(ctx, runID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGameRepositoryInterface_CompleteParticipationStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteParticipationStates'
type MockGameRepositoryInterface_CompleteParticipationStates_Call struct {
	*mock.Call
}

// CompleteParticipationStates is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - status entities.ParticipationStatus
func (_e *MockGameRepositoryInterface_Expecter) CompleteParticipationStates(ctx interface{}, runID interface{}, status interface{}) *MockGameRepositoryInterface_CompleteParticipationStates_Call {
	return &MockGameRepositoryInterface_CompleteParticipationStates_Call{Call: _e.mock.On("CompleteParticipationStates", ctx, runID, status)}
}

func (_c *MockGameRepositoryInterface_CompleteParticipationStates_Call) Run(run func(ctx context.Context, runID string, status entities.ParticipationStatus)) *MockGameRepositoryInterface_CompleteParticipationStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entities.ParticipationStatus
		if args[2] != nil {
			arg2 = args[2].(entities.ParticipationStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_CompleteParticipationStates_Call) Return(err error) *MockGameRepositoryInterface_CompleteParticipationStates_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGameRepositoryInterface_CompleteParticipationStates_Call) RunAndReturn(run func(ctx context.Context, runID string, status entities.ParticipationStatus) error) *MockGameRepositoryInterface_CompleteParticipationStates_Call {
	_c.Call.Return(run)
	return _c
}

// CreateManagerOperation provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) CreateManagerOperation(ctx context.Context, operation *entities.ManagerOperation) error {
	ret := _mock.Called(ctx, operation)

	if len(ret) == 0 {
		panic("no return value specified for CreateManagerOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.ManagerOperation) error); ok {
		r0 = returnFunc(ctx, operation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGameRepositoryInterface_CreateManagerOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateManagerOperation'
type MockGameRepositoryInterface_CreateManagerOperation_Call struct {
	*mock.Call
}

// CreateManagerOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - operation *entities.ManagerOperation
func (_e *MockGameRepositoryInterface_Expecter) CreateManagerOperation(ctx interface{}, operation interface{}) *MockGameRepositoryInterface_CreateManagerOperation_Call {
	return &MockGameRepositoryInterface_CreateManagerOperation_Call{Call: _e.mock.On("CreateManagerOperation", ctx, operation)}
}

func (_c *MockGameRepositoryInterface_CreateManagerOperation_Call) Run(run func(ctx context.Context, operation *entities.ManagerOperation)) *MockGameRepositoryInterface_CreateManagerOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.ManagerOperation
		if args[1] != nil {
			arg1 = args[1].(*entities.ManagerOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_CreateManagerOperation_Call) Return(err error) *MockGameRepositoryInterface_CreateManagerOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGameRepositoryInterface_CreateManagerOperation_Call) RunAndReturn(run func(ctx context.Context, operation *entities.ManagerOperation) error) *MockGameRepositoryInterface_CreateManagerOperation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateParticipantOperation provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) CreateParticipantOperation(ctx context.Context, operation *entities0.ParticipantOperation) error {
	ret := _mock.Called(ctx, operation)

	if len(ret) == 0 {
		panic("no return value specified for CreateParticipantOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities0.ParticipantOperation) error); ok {
		r0 = returnFunc(ctx, operation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGameRepositoryInterface_CreateParticipantOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateParticipantOperation'
type MockGameRepositoryInterface_CreateParticipantOperation_Call struct {
	*mock.Call
}

// CreateParticipantOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - operation *entities0.ParticipantOperation
func (_e *MockGameRepositoryInterface_Expecter) CreateParticipantOperation(ctx interface{}, operation interface{}) *MockGameRepositoryInterface_CreateParticipantOperation_Call {
	return &MockGameRepositoryInterface_CreateParticipantOperation_Call{Call: _e.mock.On("CreateParticipantOperation", ctx, operation)}
}

func (_c *MockGameRepositoryInterface_CreateParticipantOperation_Call) Run(run func(ctx context.Context, operation *entities0.ParticipantOperation)) *MockGameRepositoryInterface_CreateParticipantOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities0.ParticipantOperation
		if args[1] != nil {
			arg1 = args[1].(*entities0.ParticipantOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_CreateParticipantOperation_Call) Return(err error) *MockGameRepositoryInterface_CreateParticipantOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGameRepositoryInterface_CreateParticipantOperation_Call) RunAndReturn(run func(ctx context.Context, operation *entities0.ParticipantOperation) error) *MockGameRepositoryInterface_CreateParticipantOperation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateParticipation provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) CreateParticipation(ctx context.Context, participation *entities.Participation, participant *entities.RunParticipant) error {
	ret := _mock.Called(ctx, participation, participant)

	if len(ret) == 0 {
		panic("no return value specified for CreateParticipation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Participation, *entities.RunParticipant) error); ok {
		r0 = returnFunc(ctx, participation, participant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGameRepositoryInterface_CreateParticipation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateParticipation'
type MockGameRepositoryInterface_CreateParticipation_Call struct {
	*mock.Call
}

// CreateParticipation is a helper method to define mock.On call
//   - ctx context.Context
//   - participation *entities.Participation
//   - participant *entities.RunParticipant
func (_e *MockGameRepositoryInterface_Expecter) CreateParticipation(ctx interface{}, participation interface{}, participant interface{}) *MockGameRepositoryInterface_CreateParticipation_Call {
	return &MockGameRepositoryInterface_CreateParticipation_Call{Call: _e.mock.On("CreateParticipation", ctx, participation, participant)}
}

func (_c *MockGameRepositoryInterface_CreateParticipation_Call) Run(run func(ctx context.Context, participation *entities.Participation, participant *entities.RunParticipant)) *MockGameRepositoryInterface_CreateParticipation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Participation
		if args[1] != nil {
			arg1 = args[1].(*entities.Participation)
		}
		var arg2 *entities.RunParticipant
		if args[2] != nil {
			arg2 = args[2].(*entities.RunParticipant)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_CreateParticipation_Call) Return(err error) *MockGameRepositoryInterface_CreateParticipation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGameRepositoryInterface_CreateParticipation_Call) RunAndReturn(run func(ctx context.Context, participation *entities.Participation, participant *entities.RunParticipant) error) *MockGameRepositoryInterface_CreateParticipation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQR provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) CreateQR(ctx context.Context, qr *entities.QRCode) (*entities.QRCode, error) {
	ret := _mock.Called(ctx, qr)

	if len(ret) == 0 {
		panic("no return value specified for CreateQR")
	}

	var r0 *entities.QRCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.QRCode) (*entities.QRCode, error)); ok {
		return returnFunc(ctx, qr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.QRCode) *entities.QRCode); ok {
		r0 = returnFunc(ctx, qr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.QRCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.QRCode) error); ok {
		r1 = returnFunc(ctx, qr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_CreateQR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQR'
type MockGameRepositoryInterface_CreateQR_Call struct {
	*mock.Call
}

// CreateQR is a helper method to define mock.On call
//   - ctx context.Context
//   - qr *entities.QRCode
func (_e *MockGameRepositoryInterface_Expecter) CreateQR(ctx interface{}, qr interface{}) *MockGameRepositoryInterface_CreateQR_Call {
	return &MockGameRepositoryInterface_CreateQR_Call{Call: _e.mock.On("CreateQR", ctx, qr)}
}

func (_c *MockGameRepositoryInterface_CreateQR_Call) Run(run func(ctx context.Context, qr *entities.QRCode)) *MockGameRepositoryInterface_CreateQR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.QRCode
		if args[1] != nil {
			arg1 = args[1].(*entities.QRCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_CreateQR_Call) Return(qRCode *entities.QRCode, err error) *MockGameRepositoryInterface_CreateQR_Call {
	_c.Call.Return(qRCode, err)
	return _c
}

func (_c *MockGameRepositoryInterface_CreateQR_Call) RunAndReturn(run func(ctx context.Context, qr *entities.QRCode) (*entities.QRCode, error)) *MockGameRepositoryInterface_CreateQR_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRun provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) CreateRun(ctx context.Context, run *entities.ActivityRun) (*entities.ActivityRun, error) {
	ret := _mock.Called(ctx, run)

	if len(ret) == 0 {
		panic("no return value specified for CreateRun")
	}

	var r0 *entities.ActivityRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.ActivityRun) (*entities.ActivityRun, error)); ok {
		return returnFunc(ctx, run)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.ActivityRun) *entities.ActivityRun); ok {
		r0 = returnFunc(ctx, run)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ActivityRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.ActivityRun) error); ok {
		r1 = returnFunc(ctx, run)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_CreateRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRun'
type MockGameRepositoryInterface_CreateRun_Call struct {
	*mock.Call
}

// CreateRun is a helper method to define mock.On call
//   - ctx context.Context
//   - run *entities.ActivityRun
func (_e *MockGameRepositoryInterface_Expecter) CreateRun(ctx interface{}, run interface{}) *MockGameRepositoryInterface_CreateRun_Call {
	return &MockGameRepositoryInterface_CreateRun_Call{Call: _e.mock.On("CreateRun", ctx, run)}
}

func (_c *MockGameRepositoryInterface_CreateRun_Call) Run(run func(ctx context.Context, run *entities.ActivityRun)) *MockGameRepositoryInterface_CreateRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.ActivityRun
		if args[1] != nil {
			arg1 = args[1].(*entities.ActivityRun)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_CreateRun_Call) Return(activityRun *entities.ActivityRun, err error) *MockGameRepositoryInterface_CreateRun_Call {
	_c.Call.Return(activityRun, err)
	return _c
}

func (_c *MockGameRepositoryInterface_CreateRun_Call) RunAndReturn(run func(ctx context.Context, run *entities.ActivityRun) (*entities.ActivityRun, error)) *MockGameRepositoryInterface_CreateRun_Call {
	_c.Call.Return(run)
	return _c
}

// DisableActiveQR provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) DisableActiveQR(ctx context.Context, runID string, updatedAt time.Time) error {
	ret := _mock.Called(ctx, runID, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for DisableActiveQR")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, runID, updatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGameRepositoryInterface_DisableActiveQR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableActiveQR'
type MockGameRepositoryInterface_DisableActiveQR_Call struct {
	*mock.Call
}

// DisableActiveQR is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - updatedAt time.Time
func (_e *MockGameRepositoryInterface_Expecter) DisableActiveQR(ctx interface{}, runID interface{}, updatedAt interface{}) *MockGameRepositoryInterface_DisableActiveQR_Call {
	return &MockGameRepositoryInterface_DisableActiveQR_Call{Call: _e.mock.On("DisableActiveQR", ctx, runID, updatedAt)}
}

func (_c *MockGameRepositoryInterface_DisableActiveQR_Call) Run(run func(ctx context.Context, runID string, updatedAt time.Time)) *MockGameRepositoryInterface_DisableActiveQR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_DisableActiveQR_Call) Return(err error) *MockGameRepositoryInterface_DisableActiveQR_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGameRepositoryInterface_DisableActiveQR_Call) RunAndReturn(run func(ctx context.Context, runID string, updatedAt time.Time) error) *MockGameRepositoryInterface_DisableActiveQR_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveQRByRun provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindActiveQRByRun(ctx context.Context, runID string) (*entities.QRCode, error) {
	ret := _mock.Called(ctx, runID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveQRByRun")
	}

	var r0 *entities.QRCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.QRCode, error)); ok {
		return returnFunc(ctx, runID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.QRCode); ok {
		r0 = returnFunc(ctx, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.QRCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, runID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindActiveQRByRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveQRByRun'
type MockGameRepositoryInterface_FindActiveQRByRun_Call struct {
	*mock.Call
}

// FindActiveQRByRun is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
func (_e *MockGameRepositoryInterface_Expecter) FindActiveQRByRun(ctx interface{}, runID interface{}) *MockGameRepositoryInterface_FindActiveQRByRun_Call {
	return &MockGameRepositoryInterface_FindActiveQRByRun_Call{Call: _e.mock.On("FindActiveQRByRun", ctx, runID)}
}

func (_c *MockGameRepositoryInterface_FindActiveQRByRun_Call) Run(run func(ctx context.Context, runID string)) *MockGameRepositoryInterface_FindActiveQRByRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindActiveQRByRun_Call) Return(qRCode *entities.QRCode, err error) *MockGameRepositoryInterface_FindActiveQRByRun_Call {
	_c.Call.Return(qRCode, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindActiveQRByRun_Call) RunAndReturn(run func(ctx context.Context, runID string) (*entities.QRCode, error)) *MockGameRepositoryInterface_FindActiveQRByRun_Call {
	_c.Call.Return(run)
	return _c
}

// FindCurrentParticipation provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindCurrentParticipation(ctx context.Context, userID uint64) (*entities.Participation, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindCurrentParticipation")
	}

	var r0 *entities.Participation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entities.Participation, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entities.Participation); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Participation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindCurrentParticipation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCurrentParticipation'
type MockGameRepositoryInterface_FindCurrentParticipation_Call struct {
	*mock.Call
}

// FindCurrentParticipation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockGameRepositoryInterface_Expecter) FindCurrentParticipation(ctx interface{}, userID interface{}) *MockGameRepositoryInterface_FindCurrentParticipation_Call {
	return &MockGameRepositoryInterface_FindCurrentParticipation_Call{Call: _e.mock.On("FindCurrentParticipation", ctx, userID)}
}

func (_c *MockGameRepositoryInterface_FindCurrentParticipation_Call) Run(run func(ctx context.Context, userID uint64)) *MockGameRepositoryInterface_FindCurrentParticipation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindCurrentParticipation_Call) Return(participation *entities.Participation, err error) *MockGameRepositoryInterface_FindCurrentParticipation_Call {
	_c.Call.Return(participation, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindCurrentParticipation_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (*entities.Participation, error)) *MockGameRepositoryInterface_FindCurrentParticipation_Call {
	_c.Call.Return(run)
	return _c
}

// FindCurrentRanking provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindCurrentRanking(ctx context.Context, userID uint64) (*entities.IndividualRanking, *entities.GroupRanking, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindCurrentRanking")
	}

	var r0 *entities.IndividualRanking
	var r1 *entities.GroupRanking
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entities.IndividualRanking, *entities.GroupRanking, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entities.IndividualRanking); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.IndividualRanking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) *entities.GroupRanking); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.GroupRanking)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint64) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGameRepositoryInterface_FindCurrentRanking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCurrentRanking'
type MockGameRepositoryInterface_FindCurrentRanking_Call struct {
	*mock.Call
}

// FindCurrentRanking is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockGameRepositoryInterface_Expecter) FindCurrentRanking(ctx interface{}, userID interface{}) *MockGameRepositoryInterface_FindCurrentRanking_Call {
	return &MockGameRepositoryInterface_FindCurrentRanking_Call{Call: _e.mock.On("FindCurrentRanking", ctx, userID)}
}

func (_c *MockGameRepositoryInterface_FindCurrentRanking_Call) Run(run func(ctx context.Context, userID uint64)) *MockGameRepositoryInterface_FindCurrentRanking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindCurrentRanking_Call) Return(individualRanking *entities.IndividualRanking, groupRanking *entities.GroupRanking, err error) *MockGameRepositoryInterface_FindCurrentRanking_Call {
	_c.Call.Return(individualRanking, groupRanking, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindCurrentRanking_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (*entities.IndividualRanking, *entities.GroupRanking, error)) *MockGameRepositoryInterface_FindCurrentRanking_Call {
	_c.Call.Return(run)
	return _c
}

// FindManageableActivityForUpdate provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindManageableActivityForUpdate(ctx context.Context, activityID string, actorUserID uint64, global bool, generatedAt time.Time) (*entities1.Activity, error) {
	ret := _mock.Called(ctx, activityID, actorUserID, global, generatedAt)

	if len(ret) == 0 {
		panic("no return value specified for FindManageableActivityForUpdate")
	}

	var r0 *entities1.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool, time.Time) (*entities1.Activity, error)); ok {
		return returnFunc(ctx, activityID, actorUserID, global, generatedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool, time.Time) *entities1.Activity); ok {
		r0 = returnFunc(ctx, activityID, actorUserID, global, generatedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities1.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, bool, time.Time) error); ok {
		r1 = returnFunc(ctx, activityID, actorUserID, global, generatedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindManageableActivityForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindManageableActivityForUpdate'
type MockGameRepositoryInterface_FindManageableActivityForUpdate_Call struct {
	*mock.Call
}

// FindManageableActivityForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID string
//   - actorUserID uint64
//   - global bool
//   - generatedAt time.Time
func (_e *MockGameRepositoryInterface_Expecter) FindManageableActivityForUpdate(ctx interface{}, activityID interface{}, actorUserID interface{}, global interface{}, generatedAt interface{}) *MockGameRepositoryInterface_FindManageableActivityForUpdate_Call {
	return &MockGameRepositoryInterface_FindManageableActivityForUpdate_Call{Call: _e.mock.On("FindManageableActivityForUpdate", ctx, activityID, actorUserID, global, generatedAt)}
}

func (_c *MockGameRepositoryInterface_FindManageableActivityForUpdate_Call) Run(run func(ctx context.Context, activityID string, actorUserID uint64, global bool, generatedAt time.Time)) *MockGameRepositoryInterface_FindManageableActivityForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindManageableActivityForUpdate_Call) Return(activity *entities1.Activity, err error) *MockGameRepositoryInterface_FindManageableActivityForUpdate_Call {
	_c.Call.Return(activity, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindManageableActivityForUpdate_Call) RunAndReturn(run func(ctx context.Context, activityID string, actorUserID uint64, global bool, generatedAt time.Time) (*entities1.Activity, error)) *MockGameRepositoryInterface_FindManageableActivityForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindManagerOperation provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindManagerOperation(ctx context.Context, actorUserID uint64, key string) (*entities.ManagerOperation, error) {
	ret := _mock.Called(ctx, actorUserID, key)

	if len(ret) == 0 {
		panic("no return value specified for FindManagerOperation")
	}

	var r0 *entities.ManagerOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (*entities.ManagerOperation, error)); ok {
		return returnFunc(ctx, actorUserID, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) *entities.ManagerOperation); ok {
		r0 = returnFunc(ctx, actorUserID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ManagerOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(ctx, actorUserID, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindManagerOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindManagerOperation'
type MockGameRepositoryInterface_FindManagerOperation_Call struct {
	*mock.Call
}

// FindManagerOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID uint64
//   - key string
func (_e *MockGameRepositoryInterface_Expecter) FindManagerOperation(ctx interface{}, actorUserID interface{}, key interface{}) *MockGameRepositoryInterface_FindManagerOperation_Call {
	return &MockGameRepositoryInterface_FindManagerOperation_Call{Call: _e.mock.On("FindManagerOperation", ctx, actorUserID, key)}
}

func (_c *MockGameRepositoryInterface_FindManagerOperation_Call) Run(run func(ctx context.Context, actorUserID uint64, key string)) *MockGameRepositoryInterface_FindManagerOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindManagerOperation_Call) Return(managerOperation *entities.ManagerOperation, err error) *MockGameRepositoryInterface_FindManagerOperation_Call {
	_c.Call.Return(managerOperation, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindManagerOperation_Call) RunAndReturn(run func(ctx context.Context, actorUserID uint64, key string) (*entities.ManagerOperation, error)) *MockGameRepositoryInterface_FindManagerOperation_Call {
	_c.Call.Return(run)
	return _c
}

// FindOpenRunByActivityForUpdate provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindOpenRunByActivityForUpdate(ctx context.Context, activityID string) (*entities.ActivityRun, error) {
	ret := _mock.Called(ctx, activityID)

	if len(ret) == 0 {
		panic("no return value specified for FindOpenRunByActivityForUpdate")
	}

	var r0 *entities.ActivityRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.ActivityRun, error)); ok {
		return returnFunc(ctx, activityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.ActivityRun); ok {
		r0 = returnFunc(ctx, activityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ActivityRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, activityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOpenRunByActivityForUpdate'
type MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call struct {
	*mock.Call
}

// FindOpenRunByActivityForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID string
func (_e *MockGameRepositoryInterface_Expecter) FindOpenRunByActivityForUpdate(ctx interface{}, activityID interface{}) *MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call {
	return &MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call{Call: _e.mock.On("FindOpenRunByActivityForUpdate", ctx, activityID)}
}

func (_c *MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call) Run(run func(ctx context.Context, activityID string)) *MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call) Return(activityRun *entities.ActivityRun, err error) *MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call {
	_c.Call.Return(activityRun, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call) RunAndReturn(run func(ctx context.Context, activityID string) (*entities.ActivityRun, error)) *MockGameRepositoryInterface_FindOpenRunByActivityForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindOpenRunForManager provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindOpenRunForManager(ctx context.Context, actorUserID uint64, global bool) (*entities.ActivityRun, error) {
	ret := _mock.Called(ctx, actorUserID, global)

	if len(ret) == 0 {
		panic("no return value specified for FindOpenRunForManager")
	}

	var r0 *entities.ActivityRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, bool) (*entities.ActivityRun, error)); ok {
		return returnFunc(ctx, actorUserID, global)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, bool) *entities.ActivityRun); ok {
		r0 = returnFunc(ctx, actorUserID, global)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ActivityRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, bool) error); ok {
		r1 = returnFunc(ctx, actorUserID, global)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindOpenRunForManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOpenRunForManager'
type MockGameRepositoryInterface_FindOpenRunForManager_Call struct {
	*mock.Call
}

// FindOpenRunForManager is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID uint64
//   - global bool
func (_e *MockGameRepositoryInterface_Expecter) FindOpenRunForManager(ctx interface{}, actorUserID interface{}, global interface{}) *MockGameRepositoryInterface_FindOpenRunForManager_Call {
	return &MockGameRepositoryInterface_FindOpenRunForManager_Call{Call: _e.mock.On("FindOpenRunForManager", ctx, actorUserID, global)}
}

func (_c *MockGameRepositoryInterface_FindOpenRunForManager_Call) Run(run func(ctx context.Context, actorUserID uint64, global bool)) *MockGameRepositoryInterface_FindOpenRunForManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindOpenRunForManager_Call) Return(activityRun *entities.ActivityRun, err error) *MockGameRepositoryInterface_FindOpenRunForManager_Call {
	_c.Call.Return(activityRun, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindOpenRunForManager_Call) RunAndReturn(run func(ctx context.Context, actorUserID uint64, global bool) (*entities.ActivityRun, error)) *MockGameRepositoryInterface_FindOpenRunForManager_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipantOperation provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindParticipantOperation(ctx context.Context, actorUserID uint64, key string) (*entities0.ParticipantOperation, error) {
	ret := _mock.Called(ctx, actorUserID, key)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipantOperation")
	}

	var r0 *entities0.ParticipantOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (*entities0.ParticipantOperation, error)); ok {
		return returnFunc(ctx, actorUserID, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) *entities0.ParticipantOperation); ok {
		r0 = returnFunc(ctx, actorUserID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities0.ParticipantOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(ctx, actorUserID, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindParticipantOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipantOperation'
type MockGameRepositoryInterface_FindParticipantOperation_Call struct {
	*mock.Call
}

// FindParticipantOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID uint64
//   - key string
func (_e *MockGameRepositoryInterface_Expecter) FindParticipantOperation(ctx interface{}, actorUserID interface{}, key interface{}) *MockGameRepositoryInterface_FindParticipantOperation_Call {
	return &MockGameRepositoryInterface_FindParticipantOperation_Call{Call: _e.mock.On("FindParticipantOperation", ctx, actorUserID, key)}
}

func (_c *MockGameRepositoryInterface_FindParticipantOperation_Call) Run(run func(ctx context.Context, actorUserID uint64, key string)) *MockGameRepositoryInterface_FindParticipantOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindParticipantOperation_Call) Return(participantOperation *entities0.ParticipantOperation, err error) *MockGameRepositoryInterface_FindParticipantOperation_Call {
	_c.Call.Return(participantOperation, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindParticipantOperation_Call) RunAndReturn(run func(ctx context.Context, actorUserID uint64, key string) (*entities0.ParticipantOperation, error)) *MockGameRepositoryInterface_FindParticipantOperation_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipationByID provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindParticipationByID(ctx context.Context, participationID string) (*entities.Participation, error) {
	ret := _mock.Called(ctx, participationID)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipationByID")
	}

	var r0 *entities.Participation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Participation, error)); ok {
		return returnFunc(ctx, participationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Participation); ok {
		r0 = returnFunc(ctx, participationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Participation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, participationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindParticipationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipationByID'
type MockGameRepositoryInterface_FindParticipationByID_Call struct {
	*mock.Call
}

// FindParticipationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - participationID string
func (_e *MockGameRepositoryInterface_Expecter) FindParticipationByID(ctx interface{}, participationID interface{}) *MockGameRepositoryInterface_FindParticipationByID_Call {
	return &MockGameRepositoryInterface_FindParticipationByID_Call{Call: _e.mock.On("FindParticipationByID", ctx, participationID)}
}

func (_c *MockGameRepositoryInterface_FindParticipationByID_Call) Run(run func(ctx context.Context, participationID string)) *MockGameRepositoryInterface_FindParticipationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindParticipationByID_Call) Return(participation *entities.Participation, err error) *MockGameRepositoryInterface_FindParticipationByID_Call {
	_c.Call.Return(participation, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindParticipationByID_Call) RunAndReturn(run func(ctx context.Context, participationID string) (*entities.Participation, error)) *MockGameRepositoryInterface_FindParticipationByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipationByRunAndUser provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindParticipationByRunAndUser(ctx context.Context, runID string, userID uint64) (*entities.Participation, error) {
	ret := _mock.Called(ctx, runID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipationByRunAndUser")
	}

	var r0 *entities.Participation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) (*entities.Participation, error)); ok {
		return returnFunc(ctx, runID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) *entities.Participation); ok {
		r0 = returnFunc(ctx, runID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Participation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64) error); ok {
		r1 = returnFunc(ctx, runID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindParticipationByRunAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipationByRunAndUser'
type MockGameRepositoryInterface_FindParticipationByRunAndUser_Call struct {
	*mock.Call
}

// FindParticipationByRunAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - userID uint64
func (_e *MockGameRepositoryInterface_Expecter) FindParticipationByRunAndUser(ctx interface{}, runID interface{}, userID interface{}) *MockGameRepositoryInterface_FindParticipationByRunAndUser_Call {
	return &MockGameRepositoryInterface_FindParticipationByRunAndUser_Call{Call: _e.mock.On("FindParticipationByRunAndUser", ctx, runID, userID)}
}

func (_c *MockGameRepositoryInterface_FindParticipationByRunAndUser_Call) Run(run func(ctx context.Context, runID string, userID uint64)) *MockGameRepositoryInterface_FindParticipationByRunAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindParticipationByRunAndUser_Call) Return(participation *entities.Participation, err error) *MockGameRepositoryInterface_FindParticipationByRunAndUser_Call {
	_c.Call.Return(participation, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindParticipationByRunAndUser_Call) RunAndReturn(run func(ctx context.Context, runID string, userID uint64) (*entities.Participation, error)) *MockGameRepositoryInterface_FindParticipationByRunAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindPublicGame provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindPublicGame(ctx context.Context, activityID string, generatedAt time.Time) (*entities1.PublicActivity, error) {
	ret := _mock.Called(ctx, activityID, generatedAt)

	if len(ret) == 0 {
		panic("no return value specified for FindPublicGame")
	}

	var r0 *entities1.PublicActivity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (*entities1.PublicActivity, error)); ok {
		return returnFunc(ctx, activityID, generatedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) *entities1.PublicActivity); ok {
		r0 = returnFunc(ctx, activityID, generatedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities1.PublicActivity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, activityID, generatedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindPublicGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPublicGame'
type MockGameRepositoryInterface_FindPublicGame_Call struct {
	*mock.Call
}

// FindPublicGame is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID string
//   - generatedAt time.Time
func (_e *MockGameRepositoryInterface_Expecter) FindPublicGame(ctx interface{}, activityID interface{}, generatedAt interface{}) *MockGameRepositoryInterface_FindPublicGame_Call {
	return &MockGameRepositoryInterface_FindPublicGame_Call{Call: _e.mock.On("FindPublicGame", ctx, activityID, generatedAt)}
}

func (_c *MockGameRepositoryInterface_FindPublicGame_Call) Run(run func(ctx context.Context, activityID string, generatedAt time.Time)) *MockGameRepositoryInterface_FindPublicGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindPublicGame_Call) Return(publicActivity *entities1.PublicActivity, err error) *MockGameRepositoryInterface_FindPublicGame_Call {
	_c.Call.Return(publicActivity, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindPublicGame_Call) RunAndReturn(run func(ctx context.Context, activityID string, generatedAt time.Time) (*entities1.PublicActivity, error)) *MockGameRepositoryInterface_FindPublicGame_Call {
	_c.Call.Return(run)
	return _c
}

// FindQRByTokenHashForUpdate provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindQRByTokenHashForUpdate(ctx context.Context, tokenHash string, generatedAt time.Time) (*entities.QRCode, error) {
	ret := _mock.Called(ctx, tokenHash, generatedAt)

	if len(ret) == 0 {
		panic("no return value specified for FindQRByTokenHashForUpdate")
	}

	var r0 *entities.QRCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (*entities.QRCode, error)); ok {
		return returnFunc(ctx, tokenHash, generatedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) *entities.QRCode); ok {
		r0 = returnFunc(ctx, tokenHash, generatedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.QRCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, tokenHash, generatedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindQRByTokenHashForUpdate'
type MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call struct {
	*mock.Call
}

// FindQRByTokenHashForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - generatedAt time.Time
func (_e *MockGameRepositoryInterface_Expecter) FindQRByTokenHashForUpdate(ctx interface{}, tokenHash interface{}, generatedAt interface{}) *MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call {
	return &MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call{Call: _e.mock.On("FindQRByTokenHashForUpdate", ctx, tokenHash, generatedAt)}
}

func (_c *MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call) Run(run func(ctx context.Context, tokenHash string, generatedAt time.Time)) *MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call) Return(qRCode *entities.QRCode, err error) *MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call {
	_c.Call.Return(qRCode, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call) RunAndReturn(run func(ctx context.Context, tokenHash string, generatedAt time.Time) (*entities.QRCode, error)) *MockGameRepositoryInterface_FindQRByTokenHashForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindRunForManager provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindRunForManager(ctx context.Context, runID string, actorUserID uint64, global bool, lock bool) (*entities.ActivityRun, error) {
	ret := _mock.Called(ctx, runID, actorUserID, global, lock)

	if len(ret) == 0 {
		panic("no return value specified for FindRunForManager")
	}

	var r0 *entities.ActivityRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool, bool) (*entities.ActivityRun, error)); ok {
		return returnFunc(ctx, runID, actorUserID, global, lock)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool, bool) *entities.ActivityRun); ok {
		r0 = returnFunc(ctx, runID, actorUserID, global, lock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ActivityRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, bool, bool) error); ok {
		r1 = returnFunc(ctx, runID, actorUserID, global, lock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_FindRunForManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRunForManager'
type MockGameRepositoryInterface_FindRunForManager_Call struct {
	*mock.Call
}

// FindRunForManager is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - actorUserID uint64
//   - global bool
//   - lock bool
func (_e *MockGameRepositoryInterface_Expecter) FindRunForManager(ctx interface{}, runID interface{}, actorUserID interface{}, global interface{}, lock interface{}) *MockGameRepositoryInterface_FindRunForManager_Call {
	return &MockGameRepositoryInterface_FindRunForManager_Call{Call: _e.mock.On("FindRunForManager", ctx, runID, actorUserID, global, lock)}
}

func (_c *MockGameRepositoryInterface_FindRunForManager_Call) Run(run func(ctx context.Context, runID string, actorUserID uint64, global bool, lock bool)) *MockGameRepositoryInterface_FindRunForManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindRunForManager_Call) Return(activityRun *entities.ActivityRun, err error) *MockGameRepositoryInterface_FindRunForManager_Call {
	_c.Call.Return(activityRun, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindRunForManager_Call) RunAndReturn(run func(ctx context.Context, runID string, actorUserID uint64, global bool, lock bool) (*entities.ActivityRun, error)) *MockGameRepositoryInterface_FindRunForManager_Call {
	_c.Call.Return(run)
	return _c
}

// FindRunForParticipant provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) FindRunForParticipant(ctx context.Context, userID uint64, runID *string) (*entities.ActivityRun, *entities.RunParticipant, error) {
	ret := _mock.Called(ctx, userID, runID)

	if len(ret) == 0 {
		panic("no return value specified for FindRunForParticipant")
	}

	var r0 *entities.ActivityRun
	var r1 *entities.RunParticipant
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *string) (*entities.ActivityRun, *entities.RunParticipant, error)); ok {
		return returnFunc(ctx, userID, runID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *string) *entities.ActivityRun); ok {
		r0 = returnFunc(ctx, userID, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ActivityRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *string) *entities.RunParticipant); ok {
		r1 = returnFunc(ctx, userID, runID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.RunParticipant)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint64, *string) error); ok {
		r2 = returnFunc(ctx, userID, runID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGameRepositoryInterface_FindRunForParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRunForParticipant'
type MockGameRepositoryInterface_FindRunForParticipant_Call struct {
	*mock.Call
}

// FindRunForParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - runID *string
func (_e *MockGameRepositoryInterface_Expecter) FindRunForParticipant(ctx interface{}, userID interface{}, runID interface{}) *MockGameRepositoryInterface_FindRunForParticipant_Call {
	return &MockGameRepositoryInterface_FindRunForParticipant_Call{Call: _e.mock.On("FindRunForParticipant", ctx, userID, runID)}
}

func (_c *MockGameRepositoryInterface_FindRunForParticipant_Call) Run(run func(ctx context.Context, userID uint64, runID *string)) *MockGameRepositoryInterface_FindRunForParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_FindRunForParticipant_Call) Return(activityRun *entities.ActivityRun, runParticipant *entities.RunParticipant, err error) *MockGameRepositoryInterface_FindRunForParticipant_Call {
	_c.Call.Return(activityRun, runParticipant, err)
	return _c
}

func (_c *MockGameRepositoryInterface_FindRunForParticipant_Call) RunAndReturn(run func(ctx context.Context, userID uint64, runID *string) (*entities.ActivityRun, *entities.RunParticipant, error)) *MockGameRepositoryInterface_FindRunForParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroupRankings provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) ListGroupRankings(ctx context.Context, page uint64) (*messages.PaginatedResponse[entities.GroupRanking], error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupRankings")
	}

	var r0 *messages.PaginatedResponse[entities.GroupRanking]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*messages.PaginatedResponse[entities.GroupRanking], error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *messages.PaginatedResponse[entities.GroupRanking]); ok {
		r0 = returnFunc(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.PaginatedResponse[entities.GroupRanking])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_ListGroupRankings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupRankings'
type MockGameRepositoryInterface_ListGroupRankings_Call struct {
	*mock.Call
}

// ListGroupRankings is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint64
func (_e *MockGameRepositoryInterface_Expecter) ListGroupRankings(ctx interface{}, page interface{}) *MockGameRepositoryInterface_ListGroupRankings_Call {
	return &MockGameRepositoryInterface_ListGroupRankings_Call{Call: _e.mock.On("ListGroupRankings", ctx, page)}
}

func (_c *MockGameRepositoryInterface_ListGroupRankings_Call) Run(run func(ctx context.Context, page uint64)) *MockGameRepositoryInterface_ListGroupRankings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_ListGroupRankings_Call) Return(paginatedResponse *messages.PaginatedResponse[entities.GroupRanking], err error) *MockGameRepositoryInterface_ListGroupRankings_Call {
	_c.Call.Return(paginatedResponse, err)
	return _c
}

func (_c *MockGameRepositoryInterface_ListGroupRankings_Call) RunAndReturn(run func(ctx context.Context, page uint64) (*messages.PaginatedResponse[entities.GroupRanking], error)) *MockGameRepositoryInterface_ListGroupRankings_Call {
	_c.Call.Return(run)
	return _c
}

// ListIndividualRankings provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) ListIndividualRankings(ctx context.Context, page uint64) (*messages.PaginatedResponse[entities.IndividualRanking], error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for ListIndividualRankings")
	}

	var r0 *messages.PaginatedResponse[entities.IndividualRanking]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*messages.PaginatedResponse[entities.IndividualRanking], error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *messages.PaginatedResponse[entities.IndividualRanking]); ok {
		r0 = returnFunc(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.PaginatedResponse[entities.IndividualRanking])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_ListIndividualRankings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIndividualRankings'
type MockGameRepositoryInterface_ListIndividualRankings_Call struct {
	*mock.Call
}

// ListIndividualRankings is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint64
func (_e *MockGameRepositoryInterface_Expecter) ListIndividualRankings(ctx interface{}, page interface{}) *MockGameRepositoryInterface_ListIndividualRankings_Call {
	return &MockGameRepositoryInterface_ListIndividualRankings_Call{Call: _e.mock.On("ListIndividualRankings", ctx, page)}
}

func (_c *MockGameRepositoryInterface_ListIndividualRankings_Call) Run(run func(ctx context.Context, page uint64)) *MockGameRepositoryInterface_ListIndividualRankings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_ListIndividualRankings_Call) Return(paginatedResponse *messages.PaginatedResponse[entities.IndividualRanking], err error) *MockGameRepositoryInterface_ListIndividualRankings_Call {
	_c.Call.Return(paginatedResponse, err)
	return _c
}

func (_c *MockGameRepositoryInterface_ListIndividualRankings_Call) RunAndReturn(run func(ctx context.Context, page uint64) (*messages.PaginatedResponse[entities.IndividualRanking], error)) *MockGameRepositoryInterface_ListIndividualRankings_Call {
	_c.Call.Return(run)
	return _c
}

// ListManageableGames provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) ListManageableGames(ctx context.Context, actorUserID uint64, global bool, generatedAt time.Time) ([]entities1.PublicActivity, error) {
	ret := _mock.Called(ctx, actorUserID, global, generatedAt)

	if len(ret) == 0 {
		panic("no return value specified for ListManageableGames")
	}

	var r0 []entities1.PublicActivity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, bool, time.Time) ([]entities1.PublicActivity, error)); ok {
		return returnFunc(ctx, actorUserID, global, generatedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, bool, time.Time) []entities1.PublicActivity); ok {
		r0 = returnFunc(ctx, actorUserID, global, generatedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities1.PublicActivity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, bool, time.Time) error); ok {
		r1 = returnFunc(ctx, actorUserID, global, generatedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_ListManageableGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManageableGames'
type MockGameRepositoryInterface_ListManageableGames_Call struct {
	*mock.Call
}

// ListManageableGames is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID uint64
//   - global bool
//   - generatedAt time.Time
func (_e *MockGameRepositoryInterface_Expecter) ListManageableGames(ctx interface{}, actorUserID interface{}, global interface{}, generatedAt interface{}) *MockGameRepositoryInterface_ListManageableGames_Call {
	return &MockGameRepositoryInterface_ListManageableGames_Call{Call: _e.mock.On("ListManageableGames", ctx, actorUserID, global, generatedAt)}
}

func (_c *MockGameRepositoryInterface_ListManageableGames_Call) Run(run func(ctx context.Context, actorUserID uint64, global bool, generatedAt time.Time)) *MockGameRepositoryInterface_ListManageableGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_ListManageableGames_Call) Return(publicActivitys []entities1.PublicActivity, err error) *MockGameRepositoryInterface_ListManageableGames_Call {
	_c.Call.Return(publicActivitys, err)
	return _c
}

func (_c *MockGameRepositoryInterface_ListManageableGames_Call) RunAndReturn(run func(ctx context.Context, actorUserID uint64, global bool, generatedAt time.Time) ([]entities1.PublicActivity, error)) *MockGameRepositoryInterface_ListManageableGames_Call {
	_c.Call.Return(run)
	return _c
}

// ListPointBalanceMismatches provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) ListPointBalanceMismatches(ctx context.Context) ([]entities.PointBalanceMismatch, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPointBalanceMismatches")
	}

	var r0 []entities.PointBalanceMismatch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.PointBalanceMismatch, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.PointBalanceMismatch); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.PointBalanceMismatch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_ListPointBalanceMismatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPointBalanceMismatches'
type MockGameRepositoryInterface_ListPointBalanceMismatches_Call struct {
	*mock.Call
}

// ListPointBalanceMismatches is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGameRepositoryInterface_Expecter) ListPointBalanceMismatches(ctx interface{}) *MockGameRepositoryInterface_ListPointBalanceMismatches_Call {
	return &MockGameRepositoryInterface_ListPointBalanceMismatches_Call{Call: _e.mock.On("ListPointBalanceMismatches", ctx)}
}

func (_c *MockGameRepositoryInterface_ListPointBalanceMismatches_Call) Run(run func(ctx context.Context)) *MockGameRepositoryInterface_ListPointBalanceMismatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_ListPointBalanceMismatches_Call) Return(pointBalanceMismatchs []entities.PointBalanceMismatch, err error) *MockGameRepositoryInterface_ListPointBalanceMismatches_Call {
	_c.Call.Return(pointBalanceMismatchs, err)
	return _c
}

func (_c *MockGameRepositoryInterface_ListPointBalanceMismatches_Call) RunAndReturn(run func(ctx context.Context) ([]entities.PointBalanceMismatch, error)) *MockGameRepositoryInterface_ListPointBalanceMismatches_Call {
	_c.Call.Return(run)
	return _c
}

// ListPointEntries provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) ListPointEntries(ctx context.Context, userID uint64, limit int) ([]entities.PointEntry, error) {
	ret := _mock.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPointEntries")
	}

	var r0 []entities.PointEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, int) ([]entities.PointEntry, error)); ok {
		return returnFunc(ctx, userID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, int) []entities.PointEntry); ok {
		r0 = returnFunc(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.PointEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, int) error); ok {
		r1 = returnFunc(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_ListPointEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPointEntries'
type MockGameRepositoryInterface_ListPointEntries_Call struct {
	*mock.Call
}

// ListPointEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - limit int
func (_e *MockGameRepositoryInterface_Expecter) ListPointEntries(ctx interface{}, userID interface{}, limit interface{}) *MockGameRepositoryInterface_ListPointEntries_Call {
	return &MockGameRepositoryInterface_ListPointEntries_Call{Call: _e.mock.On("ListPointEntries", ctx, userID, limit)}
}

func (_c *MockGameRepositoryInterface_ListPointEntries_Call) Run(run func(ctx context.Context, userID uint64, limit int)) *MockGameRepositoryInterface_ListPointEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_ListPointEntries_Call) Return(pointEntrys []entities.PointEntry, err error) *MockGameRepositoryInterface_ListPointEntries_Call {
	_c.Call.Return(pointEntrys, err)
	return _c
}

func (_c *MockGameRepositoryInterface_ListPointEntries_Call) RunAndReturn(run func(ctx context.Context, userID uint64, limit int) ([]entities.PointEntry, error)) *MockGameRepositoryInterface_ListPointEntries_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublicGames provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) ListPublicGames(ctx context.Context, generatedAt time.Time, page uint64) (*messages.PaginatedResponse[entities1.PublicActivity], error) {
	ret := _mock.Called(ctx, generatedAt, page)

	if len(ret) == 0 {
		panic("no return value specified for ListPublicGames")
	}

	var r0 *messages.PaginatedResponse[entities1.PublicActivity]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, uint64) (*messages.PaginatedResponse[entities1.PublicActivity], error)); ok {
		return returnFunc(ctx, generatedAt, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, uint64) *messages.PaginatedResponse[entities1.PublicActivity]); ok {
		r0 = returnFunc(ctx, generatedAt, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.PaginatedResponse[entities1.PublicActivity])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, uint64) error); ok {
		r1 = returnFunc(ctx, generatedAt, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_ListPublicGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublicGames'
type MockGameRepositoryInterface_ListPublicGames_Call struct {
	*mock.Call
}

// ListPublicGames is a helper method to define mock.On call
//   - ctx context.Context
//   - generatedAt time.Time
//   - page uint64
func (_e *MockGameRepositoryInterface_Expecter) ListPublicGames(ctx interface{}, generatedAt interface{}, page interface{}) *MockGameRepositoryInterface_ListPublicGames_Call {
	return &MockGameRepositoryInterface_ListPublicGames_Call{Call: _e.mock.On("ListPublicGames", ctx, generatedAt, page)}
}

func (_c *MockGameRepositoryInterface_ListPublicGames_Call) Run(run func(ctx context.Context, generatedAt time.Time, page uint64)) *MockGameRepositoryInterface_ListPublicGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_ListPublicGames_Call) Return(paginatedResponse *messages.PaginatedResponse[entities1.PublicActivity], err error) *MockGameRepositoryInterface_ListPublicGames_Call {
	_c.Call.Return(paginatedResponse, err)
	return _c
}

func (_c *MockGameRepositoryInterface_ListPublicGames_Call) RunAndReturn(run func(ctx context.Context, generatedAt time.Time, page uint64) (*messages.PaginatedResponse[entities1.PublicActivity], error)) *MockGameRepositoryInterface_ListPublicGames_Call {
	_c.Call.Return(run)
	return _c
}

// ListRunParticipants provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) ListRunParticipants(ctx context.Context, runID string) ([]entities.RunParticipant, error) {
	ret := _mock.Called(ctx, runID)

	if len(ret) == 0 {
		panic("no return value specified for ListRunParticipants")
	}

	var r0 []entities.RunParticipant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entities.RunParticipant, error)); ok {
		return returnFunc(ctx, runID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entities.RunParticipant); ok {
		r0 = returnFunc(ctx, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.RunParticipant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, runID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_ListRunParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRunParticipants'
type MockGameRepositoryInterface_ListRunParticipants_Call struct {
	*mock.Call
}

// ListRunParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
func (_e *MockGameRepositoryInterface_Expecter) ListRunParticipants(ctx interface{}, runID interface{}) *MockGameRepositoryInterface_ListRunParticipants_Call {
	return &MockGameRepositoryInterface_ListRunParticipants_Call{Call: _e.mock.On("ListRunParticipants", ctx, runID)}
}

func (_c *MockGameRepositoryInterface_ListRunParticipants_Call) Run(run func(ctx context.Context, runID string)) *MockGameRepositoryInterface_ListRunParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_ListRunParticipants_Call) Return(runParticipants []entities.RunParticipant, err error) *MockGameRepositoryInterface_ListRunParticipants_Call {
	_c.Call.Return(runParticipants, err)
	return _c
}

func (_c *MockGameRepositoryInterface_ListRunParticipants_Call) RunAndReturn(run func(ctx context.Context, runID string) ([]entities.RunParticipant, error)) *MockGameRepositoryInterface_ListRunParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// LockUsers provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) LockUsers(ctx context.Context, userIDs []uint64) error {
	ret := _mock.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for LockUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint64) error); ok {
		r0 = returnFunc(ctx, userIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGameRepositoryInterface_LockUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockUsers'
type MockGameRepositoryInterface_LockUsers_Call struct {
	*mock.Call
}

// LockUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []uint64
func (_e *MockGameRepositoryInterface_Expecter) LockUsers(ctx interface{}, userIDs interface{}) *MockGameRepositoryInterface_LockUsers_Call {
	return &MockGameRepositoryInterface_LockUsers_Call{Call: _e.mock.On("LockUsers", ctx, userIDs)}
}

func (_c *MockGameRepositoryInterface_LockUsers_Call) Run(run func(ctx context.Context, userIDs []uint64)) *MockGameRepositoryInterface_LockUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint64
		if args[1] != nil {
			arg1 = args[1].([]uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_LockUsers_Call) Return(err error) *MockGameRepositoryInterface_LockUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGameRepositoryInterface_LockUsers_Call) RunAndReturn(run func(ctx context.Context, userIDs []uint64) error) *MockGameRepositoryInterface_LockUsers_Call {
	_c.Call.Return(run)
	return _c
}

// TopGroupRankings provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) TopGroupRankings(ctx context.Context, limit int) ([]entities.GroupRanking, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for TopGroupRankings")
	}

	var r0 []entities.GroupRanking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]entities.GroupRanking, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []entities.GroupRanking); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.GroupRanking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_TopGroupRankings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopGroupRankings'
type MockGameRepositoryInterface_TopGroupRankings_Call struct {
	*mock.Call
}

// TopGroupRankings is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockGameRepositoryInterface_Expecter) TopGroupRankings(ctx interface{}, limit interface{}) *MockGameRepositoryInterface_TopGroupRankings_Call {
	return &MockGameRepositoryInterface_TopGroupRankings_Call{Call: _e.mock.On("TopGroupRankings", ctx, limit)}
}

func (_c *MockGameRepositoryInterface_TopGroupRankings_Call) Run(run func(ctx context.Context, limit int)) *MockGameRepositoryInterface_TopGroupRankings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_TopGroupRankings_Call) Return(groupRankings []entities.GroupRanking, err error) *MockGameRepositoryInterface_TopGroupRankings_Call {
	_c.Call.Return(groupRankings, err)
	return _c
}

func (_c *MockGameRepositoryInterface_TopGroupRankings_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]entities.GroupRanking, error)) *MockGameRepositoryInterface_TopGroupRankings_Call {
	_c.Call.Return(run)
	return _c
}

// TopIndividualRankings provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) TopIndividualRankings(ctx context.Context, limit int) ([]entities.IndividualRanking, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for TopIndividualRankings")
	}

	var r0 []entities.IndividualRanking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]entities.IndividualRanking, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []entities.IndividualRanking); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.IndividualRanking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepositoryInterface_TopIndividualRankings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopIndividualRankings'
type MockGameRepositoryInterface_TopIndividualRankings_Call struct {
	*mock.Call
}

// TopIndividualRankings is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockGameRepositoryInterface_Expecter) TopIndividualRankings(ctx interface{}, limit interface{}) *MockGameRepositoryInterface_TopIndividualRankings_Call {
	return &MockGameRepositoryInterface_TopIndividualRankings_Call{Call: _e.mock.On("TopIndividualRankings", ctx, limit)}
}

func (_c *MockGameRepositoryInterface_TopIndividualRankings_Call) Run(run func(ctx context.Context, limit int)) *MockGameRepositoryInterface_TopIndividualRankings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_TopIndividualRankings_Call) Return(individualRankings []entities.IndividualRanking, err error) *MockGameRepositoryInterface_TopIndividualRankings_Call {
	_c.Call.Return(individualRankings, err)
	return _c
}

func (_c *MockGameRepositoryInterface_TopIndividualRankings_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]entities.IndividualRanking, error)) *MockGameRepositoryInterface_TopIndividualRankings_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionRun provides a mock function for the type MockGameRepositoryInterface
func (_mock *MockGameRepositoryInterface) TransitionRun(ctx context.Context, runID string, from entities.RunStatus, to entities.RunStatus, startedAt *time.Time, endedAt *time.Time, updatedAt time.Time) error {
	ret := _mock.Called(ctx, runID, from, to, startedAt, endedAt, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for TransitionRun")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.RunStatus, entities.RunStatus, *time.Time, *time.Time, time.Time) error); ok {
		r0 = returnFunc(ctx, runID, from, to, startedAt, endedAt, updatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGameRepositoryInterface_TransitionRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionRun'
type MockGameRepositoryInterface_TransitionRun_Call struct {
	*mock.Call
}

// TransitionRun is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - from entities.RunStatus
//   - to entities.RunStatus
//   - startedAt *time.Time
//   - endedAt *time.Time
//   - updatedAt time.Time
func (_e *MockGameRepositoryInterface_Expecter) TransitionRun(ctx interface{}, runID interface{}, from interface{}, to interface{}, startedAt interface{}, endedAt interface{}, updatedAt interface{}) *MockGameRepositoryInterface_TransitionRun_Call {
	return &MockGameRepositoryInterface_TransitionRun_Call{Call: _e.mock.On("TransitionRun", ctx, runID, from, to, startedAt, endedAt, updatedAt)}
}

func (_c *MockGameRepositoryInterface_TransitionRun_Call) Run(run func(ctx context.Context, runID string, from entities.RunStatus, to entities.RunStatus, startedAt *time.Time, endedAt *time.Time, updatedAt time.Time)) *MockGameRepositoryInterface_TransitionRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entities.RunStatus
		if args[2] != nil {
			arg2 = args[2].(entities.RunStatus)
		}
		var arg3 entities.RunStatus
		if args[3] != nil {
			arg3 = args[3].(entities.RunStatus)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		var arg5 *time.Time
		if args[5] != nil {
			arg5 = args[5].(*time.Time)
		}
		var arg6 time.Time
		if args[6] != nil {
			arg6 = args[6].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockGameRepositoryInterface_TransitionRun_Call) Return(err error) *MockGameRepositoryInterface_TransitionRun_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGameRepositoryInterface_TransitionRun_Call) RunAndReturn(run func(ctx context.Context, runID string, from entities.RunStatus, to entities.RunStatus, startedAt *time.Time, endedAt *time.Time, updatedAt time.Time) error) *MockGameRepositoryInterface_TransitionRun_Call {
	_c.Call.Return(run)
	return _c
}
