// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnjtechteam/dnj-game-api/internal/app/messages"
	"github.com/dnjtechteam/dnj-game-api/internal/domain/groupmembership/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGroupMembershipRepositoryInterface creates a new instance of MockGroupMembershipRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupMembershipRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupMembershipRepositoryInterface {
	mock := &MockGroupMembershipRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupMembershipRepositoryInterface is an autogenerated mock type for the GroupMembershipRepositoryInterface type
type MockGroupMembershipRepositoryInterface struct {
	mock.Mock
}

type MockGroupMembershipRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupMembershipRepositoryInterface) EXPECT() *MockGroupMembershipRepositoryInterface_Expecter {
	return &MockGroupMembershipRepositoryInterface_Expecter{mock: &_m.Mock}
}

// DeleteByUser provides a mock function for the type MockGroupMembershipRepositoryInterface
func (_mock *MockGroupMembershipRepositoryInterface) DeleteByUser(ctx context.Context, userID uint64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupMembershipRepositoryInterface_DeleteByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUser'
type MockGroupMembershipRepositoryInterface_DeleteByUser_Call struct {
	*mock.Call
}

// DeleteByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockGroupMembershipRepositoryInterface_Expecter) DeleteByUser(ctx interface{}, userID interface{}) *MockGroupMembershipRepositoryInterface_DeleteByUser_Call {
	return &MockGroupMembershipRepositoryInterface_DeleteByUser_Call{Call: _e.mock.On("DeleteByUser", ctx, userID)}
}

func (_c *MockGroupMembershipRepositoryInterface_DeleteByUser_Call) Run(run func(ctx context.Context, userID uint64)) *MockGroupMembershipRepositoryInterface_DeleteByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupMembershipRepositoryInterface_DeleteByUser_Call) Return(err error) *MockGroupMembershipRepositoryInterface_DeleteByUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupMembershipRepositoryInterface_DeleteByUser_Call) RunAndReturn(run func(ctx context.Context, userID uint64) error) *MockGroupMembershipRepositoryInterface_DeleteByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUser provides a mock function for the type MockGroupMembershipRepositoryInterface
func (_mock *MockGroupMembershipRepositoryInterface) FindByUser(ctx context.Context, userID uint64) (*entities.GroupMembership, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 *entities.GroupMembership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entities.GroupMembership, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entities.GroupMembership); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GroupMembership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupMembershipRepositoryInterface_FindByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUser'
type MockGroupMembershipRepositoryInterface_FindByUser_Call struct {
	*mock.Call
}

// FindByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockGroupMembershipRepositoryInterface_Expecter) FindByUser(ctx interface{}, userID interface{}) *MockGroupMembershipRepositoryInterface_FindByUser_Call {
	return &MockGroupMembershipRepositoryInterface_FindByUser_Call{Call: _e.mock.On("FindByUser", ctx, userID)}
}

func (_c *MockGroupMembershipRepositoryInterface_FindByUser_Call) Run(run func(ctx context.Context, userID uint64)) *MockGroupMembershipRepositoryInterface_FindByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupMembershipRepositoryInterface_FindByUser_Call) Return(groupMembership *entities.GroupMembership, err error) *MockGroupMembershipRepositoryInterface_FindByUser_Call {
	_c.Call.Return(groupMembership, err)
	return _c
}

func (_c *MockGroupMembershipRepositoryInterface_FindByUser_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (*entities.GroupMembership, error)) *MockGroupMembershipRepositoryInterface_FindByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function for the type MockGroupMembershipRepositoryInterface
func (_mock *MockGroupMembershipRepositoryInterface) ListMembers(ctx context.Context, groupID uint64, page uint64) (*messages.PaginatedResponse[entities.GroupMember], error) {
	ret := _mock.Called(ctx, groupID, page)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 *messages.PaginatedResponse[entities.GroupMember]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*messages.PaginatedResponse[entities.GroupMember], error)); ok {
		return returnFunc(ctx, groupID, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) *messages.PaginatedResponse[entities.GroupMember]); ok {
		r0 = returnFunc(ctx, groupID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.PaginatedResponse[entities.GroupMember])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, groupID, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupMembershipRepositoryInterface_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockGroupMembershipRepositoryInterface_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint64
//   - page uint64
func (_e *MockGroupMembershipRepositoryInterface_Expecter) ListMembers(ctx interface{}, groupID interface{}, page interface{}) *MockGroupMembershipRepositoryInterface_ListMembers_Call {
	return &MockGroupMembershipRepositoryInterface_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, groupID, page)}
}

func (_c *MockGroupMembershipRepositoryInterface_ListMembers_Call) Run(run func(ctx context.Context, groupID uint64, page uint64)) *MockGroupMembershipRepositoryInterface_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupMembershipRepositoryInterface_ListMembers_Call) Return(paginatedResponse *messages.PaginatedResponse[entities.GroupMember], err error) *MockGroupMembershipRepositoryInterface_ListMembers_Call {
	_c.Call.Return(paginatedResponse, err)
	return _c
}

func (_c *MockGroupMembershipRepositoryInterface_ListMembers_Call) RunAndReturn(run func(ctx context.Context, groupID uint64, page uint64) (*messages.PaginatedResponse[entities.GroupMember], error)) *MockGroupMembershipRepositoryInterface_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertForUser provides a mock function for the type MockGroupMembershipRepositoryInterface
func (_mock *MockGroupMembershipRepositoryInterface) UpsertForUser(ctx context.Context, membership *entities.GroupMembership) (*entities.GroupMembership, error) {
	ret := _mock.Called(ctx, membership)

	if len(ret) == 0 {
		panic("no return value specified for UpsertForUser")
	}

	var r0 *entities.GroupMembership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.GroupMembership) (*entities.GroupMembership, error)); ok {
		return returnFunc(ctx, membership)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.GroupMembership) *entities.GroupMembership); ok {
		r0 = returnFunc(ctx, membership)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GroupMembership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.GroupMembership) error); ok {
		r1 = returnFunc(ctx, membership)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupMembershipRepositoryInterface_UpsertForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertForUser'
type MockGroupMembershipRepositoryInterface_UpsertForUser_Call struct {
	*mock.Call
}

// UpsertForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - membership *entities.GroupMembership
func (_e *MockGroupMembershipRepositoryInterface_Expecter) UpsertForUser(ctx interface{}, membership interface{}) *MockGroupMembershipRepositoryInterface_UpsertForUser_Call {
	return &MockGroupMembershipRepositoryInterface_UpsertForUser_Call{Call: _e.mock.On("UpsertForUser", ctx, membership)}
}

func (_c *MockGroupMembershipRepositoryInterface_UpsertForUser_Call) Run(run func(ctx context.Context, membership *entities.GroupMembership)) *MockGroupMembershipRepositoryInterface_UpsertForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.GroupMembership
		if args[1] != nil {
			arg1 = args[1].(*entities.GroupMembership)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupMembershipRepositoryInterface_UpsertForUser_Call) Return(groupMembership *entities.GroupMembership, err error) *MockGroupMembershipRepositoryInterface_UpsertForUser_Call {
	_c.Call.Return(groupMembership, err)
	return _c
}

func (_c *MockGroupMembershipRepositoryInterface_UpsertForUser_Call) RunAndReturn(run func(ctx context.Context, membership *entities.GroupMembership) (*entities.GroupMembership, error)) *MockGroupMembershipRepositoryInterface_UpsertForUser_Call {
	_c.Call.Return(run)
	return _c
}
