// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/dnjtechteam/dnj-game-api/internal/app/messages"
	"github.com/dnjtechteam/dnj-game-api/internal/domain/groupinvite/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGroupInviteRepositoryInterface creates a new instance of MockGroupInviteRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupInviteRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupInviteRepositoryInterface {
	mock := &MockGroupInviteRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupInviteRepositoryInterface is an autogenerated mock type for the GroupInviteRepositoryInterface type
type MockGroupInviteRepositoryInterface struct {
	mock.Mock
}

type MockGroupInviteRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupInviteRepositoryInterface) EXPECT() *MockGroupInviteRepositoryInterface_Expecter {
	return &MockGroupInviteRepositoryInterface_Expecter{mock: &_m.Mock}
}

// ConsumeAvailable provides a mock function for the type MockGroupInviteRepositoryInterface
func (_mock *MockGroupInviteRepositoryInterface) ConsumeAvailable(ctx context.Context, inviteID uint64, userID uint64, now time.Time) (bool, error) {
	ret := _mock.Called(ctx, inviteID, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeAvailable")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, time.Time) (bool, error)); ok {
		return returnFunc(ctx, inviteID, userID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, time.Time) bool); ok {
		r0 = returnFunc(ctx, inviteID, userID, now)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, time.Time) error); ok {
		r1 = returnFunc(ctx, inviteID, userID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupInviteRepositoryInterface_ConsumeAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeAvailable'
type MockGroupInviteRepositoryInterface_ConsumeAvailable_Call struct {
	*mock.Call
}

// ConsumeAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - inviteID uint64
//   - userID uint64
//   - now time.Time
func (_e *MockGroupInviteRepositoryInterface_Expecter) ConsumeAvailable(ctx interface{}, inviteID interface{}, userID interface{}, now interface{}) *MockGroupInviteRepositoryInterface_ConsumeAvailable_Call {
	return &MockGroupInviteRepositoryInterface_ConsumeAvailable_Call{Call: _e.mock.On("ConsumeAvailable", ctx, inviteID, userID, now)}
}

func (_c *MockGroupInviteRepositoryInterface_ConsumeAvailable_Call) Run(run func(ctx context.Context, inviteID uint64, userID uint64, now time.Time)) *MockGroupInviteRepositoryInterface_ConsumeAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_ConsumeAvailable_Call) Return(b bool, err error) *MockGroupInviteRepositoryInterface_ConsumeAvailable_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_ConsumeAvailable_Call) RunAndReturn(run func(ctx context.Context, inviteID uint64, userID uint64, now time.Time) (bool, error)) *MockGroupInviteRepositoryInterface_ConsumeAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockGroupInviteRepositoryInterface
func (_mock *MockGroupInviteRepositoryInterface) Create(ctx context.Context, invite *entities.GroupInvite) (*entities.GroupInvite, error) {
	ret := _mock.Called(ctx, invite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.GroupInvite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.GroupInvite) (*entities.GroupInvite, error)); ok {
		return returnFunc(ctx, invite)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.GroupInvite) *entities.GroupInvite); ok {
		r0 = returnFunc(ctx, invite)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GroupInvite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.GroupInvite) error); ok {
		r1 = returnFunc(ctx, invite)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupInviteRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupInviteRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - invite *entities.GroupInvite
func (_e *MockGroupInviteRepositoryInterface_Expecter) Create(ctx interface{}, invite interface{}) *MockGroupInviteRepositoryInterface_Create_Call {
	return &MockGroupInviteRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, invite)}
}

func (_c *MockGroupInviteRepositoryInterface_Create_Call) Run(run func(ctx context.Context, invite *entities.GroupInvite)) *MockGroupInviteRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.GroupInvite
		if args[1] != nil {
			arg1 = args[1].(*entities.GroupInvite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_Create_Call) Return(groupInvite *entities.GroupInvite, err error) *MockGroupInviteRepositoryInterface_Create_Call {
	_c.Call.Return(groupInvite, err)
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, invite *entities.GroupInvite) (*entities.GroupInvite, error)) *MockGroupInviteRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHash provides a mock function for the type MockGroupInviteRepositoryInterface
func (_mock *MockGroupInviteRepositoryInterface) FindByHash(ctx context.Context, codeHash string) (*entities.GroupInvite, error) {
	ret := _mock.Called(ctx, codeHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *entities.GroupInvite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.GroupInvite, error)); ok {
		return returnFunc(ctx, codeHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.GroupInvite); ok {
		r0 = returnFunc(ctx, codeHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GroupInvite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, codeHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupInviteRepositoryInterface_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type MockGroupInviteRepositoryInterface_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - codeHash string
func (_e *MockGroupInviteRepositoryInterface_Expecter) FindByHash(ctx interface{}, codeHash interface{}) *MockGroupInviteRepositoryInterface_FindByHash_Call {
	return &MockGroupInviteRepositoryInterface_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, codeHash)}
}

func (_c *MockGroupInviteRepositoryInterface_FindByHash_Call) Run(run func(ctx context.Context, codeHash string)) *MockGroupInviteRepositoryInterface_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_FindByHash_Call) Return(groupInvite *entities.GroupInvite, err error) *MockGroupInviteRepositoryInterface_FindByHash_Call {
	_c.Call.Return(groupInvite, err)
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_FindByHash_Call) RunAndReturn(run func(ctx context.Context, codeHash string) (*entities.GroupInvite, error)) *MockGroupInviteRepositoryInterface_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDAndGroup provides a mock function for the type MockGroupInviteRepositoryInterface
func (_mock *MockGroupInviteRepositoryInterface) FindByIDAndGroup(ctx context.Context, inviteID uint64, groupID uint64) (*entities.GroupInvite, error) {
	ret := _mock.Called(ctx, inviteID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDAndGroup")
	}

	var r0 *entities.GroupInvite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*entities.GroupInvite, error)); ok {
		return returnFunc(ctx, inviteID, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) *entities.GroupInvite); ok {
		r0 = returnFunc(ctx, inviteID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GroupInvite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, inviteID, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDAndGroup'
type MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call struct {
	*mock.Call
}

// FindByIDAndGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - inviteID uint64
//   - groupID uint64
func (_e *MockGroupInviteRepositoryInterface_Expecter) FindByIDAndGroup(ctx interface{}, inviteID interface{}, groupID interface{}) *MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call {
	return &MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call{Call: _e.mock.On("FindByIDAndGroup", ctx, inviteID, groupID)}
}

func (_c *MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call) Run(run func(ctx context.Context, inviteID uint64, groupID uint64)) *MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call) Return(groupInvite *entities.GroupInvite, err error) *MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call {
	_c.Call.Return(groupInvite, err)
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call) RunAndReturn(run func(ctx context.Context, inviteID uint64, groupID uint64) (*entities.GroupInvite, error)) *MockGroupInviteRepositoryInterface_FindByIDAndGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ListByGroup provides a mock function for the type MockGroupInviteRepositoryInterface
func (_mock *MockGroupInviteRepositoryInterface) ListByGroup(ctx context.Context, groupID uint64, page uint64) (*messages.PaginatedResponse[entities.GroupInvite], error) {
	ret := _mock.Called(ctx, groupID, page)

	if len(ret) == 0 {
		panic("no return value specified for ListByGroup")
	}

	var r0 *messages.PaginatedResponse[entities.GroupInvite]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*messages.PaginatedResponse[entities.GroupInvite], error)); ok {
		return returnFunc(ctx, groupID, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) *messages.PaginatedResponse[entities.GroupInvite]); ok {
		r0 = returnFunc(ctx, groupID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.PaginatedResponse[entities.GroupInvite])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, groupID, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupInviteRepositoryInterface_ListByGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByGroup'
type MockGroupInviteRepositoryInterface_ListByGroup_Call struct {
	*mock.Call
}

// ListByGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint64
//   - page uint64
func (_e *MockGroupInviteRepositoryInterface_Expecter) ListByGroup(ctx interface{}, groupID interface{}, page interface{}) *MockGroupInviteRepositoryInterface_ListByGroup_Call {
	return &MockGroupInviteRepositoryInterface_ListByGroup_Call{Call: _e.mock.On("ListByGroup", ctx, groupID, page)}
}

func (_c *MockGroupInviteRepositoryInterface_ListByGroup_Call) Run(run func(ctx context.Context, groupID uint64, page uint64)) *MockGroupInviteRepositoryInterface_ListByGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_ListByGroup_Call) Return(paginatedResponse *messages.PaginatedResponse[entities.GroupInvite], err error) *MockGroupInviteRepositoryInterface_ListByGroup_Call {
	_c.Call.Return(paginatedResponse, err)
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_ListByGroup_Call) RunAndReturn(run func(ctx context.Context, groupID uint64, page uint64) (*messages.PaginatedResponse[entities.GroupInvite], error)) *MockGroupInviteRepositoryInterface_ListByGroup_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAvailable provides a mock function for the type MockGroupInviteRepositoryInterface
func (_mock *MockGroupInviteRepositoryInterface) RevokeAvailable(ctx context.Context, inviteID uint64, groupID uint64, now time.Time) (bool, error) {
	ret := _mock.Called(ctx, inviteID, groupID, now)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAvailable")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, time.Time) (bool, error)); ok {
		return returnFunc(ctx, inviteID, groupID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, time.Time) bool); ok {
		r0 = returnFunc(ctx, inviteID, groupID, now)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, time.Time) error); ok {
		r1 = returnFunc(ctx, inviteID, groupID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupInviteRepositoryInterface_RevokeAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAvailable'
type MockGroupInviteRepositoryInterface_RevokeAvailable_Call struct {
	*mock.Call
}

// RevokeAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - inviteID uint64
//   - groupID uint64
//   - now time.Time
func (_e *MockGroupInviteRepositoryInterface_Expecter) RevokeAvailable(ctx interface{}, inviteID interface{}, groupID interface{}, now interface{}) *MockGroupInviteRepositoryInterface_RevokeAvailable_Call {
	return &MockGroupInviteRepositoryInterface_RevokeAvailable_Call{Call: _e.mock.On("RevokeAvailable", ctx, inviteID, groupID, now)}
}

func (_c *MockGroupInviteRepositoryInterface_RevokeAvailable_Call) Run(run func(ctx context.Context, inviteID uint64, groupID uint64, now time.Time)) *MockGroupInviteRepositoryInterface_RevokeAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_RevokeAvailable_Call) Return(b bool, err error) *MockGroupInviteRepositoryInterface_RevokeAvailable_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGroupInviteRepositoryInterface_RevokeAvailable_Call) RunAndReturn(run func(ctx context.Context, inviteID uint64, groupID uint64, now time.Time) (bool, error)) *MockGroupInviteRepositoryInterface_RevokeAvailable_Call {
	_c.Call.Return(run)
	return _c
}
