// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnjtechteam/dnj-game-api/internal/domain/group/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGroupRepositoryInterface creates a new instance of MockGroupRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupRepositoryInterface {
	mock := &MockGroupRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupRepositoryInterface is an autogenerated mock type for the GroupRepositoryInterface type
type MockGroupRepositoryInterface struct {
	mock.Mock
}

type MockGroupRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupRepositoryInterface) EXPECT() *MockGroupRepositoryInterface_Expecter {
	return &MockGroupRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockGroupRepositoryInterface
func (_mock *MockGroupRepositoryInterface) Create(ctx context.Context, group *entities.Group) (*entities.Group, error) {
	ret := _mock.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Group) (*entities.Group, error)); ok {
		return returnFunc(ctx, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Group) *entities.Group); ok {
		r0 = returnFunc(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Group) error); ok {
		r1 = returnFunc(ctx, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - group *entities.Group
func (_e *MockGroupRepositoryInterface_Expecter) Create(ctx interface{}, group interface{}) *MockGroupRepositoryInterface_Create_Call {
	return &MockGroupRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, group)}
}

func (_c *MockGroupRepositoryInterface_Create_Call) Run(run func(ctx context.Context, group *entities.Group)) *MockGroupRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Group
		if args[1] != nil {
			arg1 = args[1].(*entities.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepositoryInterface_Create_Call) Return(group1 *entities.Group, err error) *MockGroupRepositoryInterface_Create_Call {
	_c.Call.Return(group1, err)
	return _c
}

func (_c *MockGroupRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, group *entities.Group) (*entities.Group, error)) *MockGroupRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByID provides a mock function for the type MockGroupRepositoryInterface
func (_mock *MockGroupRepositoryInterface) ExistsByID(ctx context.Context, id uint64) bool {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByID")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGroupRepositoryInterface_ExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByID'
type MockGroupRepositoryInterface_ExistsByID_Call struct {
	*mock.Call
}

// ExistsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockGroupRepositoryInterface_Expecter) ExistsByID(ctx interface{}, id interface{}) *MockGroupRepositoryInterface_ExistsByID_Call {
	return &MockGroupRepositoryInterface_ExistsByID_Call{Call: _e.mock.On("ExistsByID", ctx, id)}
}

func (_c *MockGroupRepositoryInterface_ExistsByID_Call) Run(run func(ctx context.Context, id uint64)) *MockGroupRepositoryInterface_ExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepositoryInterface_ExistsByID_Call) Return(b bool) *MockGroupRepositoryInterface_ExistsByID_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGroupRepositoryInterface_ExistsByID_Call) RunAndReturn(run func(ctx context.Context, id uint64) bool) *MockGroupRepositoryInterface_ExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockGroupRepositoryInterface
func (_mock *MockGroupRepositoryInterface) FindByID(ctx context.Context, id uint64) (*entities.Group, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entities.Group, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entities.Group); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockGroupRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockGroupRepositoryInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockGroupRepositoryInterface_FindByID_Call {
	return &MockGroupRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockGroupRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockGroupRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepositoryInterface_FindByID_Call) Return(group *entities.Group, err error) *MockGroupRepositoryInterface_FindByID_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupRepositoryInterface_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint64) (*entities.Group, error)) *MockGroupRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNameExact provides a mock function for the type MockGroupRepositoryInterface
func (_mock *MockGroupRepositoryInterface) FindByNameExact(ctx context.Context, name string) (*entities.Group, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByNameExact")
	}

	var r0 *entities.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Group, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Group); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepositoryInterface_FindByNameExact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNameExact'
type MockGroupRepositoryInterface_FindByNameExact_Call struct {
	*mock.Call
}

// FindByNameExact is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockGroupRepositoryInterface_Expecter) FindByNameExact(ctx interface{}, name interface{}) *MockGroupRepositoryInterface_FindByNameExact_Call {
	return &MockGroupRepositoryInterface_FindByNameExact_Call{Call: _e.mock.On("FindByNameExact", ctx, name)}
}

func (_c *MockGroupRepositoryInterface_FindByNameExact_Call) Run(run func(ctx context.Context, name string)) *MockGroupRepositoryInterface_FindByNameExact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepositoryInterface_FindByNameExact_Call) Return(group *entities.Group, err error) *MockGroupRepositoryInterface_FindByNameExact_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupRepositoryInterface_FindByNameExact_Call) RunAndReturn(run func(ctx context.Context, name string) (*entities.Group, error)) *MockGroupRepositoryInterface_FindByNameExact_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockGroupRepositoryInterface
func (_mock *MockGroupRepositoryInterface) Search(ctx context.Context, query string, limit int) ([]*entities.Group, error) {
	ret := _mock.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*entities.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]*entities.Group, error)); ok {
		return returnFunc(ctx, query, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []*entities.Group); ok {
		r0 = returnFunc(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepositoryInterface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockGroupRepositoryInterface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
func (_e *MockGroupRepositoryInterface_Expecter) Search(ctx interface{}, query interface{}, limit interface{}) *MockGroupRepositoryInterface_Search_Call {
	return &MockGroupRepositoryInterface_Search_Call{Call: _e.mock.On("Search", ctx, query, limit)}
}

func (_c *MockGroupRepositoryInterface_Search_Call) Run(run func(ctx context.Context, query string, limit int)) *MockGroupRepositoryInterface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupRepositoryInterface_Search_Call) Return(groups []*entities.Group, err error) *MockGroupRepositoryInterface_Search_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupRepositoryInterface_Search_Call) RunAndReturn(run func(ctx context.Context, query string, limit int) ([]*entities.Group, error)) *MockGroupRepositoryInterface_Search_Call {
	_c.Call.Return(run)
	return _c
}
