// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnjtechteam/dnj-game-api/internal/domain/identity/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGoogleIdentityRepositoryInterface creates a new instance of MockGoogleIdentityRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoogleIdentityRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoogleIdentityRepositoryInterface {
	mock := &MockGoogleIdentityRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGoogleIdentityRepositoryInterface is an autogenerated mock type for the GoogleIdentityRepositoryInterface type
type MockGoogleIdentityRepositoryInterface struct {
	mock.Mock
}

type MockGoogleIdentityRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoogleIdentityRepositoryInterface) EXPECT() *MockGoogleIdentityRepositoryInterface_Expecter {
	return &MockGoogleIdentityRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockGoogleIdentityRepositoryInterface
func (_mock *MockGoogleIdentityRepositoryInterface) Create(ctx context.Context, identity *entities.GoogleIdentity) (*entities.GoogleIdentity, error) {
	ret := _mock.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.GoogleIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.GoogleIdentity) (*entities.GoogleIdentity, error)); ok {
		return returnFunc(ctx, identity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.GoogleIdentity) *entities.GoogleIdentity); ok {
		r0 = returnFunc(ctx, identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GoogleIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.GoogleIdentity) error); ok {
		r1 = returnFunc(ctx, identity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoogleIdentityRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGoogleIdentityRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *entities.GoogleIdentity
func (_e *MockGoogleIdentityRepositoryInterface_Expecter) Create(ctx interface{}, identity interface{}) *MockGoogleIdentityRepositoryInterface_Create_Call {
	return &MockGoogleIdentityRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, identity)}
}

func (_c *MockGoogleIdentityRepositoryInterface_Create_Call) Run(run func(ctx context.Context, identity *entities.GoogleIdentity)) *MockGoogleIdentityRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.GoogleIdentity
		if args[1] != nil {
			arg1 = args[1].(*entities.GoogleIdentity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGoogleIdentityRepositoryInterface_Create_Call) Return(googleIdentity *entities.GoogleIdentity, err error) *MockGoogleIdentityRepositoryInterface_Create_Call {
	_c.Call.Return(googleIdentity, err)
	return _c
}

func (_c *MockGoogleIdentityRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, identity *entities.GoogleIdentity) (*entities.GoogleIdentity, error)) *MockGoogleIdentityRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProviderAndSubject provides a mock function for the type MockGoogleIdentityRepositoryInterface
func (_mock *MockGoogleIdentityRepositoryInterface) FindByProviderAndSubject(ctx context.Context, provider string, subject string) (*entities.GoogleIdentity, error) {
	ret := _mock.Called(ctx, provider, subject)

	if len(ret) == 0 {
		panic("no return value specified for FindByProviderAndSubject")
	}

	var r0 *entities.GoogleIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entities.GoogleIdentity, error)); ok {
		return returnFunc(ctx, provider, subject)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entities.GoogleIdentity); ok {
		r0 = returnFunc(ctx, provider, subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GoogleIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, subject)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProviderAndSubject'
type MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call struct {
	*mock.Call
}

// FindByProviderAndSubject is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - subject string
func (_e *MockGoogleIdentityRepositoryInterface_Expecter) FindByProviderAndSubject(ctx interface{}, provider interface{}, subject interface{}) *MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call {
	return &MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call{Call: _e.mock.On("FindByProviderAndSubject", ctx, provider, subject)}
}

func (_c *MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call) Run(run func(ctx context.Context, provider string, subject string)) *MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call) Return(googleIdentity *entities.GoogleIdentity, err error) *MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call {
	_c.Call.Return(googleIdentity, err)
	return _c
}

func (_c *MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call) RunAndReturn(run func(ctx context.Context, provider string, subject string) (*entities.GoogleIdentity, error)) *MockGoogleIdentityRepositoryInterface_FindByProviderAndSubject_Call {
	_c.Call.Return(run)
	return _c
}
