// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/dnjtechteam/dnj-game-api/internal/domain/media/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMediaRepository creates a new instance of MockMediaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaRepository {
	mock := &MockMediaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMediaRepository is an autogenerated mock type for the Repository type
type MockMediaRepository struct {
	mock.Mock
}

type MockMediaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaRepository) EXPECT() *MockMediaRepository_Expecter {
	return &MockMediaRepository_Expecter{mock: &_m.Mock}
}

// AcquireProcessingClaim provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) AcquireProcessingClaim(context1 context.Context, s string, s1 string, s2 string, time1 time.Time, time11 time.Time) (*entities.ProcessingClaim, bool, error) {
	ret := _mock.Called(context1, s, s1, s2, time1, time11)

	if len(ret) == 0 {
		panic("no return value specified for AcquireProcessingClaim")
	}

	var r0 *entities.ProcessingClaim
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) (*entities.ProcessingClaim, bool, error)); ok {
		return returnFunc(context1, s, s1, s2, time1, time11)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) *entities.ProcessingClaim); ok {
		r0 = returnFunc(context1, s, s1, s2, time1, time11)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ProcessingClaim)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, time.Time, time.Time) bool); ok {
		r1 = returnFunc(context1, s, s1, s2, time1, time11)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, time.Time, time.Time) error); ok {
		r2 = returnFunc(context1, s, s1, s2, time1, time11)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMediaRepository_AcquireProcessingClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireProcessingClaim'
type MockMediaRepository_AcquireProcessingClaim_Call struct {
	*mock.Call
}

// AcquireProcessingClaim is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - time1 time.Time
//   - time11 time.Time
func (_e *MockMediaRepository_Expecter) AcquireProcessingClaim(context1 interface{}, s interface{}, s1 interface{}, s2 interface{}, time1 interface{}, time11 interface{}) *MockMediaRepository_AcquireProcessingClaim_Call {
	return &MockMediaRepository_AcquireProcessingClaim_Call{Call: _e.mock.On("AcquireProcessingClaim", context1, s, s1, s2, time1, time11)}
}

func (_c *MockMediaRepository_AcquireProcessingClaim_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, time1 time.Time, time11 time.Time)) *MockMediaRepository_AcquireProcessingClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMediaRepository_AcquireProcessingClaim_Call) Return(processingClaim *entities.ProcessingClaim, b bool, err error) *MockMediaRepository_AcquireProcessingClaim_Call {
	_c.Call.Return(processingClaim, b, err)
	return _c
}

func (_c *MockMediaRepository_AcquireProcessingClaim_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, time1 time.Time, time11 time.Time) (*entities.ProcessingClaim, bool, error)) *MockMediaRepository_AcquireProcessingClaim_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimCleanupJobs provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) ClaimCleanupJobs(context1 context.Context, time1 time.Time, duration time.Duration, n int) ([]entities.CleanupJob, error) {
	ret := _mock.Called(context1, time1, duration, n)

	if len(ret) == 0 {
		panic("no return value specified for ClaimCleanupJobs")
	}

	var r0 []entities.CleanupJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Duration, int) ([]entities.CleanupJob, error)); ok {
		return returnFunc(context1, time1, duration, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Duration, int) []entities.CleanupJob); ok {
		r0 = returnFunc(context1, time1, duration, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.CleanupJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Duration, int) error); ok {
		r1 = returnFunc(context1, time1, duration, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaRepository_ClaimCleanupJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimCleanupJobs'
type MockMediaRepository_ClaimCleanupJobs_Call struct {
	*mock.Call
}

// ClaimCleanupJobs is a helper method to define mock.On call
//   - context1 context.Context
//   - time1 time.Time
//   - duration time.Duration
//   - n int
func (_e *MockMediaRepository_Expecter) ClaimCleanupJobs(context1 interface{}, time1 interface{}, duration interface{}, n interface{}) *MockMediaRepository_ClaimCleanupJobs_Call {
	return &MockMediaRepository_ClaimCleanupJobs_Call{Call: _e.mock.On("ClaimCleanupJobs", context1, time1, duration, n)}
}

func (_c *MockMediaRepository_ClaimCleanupJobs_Call) Run(run func(context1 context.Context, time1 time.Time, duration time.Duration, n int)) *MockMediaRepository_ClaimCleanupJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMediaRepository_ClaimCleanupJobs_Call) Return(cleanupJobs []entities.CleanupJob, err error) *MockMediaRepository_ClaimCleanupJobs_Call {
	_c.Call.Return(cleanupJobs, err)
	return _c
}

func (_c *MockMediaRepository_ClaimCleanupJobs_Call) RunAndReturn(run func(context1 context.Context, time1 time.Time, duration time.Duration, n int) ([]entities.CleanupJob, error)) *MockMediaRepository_ClaimCleanupJobs_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteCleanupJob provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) CompleteCleanupJob(context1 context.Context, s string, s1 string, time1 time.Time) error {
	ret := _mock.Called(context1, s, s1, time1)

	if len(ret) == 0 {
		panic("no return value specified for CompleteCleanupJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = returnFunc(context1, s, s1, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaRepository_CompleteCleanupJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteCleanupJob'
type MockMediaRepository_CompleteCleanupJob_Call struct {
	*mock.Call
}

// CompleteCleanupJob is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - time1 time.Time
func (_e *MockMediaRepository_Expecter) CompleteCleanupJob(context1 interface{}, s interface{}, s1 interface{}, time1 interface{}) *MockMediaRepository_CompleteCleanupJob_Call {
	return &MockMediaRepository_CompleteCleanupJob_Call{Call: _e.mock.On("CompleteCleanupJob", context1, s, s1, time1)}
}

func (_c *MockMediaRepository_CompleteCleanupJob_Call) Run(run func(context1 context.Context, s string, s1 string, time1 time.Time)) *MockMediaRepository_CompleteCleanupJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMediaRepository_CompleteCleanupJob_Call) Return(err error) *MockMediaRepository_CompleteCleanupJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaRepository_CompleteCleanupJob_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, time1 time.Time) error) *MockMediaRepository_CompleteCleanupJob_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteOperation provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) CompleteOperation(context1 context.Context, s string, n int, s1 *string, b *bool, n1 *int, bytes []byte, time1 time.Time) error {
	ret := _mock.Called(context1, s, n, s1, b, n1, bytes, time1)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *string, *bool, *int, []byte, time.Time) error); ok {
		r0 = returnFunc(context1, s, n, s1, b, n1, bytes, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaRepository_CompleteOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOperation'
type MockMediaRepository_CompleteOperation_Call struct {
	*mock.Call
}

// CompleteOperation is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - n int
//   - s1 *string
//   - b *bool
//   - n1 *int
//   - bytes []byte
//   - time1 time.Time
func (_e *MockMediaRepository_Expecter) CompleteOperation(context1 interface{}, s interface{}, n interface{}, s1 interface{}, b interface{}, n1 interface{}, bytes interface{}, time1 interface{}) *MockMediaRepository_CompleteOperation_Call {
	return &MockMediaRepository_CompleteOperation_Call{Call: _e.mock.On("CompleteOperation", context1, s, n, s1, b, n1, bytes, time1)}
}

func (_c *MockMediaRepository_CompleteOperation_Call) Run(run func(context1 context.Context, s string, n int, s1 *string, b *bool, n1 *int, bytes []byte, time1 time.Time)) *MockMediaRepository_CompleteOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *bool
		if args[4] != nil {
			arg4 = args[4].(*bool)
		}
		var arg5 *int
		if args[5] != nil {
			arg5 = args[5].(*int)
		}
		var arg6 []byte
		if args[6] != nil {
			arg6 = args[6].([]byte)
		}
		var arg7 time.Time
		if args[7] != nil {
			arg7 = args[7].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockMediaRepository_CompleteOperation_Call) Return(err error) *MockMediaRepository_CompleteOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaRepository_CompleteOperation_Call) RunAndReturn(run func(context1 context.Context, s string, n int, s1 *string, b *bool, n1 *int, bytes []byte, time1 time.Time) error) *MockMediaRepository_CompleteOperation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAsset provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) CreateAsset(context1 context.Context, asset *entities.Asset) error {
	ret := _mock.Called(context1, asset)

	if len(ret) == 0 {
		panic("no return value specified for CreateAsset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset) error); ok {
		r0 = returnFunc(context1, asset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaRepository_CreateAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAsset'
type MockMediaRepository_CreateAsset_Call struct {
	*mock.Call
}

// CreateAsset is a helper method to define mock.On call
//   - context1 context.Context
//   - asset *entities.Asset
func (_e *MockMediaRepository_Expecter) CreateAsset(context1 interface{}, asset interface{}) *MockMediaRepository_CreateAsset_Call {
	return &MockMediaRepository_CreateAsset_Call{Call: _e.mock.On("CreateAsset", context1, asset)}
}

func (_c *MockMediaRepository_CreateAsset_Call) Run(run func(context1 context.Context, asset *entities.Asset)) *MockMediaRepository_CreateAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Asset
		if args[1] != nil {
			arg1 = args[1].(*entities.Asset)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaRepository_CreateAsset_Call) Return(err error) *MockMediaRepository_CreateAsset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaRepository_CreateAsset_Call) RunAndReturn(run func(context1 context.Context, asset *entities.Asset) error) *MockMediaRepository_CreateAsset_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCleanupJob provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) CreateCleanupJob(context1 context.Context, cleanupJob *entities.CleanupJob) (bool, error) {
	ret := _mock.Called(context1, cleanupJob)

	if len(ret) == 0 {
		panic("no return value specified for CreateCleanupJob")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.CleanupJob) (bool, error)); ok {
		return returnFunc(context1, cleanupJob)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.CleanupJob) bool); ok {
		r0 = returnFunc(context1, cleanupJob)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.CleanupJob) error); ok {
		r1 = returnFunc(context1, cleanupJob)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaRepository_CreateCleanupJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCleanupJob'
type MockMediaRepository_CreateCleanupJob_Call struct {
	*mock.Call
}

// CreateCleanupJob is a helper method to define mock.On call
//   - context1 context.Context
//   - cleanupJob *entities.CleanupJob
func (_e *MockMediaRepository_Expecter) CreateCleanupJob(context1 interface{}, cleanupJob interface{}) *MockMediaRepository_CreateCleanupJob_Call {
	return &MockMediaRepository_CreateCleanupJob_Call{Call: _e.mock.On("CreateCleanupJob", context1, cleanupJob)}
}

func (_c *MockMediaRepository_CreateCleanupJob_Call) Run(run func(context1 context.Context, cleanupJob *entities.CleanupJob)) *MockMediaRepository_CreateCleanupJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.CleanupJob
		if args[1] != nil {
			arg1 = args[1].(*entities.CleanupJob)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaRepository_CreateCleanupJob_Call) Return(b bool, err error) *MockMediaRepository_CreateCleanupJob_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockMediaRepository_CreateCleanupJob_Call) RunAndReturn(run func(context1 context.Context, cleanupJob *entities.CleanupJob) (bool, error)) *MockMediaRepository_CreateCleanupJob_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOperation provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) CreateOperation(context1 context.Context, operation *entities.Operation) error {
	ret := _mock.Called(context1, operation)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Operation) error); ok {
		r0 = returnFunc(context1, operation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaRepository_CreateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOperation'
type MockMediaRepository_CreateOperation_Call struct {
	*mock.Call
}

// CreateOperation is a helper method to define mock.On call
//   - context1 context.Context
//   - operation *entities.Operation
func (_e *MockMediaRepository_Expecter) CreateOperation(context1 interface{}, operation interface{}) *MockMediaRepository_CreateOperation_Call {
	return &MockMediaRepository_CreateOperation_Call{Call: _e.mock.On("CreateOperation", context1, operation)}
}

func (_c *MockMediaRepository_CreateOperation_Call) Run(run func(context1 context.Context, operation *entities.Operation)) *MockMediaRepository_CreateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Operation
		if args[1] != nil {
			arg1 = args[1].(*entities.Operation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaRepository_CreateOperation_Call) Return(err error) *MockMediaRepository_CreateOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaRepository_CreateOperation_Call) RunAndReturn(run func(context1 context.Context, operation *entities.Operation) error) *MockMediaRepository_CreateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// ExpirePendingAssets provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) ExpirePendingAssets(context1 context.Context, time1 time.Time, n int) ([]entities.Asset, error) {
	ret := _mock.Called(context1, time1, n)

	if len(ret) == 0 {
		panic("no return value specified for ExpirePendingAssets")
	}

	var r0 []entities.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]entities.Asset, error)); ok {
		return returnFunc(context1, time1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) []entities.Asset); ok {
		r0 = returnFunc(context1, time1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(context1, time1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaRepository_ExpirePendingAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpirePendingAssets'
type MockMediaRepository_ExpirePendingAssets_Call struct {
	*mock.Call
}

// ExpirePendingAssets is a helper method to define mock.On call
//   - context1 context.Context
//   - time1 time.Time
//   - n int
func (_e *MockMediaRepository_Expecter) ExpirePendingAssets(context1 interface{}, time1 interface{}, n interface{}) *MockMediaRepository_ExpirePendingAssets_Call {
	return &MockMediaRepository_ExpirePendingAssets_Call{Call: _e.mock.On("ExpirePendingAssets", context1, time1, n)}
}

func (_c *MockMediaRepository_ExpirePendingAssets_Call) Run(run func(context1 context.Context, time1 time.Time, n int)) *MockMediaRepository_ExpirePendingAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMediaRepository_ExpirePendingAssets_Call) Return(assets []entities.Asset, err error) *MockMediaRepository_ExpirePendingAssets_Call {
	_c.Call.Return(assets, err)
	return _c
}

func (_c *MockMediaRepository_ExpirePendingAssets_Call) RunAndReturn(run func(context1 context.Context, time1 time.Time, n int) ([]entities.Asset, error)) *MockMediaRepository_ExpirePendingAssets_Call {
	_c.Call.Return(run)
	return _c
}

// FindAsset provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) FindAsset(context1 context.Context, s string, b bool) (*entities.Asset, error) {
	ret := _mock.Called(context1, s, b)

	if len(ret) == 0 {
		panic("no return value specified for FindAsset")
	}

	var r0 *entities.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*entities.Asset, error)); ok {
		return returnFunc(context1, s, b)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *entities.Asset); ok {
		r0 = returnFunc(context1, s, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(context1, s, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaRepository_FindAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAsset'
type MockMediaRepository_FindAsset_Call struct {
	*mock.Call
}

// FindAsset is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - b bool
func (_e *MockMediaRepository_Expecter) FindAsset(context1 interface{}, s interface{}, b interface{}) *MockMediaRepository_FindAsset_Call {
	return &MockMediaRepository_FindAsset_Call{Call: _e.mock.On("FindAsset", context1, s, b)}
}

func (_c *MockMediaRepository_FindAsset_Call) Run(run func(context1 context.Context, s string, b bool)) *MockMediaRepository_FindAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMediaRepository_FindAsset_Call) Return(asset *entities.Asset, err error) *MockMediaRepository_FindAsset_Call {
	_c.Call.Return(asset, err)
	return _c
}

func (_c *MockMediaRepository_FindAsset_Call) RunAndReturn(run func(context1 context.Context, s string, b bool) (*entities.Asset, error)) *MockMediaRepository_FindAsset_Call {
	_c.Call.Return(run)
	return _c
}

// FindLegacyOperation provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) FindLegacyOperation(context1 context.Context, v uint64, s string) (bool, error) {
	ret := _mock.Called(context1, v, s)

	if len(ret) == 0 {
		panic("no return value specified for FindLegacyOperation")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (bool, error)); ok {
		return returnFunc(context1, v, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) bool); ok {
		r0 = returnFunc(context1, v, s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(context1, v, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaRepository_FindLegacyOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLegacyOperation'
type MockMediaRepository_FindLegacyOperation_Call struct {
	*mock.Call
}

// FindLegacyOperation is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint64
//   - s string
func (_e *MockMediaRepository_Expecter) FindLegacyOperation(context1 interface{}, v interface{}, s interface{}) *MockMediaRepository_FindLegacyOperation_Call {
	return &MockMediaRepository_FindLegacyOperation_Call{Call: _e.mock.On("FindLegacyOperation", context1, v, s)}
}

func (_c *MockMediaRepository_FindLegacyOperation_Call) Run(run func(context1 context.Context, v uint64, s string)) *MockMediaRepository_FindLegacyOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMediaRepository_FindLegacyOperation_Call) Return(b bool, err error) *MockMediaRepository_FindLegacyOperation_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockMediaRepository_FindLegacyOperation_Call) RunAndReturn(run func(context1 context.Context, v uint64, s string) (bool, error)) *MockMediaRepository_FindLegacyOperation_Call {
	_c.Call.Return(run)
	return _c
}

// FindOperation provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) FindOperation(context1 context.Context, v uint64, s string) (*entities.Operation, error) {
	ret := _mock.Called(context1, v, s)

	if len(ret) == 0 {
		panic("no return value specified for FindOperation")
	}

	var r0 *entities.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (*entities.Operation, error)); ok {
		return returnFunc(context1, v, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) *entities.Operation); ok {
		r0 = returnFunc(context1, v, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(context1, v, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaRepository_FindOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOperation'
type MockMediaRepository_FindOperation_Call struct {
	*mock.Call
}

// FindOperation is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint64
//   - s string
func (_e *MockMediaRepository_Expecter) FindOperation(context1 interface{}, v interface{}, s interface{}) *MockMediaRepository_FindOperation_Call {
	return &MockMediaRepository_FindOperation_Call{Call: _e.mock.On("FindOperation", context1, v, s)}
}

func (_c *MockMediaRepository_FindOperation_Call) Run(run func(context1 context.Context, v uint64, s string)) *MockMediaRepository_FindOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMediaRepository_FindOperation_Call) Return(operation *entities.Operation, err error) *MockMediaRepository_FindOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockMediaRepository_FindOperation_Call) RunAndReturn(run func(context1 context.Context, v uint64, s string) (*entities.Operation, error)) *MockMediaRepository_FindOperation_Call {
	_c.Call.Return(run)
	return _c
}

// Metrics provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) Metrics(context1 context.Context, time1 time.Time) (*entities.WorkerMetrics, error) {
	ret := _mock.Called(context1, time1)

	if len(ret) == 0 {
		panic("no return value specified for Metrics")
	}

	var r0 *entities.WorkerMetrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (*entities.WorkerMetrics, error)); ok {
		return returnFunc(context1, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) *entities.WorkerMetrics); ok {
		r0 = returnFunc(context1, time1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.WorkerMetrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(context1, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaRepository_Metrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metrics'
type MockMediaRepository_Metrics_Call struct {
	*mock.Call
}

// Metrics is a helper method to define mock.On call
//   - context1 context.Context
//   - time1 time.Time
func (_e *MockMediaRepository_Expecter) Metrics(context1 interface{}, time1 interface{}) *MockMediaRepository_Metrics_Call {
	return &MockMediaRepository_Metrics_Call{Call: _e.mock.On("Metrics", context1, time1)}
}

func (_c *MockMediaRepository_Metrics_Call) Run(run func(context1 context.Context, time1 time.Time)) *MockMediaRepository_Metrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaRepository_Metrics_Call) Return(workerMetrics *entities.WorkerMetrics, err error) *MockMediaRepository_Metrics_Call {
	_c.Call.Return(workerMetrics, err)
	return _c
}

func (_c *MockMediaRepository_Metrics_Call) RunAndReturn(run func(context1 context.Context, time1 time.Time) (*entities.WorkerMetrics, error)) *MockMediaRepository_Metrics_Call {
	_c.Call.Return(run)
	return _c
}

// RetryCleanupJob provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) RetryCleanupJob(context1 context.Context, s string, s1 string, time1 time.Time, s2 string, time11 time.Time) error {
	ret := _mock.Called(context1, s, s1, time1, s2, time11)

	if len(ret) == 0 {
		panic("no return value specified for RetryCleanupJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, string, time.Time) error); ok {
		r0 = returnFunc(context1, s, s1, time1, s2, time11)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaRepository_RetryCleanupJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryCleanupJob'
type MockMediaRepository_RetryCleanupJob_Call struct {
	*mock.Call
}

// RetryCleanupJob is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - time1 time.Time
//   - s2 string
//   - time11 time.Time
func (_e *MockMediaRepository_Expecter) RetryCleanupJob(context1 interface{}, s interface{}, s1 interface{}, time1 interface{}, s2 interface{}, time11 interface{}) *MockMediaRepository_RetryCleanupJob_Call {
	return &MockMediaRepository_RetryCleanupJob_Call{Call: _e.mock.On("RetryCleanupJob", context1, s, s1, time1, s2, time11)}
}

func (_c *MockMediaRepository_RetryCleanupJob_Call) Run(run func(context1 context.Context, s string, s1 string, time1 time.Time, s2 string, time11 time.Time)) *MockMediaRepository_RetryCleanupJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMediaRepository_RetryCleanupJob_Call) Return(err error) *MockMediaRepository_RetryCleanupJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaRepository_RetryCleanupJob_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, time1 time.Time, s2 string, time11 time.Time) error) *MockMediaRepository_RetryCleanupJob_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAsset provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) UpdateAsset(context1 context.Context, asset *entities.Asset) error {
	ret := _mock.Called(context1, asset)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAsset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset) error); ok {
		r0 = returnFunc(context1, asset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaRepository_UpdateAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAsset'
type MockMediaRepository_UpdateAsset_Call struct {
	*mock.Call
}

// UpdateAsset is a helper method to define mock.On call
//   - context1 context.Context
//   - asset *entities.Asset
func (_e *MockMediaRepository_Expecter) UpdateAsset(context1 interface{}, asset interface{}) *MockMediaRepository_UpdateAsset_Call {
	return &MockMediaRepository_UpdateAsset_Call{Call: _e.mock.On("UpdateAsset", context1, asset)}
}

func (_c *MockMediaRepository_UpdateAsset_Call) Run(run func(context1 context.Context, asset *entities.Asset)) *MockMediaRepository_UpdateAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Asset
		if args[1] != nil {
			arg1 = args[1].(*entities.Asset)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaRepository_UpdateAsset_Call) Return(err error) *MockMediaRepository_UpdateAsset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaRepository_UpdateAsset_Call) RunAndReturn(run func(context1 context.Context, asset *entities.Asset) error) *MockMediaRepository_UpdateAsset_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcessingClaim provides a mock function for the type MockMediaRepository
func (_mock *MockMediaRepository) UpdateProcessingClaim(context1 context.Context, processingClaim *entities.ProcessingClaim) error {
	ret := _mock.Called(context1, processingClaim)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcessingClaim")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.ProcessingClaim) error); ok {
		r0 = returnFunc(context1, processingClaim)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaRepository_UpdateProcessingClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcessingClaim'
type MockMediaRepository_UpdateProcessingClaim_Call struct {
	*mock.Call
}

// UpdateProcessingClaim is a helper method to define mock.On call
//   - context1 context.Context
//   - processingClaim *entities.ProcessingClaim
func (_e *MockMediaRepository_Expecter) UpdateProcessingClaim(context1 interface{}, processingClaim interface{}) *MockMediaRepository_UpdateProcessingClaim_Call {
	return &MockMediaRepository_UpdateProcessingClaim_Call{Call: _e.mock.On("UpdateProcessingClaim", context1, processingClaim)}
}

func (_c *MockMediaRepository_UpdateProcessingClaim_Call) Run(run func(context1 context.Context, processingClaim *entities.ProcessingClaim)) *MockMediaRepository_UpdateProcessingClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.ProcessingClaim
		if args[1] != nil {
			arg1 = args[1].(*entities.ProcessingClaim)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaRepository_UpdateProcessingClaim_Call) Return(err error) *MockMediaRepository_UpdateProcessingClaim_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaRepository_UpdateProcessingClaim_Call) RunAndReturn(run func(context1 context.Context, processingClaim *entities.ProcessingClaim) error) *MockMediaRepository_UpdateProcessingClaim_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaStorage creates a new instance of MockMediaStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaStorage {
	mock := &MockMediaStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMediaStorage is an autogenerated mock type for the Storage type
type MockMediaStorage struct {
	mock.Mock
}

type MockMediaStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaStorage) EXPECT() *MockMediaStorage_Expecter {
	return &MockMediaStorage_Expecter{mock: &_m.Mock}
}

// DeleteObjectVersions provides a mock function for the type MockMediaStorage
func (_mock *MockMediaStorage) DeleteObjectVersions(context1 context.Context, s string, s1 string) error {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjectVersions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaStorage_DeleteObjectVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjectVersions'
type MockMediaStorage_DeleteObjectVersions_Call struct {
	*mock.Call
}

// DeleteObjectVersions is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockMediaStorage_Expecter) DeleteObjectVersions(context1 interface{}, s interface{}, s1 interface{}) *MockMediaStorage_DeleteObjectVersions_Call {
	return &MockMediaStorage_DeleteObjectVersions_Call{Call: _e.mock.On("DeleteObjectVersions", context1, s, s1)}
}

func (_c *MockMediaStorage_DeleteObjectVersions_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockMediaStorage_DeleteObjectVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMediaStorage_DeleteObjectVersions_Call) Return(err error) *MockMediaStorage_DeleteObjectVersions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaStorage_DeleteObjectVersions_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) error) *MockMediaStorage_DeleteObjectVersions_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadStaging provides a mock function for the type MockMediaStorage
func (_mock *MockMediaStorage) DownloadStaging(context1 context.Context, asset *entities.Asset, s string, n int64) (*entities.ObjectBody, error) {
	ret := _mock.Called(context1, asset, s, n)

	if len(ret) == 0 {
		panic("no return value specified for DownloadStaging")
	}

	var r0 *entities.ObjectBody
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, string, int64) (*entities.ObjectBody, error)); ok {
		return returnFunc(context1, asset, s, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, string, int64) *entities.ObjectBody); ok {
		r0 = returnFunc(context1, asset, s, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ObjectBody)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Asset, string, int64) error); ok {
		r1 = returnFunc(context1, asset, s, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaStorage_DownloadStaging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadStaging'
type MockMediaStorage_DownloadStaging_Call struct {
	*mock.Call
}

// DownloadStaging is a helper method to define mock.On call
//   - context1 context.Context
//   - asset *entities.Asset
//   - s string
//   - n int64
func (_e *MockMediaStorage_Expecter) DownloadStaging(context1 interface{}, asset interface{}, s interface{}, n interface{}) *MockMediaStorage_DownloadStaging_Call {
	return &MockMediaStorage_DownloadStaging_Call{Call: _e.mock.On("DownloadStaging", context1, asset, s, n)}
}

func (_c *MockMediaStorage_DownloadStaging_Call) Run(run func(context1 context.Context, asset *entities.Asset, s string, n int64)) *MockMediaStorage_DownloadStaging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Asset
		if args[1] != nil {
			arg1 = args[1].(*entities.Asset)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMediaStorage_DownloadStaging_Call) Return(objectBody *entities.ObjectBody, err error) *MockMediaStorage_DownloadStaging_Call {
	_c.Call.Return(objectBody, err)
	return _c
}

func (_c *MockMediaStorage_DownloadStaging_Call) RunAndReturn(run func(context1 context.Context, asset *entities.Asset, s string, n int64) (*entities.ObjectBody, error)) *MockMediaStorage_DownloadStaging_Call {
	_c.Call.Return(run)
	return _c
}

// HeadFinal provides a mock function for the type MockMediaStorage
func (_mock *MockMediaStorage) HeadFinal(context1 context.Context, asset *entities.Asset, s string) (*entities.ObjectMetadata, error) {
	ret := _mock.Called(context1, asset, s)

	if len(ret) == 0 {
		panic("no return value specified for HeadFinal")
	}

	var r0 *entities.ObjectMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, string) (*entities.ObjectMetadata, error)); ok {
		return returnFunc(context1, asset, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, string) *entities.ObjectMetadata); ok {
		r0 = returnFunc(context1, asset, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ObjectMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Asset, string) error); ok {
		r1 = returnFunc(context1, asset, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaStorage_HeadFinal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadFinal'
type MockMediaStorage_HeadFinal_Call struct {
	*mock.Call
}

// HeadFinal is a helper method to define mock.On call
//   - context1 context.Context
//   - asset *entities.Asset
//   - s string
func (_e *MockMediaStorage_Expecter) HeadFinal(context1 interface{}, asset interface{}, s interface{}) *MockMediaStorage_HeadFinal_Call {
	return &MockMediaStorage_HeadFinal_Call{Call: _e.mock.On("HeadFinal", context1, asset, s)}
}

func (_c *MockMediaStorage_HeadFinal_Call) Run(run func(context1 context.Context, asset *entities.Asset, s string)) *MockMediaStorage_HeadFinal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Asset
		if args[1] != nil {
			arg1 = args[1].(*entities.Asset)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMediaStorage_HeadFinal_Call) Return(objectMetadata *entities.ObjectMetadata, err error) *MockMediaStorage_HeadFinal_Call {
	_c.Call.Return(objectMetadata, err)
	return _c
}

func (_c *MockMediaStorage_HeadFinal_Call) RunAndReturn(run func(context1 context.Context, asset *entities.Asset, s string) (*entities.ObjectMetadata, error)) *MockMediaStorage_HeadFinal_Call {
	_c.Call.Return(run)
	return _c
}

// HeadStaging provides a mock function for the type MockMediaStorage
func (_mock *MockMediaStorage) HeadStaging(context1 context.Context, asset *entities.Asset) (*entities.ObjectMetadata, error) {
	ret := _mock.Called(context1, asset)

	if len(ret) == 0 {
		panic("no return value specified for HeadStaging")
	}

	var r0 *entities.ObjectMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset) (*entities.ObjectMetadata, error)); ok {
		return returnFunc(context1, asset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset) *entities.ObjectMetadata); ok {
		r0 = returnFunc(context1, asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ObjectMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Asset) error); ok {
		r1 = returnFunc(context1, asset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaStorage_HeadStaging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadStaging'
type MockMediaStorage_HeadStaging_Call struct {
	*mock.Call
}

// HeadStaging is a helper method to define mock.On call
//   - context1 context.Context
//   - asset *entities.Asset
func (_e *MockMediaStorage_Expecter) HeadStaging(context1 interface{}, asset interface{}) *MockMediaStorage_HeadStaging_Call {
	return &MockMediaStorage_HeadStaging_Call{Call: _e.mock.On("HeadStaging", context1, asset)}
}

func (_c *MockMediaStorage_HeadStaging_Call) Run(run func(context1 context.Context, asset *entities.Asset)) *MockMediaStorage_HeadStaging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Asset
		if args[1] != nil {
			arg1 = args[1].(*entities.Asset)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaStorage_HeadStaging_Call) Return(objectMetadata *entities.ObjectMetadata, err error) *MockMediaStorage_HeadStaging_Call {
	_c.Call.Return(objectMetadata, err)
	return _c
}

func (_c *MockMediaStorage_HeadStaging_Call) RunAndReturn(run func(context1 context.Context, asset *entities.Asset) (*entities.ObjectMetadata, error)) *MockMediaStorage_HeadStaging_Call {
	_c.Call.Return(run)
	return _c
}

// PresignDownload provides a mock function for the type MockMediaStorage
func (_mock *MockMediaStorage) PresignDownload(context1 context.Context, asset *entities.Asset, time1 time.Time, duration time.Duration) (string, error) {
	ret := _mock.Called(context1, asset, time1, duration)

	if len(ret) == 0 {
		panic("no return value specified for PresignDownload")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, time.Time, time.Duration) (string, error)); ok {
		return returnFunc(context1, asset, time1, duration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, time.Time, time.Duration) string); ok {
		r0 = returnFunc(context1, asset, time1, duration)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Asset, time.Time, time.Duration) error); ok {
		r1 = returnFunc(context1, asset, time1, duration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaStorage_PresignDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignDownload'
type MockMediaStorage_PresignDownload_Call struct {
	*mock.Call
}

// PresignDownload is a helper method to define mock.On call
//   - context1 context.Context
//   - asset *entities.Asset
//   - time1 time.Time
//   - duration time.Duration
func (_e *MockMediaStorage_Expecter) PresignDownload(context1 interface{}, asset interface{}, time1 interface{}, duration interface{}) *MockMediaStorage_PresignDownload_Call {
	return &MockMediaStorage_PresignDownload_Call{Call: _e.mock.On("PresignDownload", context1, asset, time1, duration)}
}

func (_c *MockMediaStorage_PresignDownload_Call) Run(run func(context1 context.Context, asset *entities.Asset, time1 time.Time, duration time.Duration)) *MockMediaStorage_PresignDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Asset
		if args[1] != nil {
			arg1 = args[1].(*entities.Asset)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMediaStorage_PresignDownload_Call) Return(s string, err error) *MockMediaStorage_PresignDownload_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMediaStorage_PresignDownload_Call) RunAndReturn(run func(context1 context.Context, asset *entities.Asset, time1 time.Time, duration time.Duration) (string, error)) *MockMediaStorage_PresignDownload_Call {
	_c.Call.Return(run)
	return _c
}

// PresignUpload provides a mock function for the type MockMediaStorage
func (_mock *MockMediaStorage) PresignUpload(context1 context.Context, asset *entities.Asset, time1 time.Time) (*entities.PresignedRequest, error) {
	ret := _mock.Called(context1, asset, time1)

	if len(ret) == 0 {
		panic("no return value specified for PresignUpload")
	}

	var r0 *entities.PresignedRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, time.Time) (*entities.PresignedRequest, error)); ok {
		return returnFunc(context1, asset, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, time.Time) *entities.PresignedRequest); ok {
		r0 = returnFunc(context1, asset, time1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PresignedRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Asset, time.Time) error); ok {
		r1 = returnFunc(context1, asset, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaStorage_PresignUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignUpload'
type MockMediaStorage_PresignUpload_Call struct {
	*mock.Call
}

// PresignUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - asset *entities.Asset
//   - time1 time.Time
func (_e *MockMediaStorage_Expecter) PresignUpload(context1 interface{}, asset interface{}, time1 interface{}) *MockMediaStorage_PresignUpload_Call {
	return &MockMediaStorage_PresignUpload_Call{Call: _e.mock.On("PresignUpload", context1, asset, time1)}
}

func (_c *MockMediaStorage_PresignUpload_Call) Run(run func(context1 context.Context, asset *entities.Asset, time1 time.Time)) *MockMediaStorage_PresignUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Asset
		if args[1] != nil {
			arg1 = args[1].(*entities.Asset)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMediaStorage_PresignUpload_Call) Return(presignedRequest *entities.PresignedRequest, err error) *MockMediaStorage_PresignUpload_Call {
	_c.Call.Return(presignedRequest, err)
	return _c
}

func (_c *MockMediaStorage_PresignUpload_Call) RunAndReturn(run func(context1 context.Context, asset *entities.Asset, time1 time.Time) (*entities.PresignedRequest, error)) *MockMediaStorage_PresignUpload_Call {
	_c.Call.Return(run)
	return _c
}

// PutFinal provides a mock function for the type MockMediaStorage
func (_mock *MockMediaStorage) PutFinal(context1 context.Context, asset *entities.Asset, bytes []byte, s string) (*entities.ObjectMetadata, error) {
	ret := _mock.Called(context1, asset, bytes, s)

	if len(ret) == 0 {
		panic("no return value specified for PutFinal")
	}

	var r0 *entities.ObjectMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, []byte, string) (*entities.ObjectMetadata, error)); ok {
		return returnFunc(context1, asset, bytes, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Asset, []byte, string) *entities.ObjectMetadata); ok {
		r0 = returnFunc(context1, asset, bytes, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ObjectMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Asset, []byte, string) error); ok {
		r1 = returnFunc(context1, asset, bytes, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaStorage_PutFinal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutFinal'
type MockMediaStorage_PutFinal_Call struct {
	*mock.Call
}

// PutFinal is a helper method to define mock.On call
//   - context1 context.Context
//   - asset *entities.Asset
//   - bytes []byte
//   - s string
func (_e *MockMediaStorage_Expecter) PutFinal(context1 interface{}, asset interface{}, bytes interface{}, s interface{}) *MockMediaStorage_PutFinal_Call {
	return &MockMediaStorage_PutFinal_Call{Call: _e.mock.On("PutFinal", context1, asset, bytes, s)}
}

func (_c *MockMediaStorage_PutFinal_Call) Run(run func(context1 context.Context, asset *entities.Asset, bytes []byte, s string)) *MockMediaStorage_PutFinal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Asset
		if args[1] != nil {
			arg1 = args[1].(*entities.Asset)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMediaStorage_PutFinal_Call) Return(objectMetadata *entities.ObjectMetadata, err error) *MockMediaStorage_PutFinal_Call {
	_c.Call.Return(objectMetadata, err)
	return _c
}

func (_c *MockMediaStorage_PutFinal_Call) RunAndReturn(run func(context1 context.Context, asset *entities.Asset, bytes []byte, s string) (*entities.ObjectMetadata, error)) *MockMediaStorage_PutFinal_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConfiguration provides a mock function for the type MockMediaStorage
func (_mock *MockMediaStorage) ValidateConfiguration() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidateConfiguration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaStorage_ValidateConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConfiguration'
type MockMediaStorage_ValidateConfiguration_Call struct {
	*mock.Call
}

// ValidateConfiguration is a helper method to define mock.On call
func (_e *MockMediaStorage_Expecter) ValidateConfiguration() *MockMediaStorage_ValidateConfiguration_Call {
	return &MockMediaStorage_ValidateConfiguration_Call{Call: _e.mock.On("ValidateConfiguration")}
}

func (_c *MockMediaStorage_ValidateConfiguration_Call) Run(run func()) *MockMediaStorage_ValidateConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMediaStorage_ValidateConfiguration_Call) Return(err error) *MockMediaStorage_ValidateConfiguration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaStorage_ValidateConfiguration_Call) RunAndReturn(run func() error) *MockMediaStorage_ValidateConfiguration_Call {
	_c.Call.Return(run)
	return _c
}
