// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	entities1 "github.com/dnjtechteam/dnj-game-api/internal/domain/game/entities"
	entities0 "github.com/dnjtechteam/dnj-game-api/internal/domain/media/entities"
	"github.com/dnjtechteam/dnj-game-api/internal/domain/moment/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMomentRepository creates a new instance of MockMomentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMomentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMomentRepository {
	mock := &MockMomentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMomentRepository is an autogenerated mock type for the Repository type
type MockMomentRepository struct {
	mock.Mock
}

type MockMomentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMomentRepository) EXPECT() *MockMomentRepository_Expecter {
	return &MockMomentRepository_Expecter{mock: &_m.Mock}
}

// ApplyModeration provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) ApplyModeration(context1 context.Context, s string, s1 string, v uint64, s2 string, time1 time.Time) (*entities.Moment, *entities0.Asset, bool, error) {
	ret := _mock.Called(context1, s, s1, v, s2, time1)

	if len(ret) == 0 {
		panic("no return value specified for ApplyModeration")
	}

	var r0 *entities.Moment
	var r1 *entities0.Asset
	var r2 bool
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint64, string, time.Time) (*entities.Moment, *entities0.Asset, bool, error)); ok {
		return returnFunc(context1, s, s1, v, s2, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint64, string, time.Time) *entities.Moment); ok {
		r0 = returnFunc(context1, s, s1, v, s2, time1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, uint64, string, time.Time) *entities0.Asset); ok {
		r1 = returnFunc(context1, s, s1, v, s2, time1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities0.Asset)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, uint64, string, time.Time) bool); ok {
		r2 = returnFunc(context1, s, s1, v, s2, time1)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, string, uint64, string, time.Time) error); ok {
		r3 = returnFunc(context1, s, s1, v, s2, time1)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockMomentRepository_ApplyModeration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyModeration'
type MockMomentRepository_ApplyModeration_Call struct {
	*mock.Call
}

// ApplyModeration is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - v uint64
//   - s2 string
//   - time1 time.Time
func (_e *MockMomentRepository_Expecter) ApplyModeration(context1 interface{}, s interface{}, s1 interface{}, v interface{}, s2 interface{}, time1 interface{}) *MockMomentRepository_ApplyModeration_Call {
	return &MockMomentRepository_ApplyModeration_Call{Call: _e.mock.On("ApplyModeration", context1, s, s1, v, s2, time1)}
}

func (_c *MockMomentRepository_ApplyModeration_Call) Run(run func(context1 context.Context, s string, s1 string, v uint64, s2 string, time1 time.Time)) *MockMomentRepository_ApplyModeration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMomentRepository_ApplyModeration_Call) Return(moment *entities.Moment, asset *entities0.Asset, b bool, err error) *MockMomentRepository_ApplyModeration_Call {
	_c.Call.Return(moment, asset, b, err)
	return _c
}

func (_c *MockMomentRepository_ApplyModeration_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, v uint64, s2 string, time1 time.Time) (*entities.Moment, *entities0.Asset, bool, error)) *MockMomentRepository_ApplyModeration_Call {
	_c.Call.Return(run)
	return _c
}

// AwardMoment provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) AwardMoment(context1 context.Context, s string, v uint64, s1 string, n int, time1 time.Time) error {
	ret := _mock.Called(context1, s, v, s1, n, time1)

	if len(ret) == 0 {
		panic("no return value specified for AwardMoment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, string, int, time.Time) error); ok {
		r0 = returnFunc(context1, s, v, s1, n, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMomentRepository_AwardMoment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AwardMoment'
type MockMomentRepository_AwardMoment_Call struct {
	*mock.Call
}

// AwardMoment is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - v uint64
//   - s1 string
//   - n int
//   - time1 time.Time
func (_e *MockMomentRepository_Expecter) AwardMoment(context1 interface{}, s interface{}, v interface{}, s1 interface{}, n interface{}, time1 interface{}) *MockMomentRepository_AwardMoment_Call {
	return &MockMomentRepository_AwardMoment_Call{Call: _e.mock.On("AwardMoment", context1, s, v, s1, n, time1)}
}

func (_c *MockMomentRepository_AwardMoment_Call) Run(run func(context1 context.Context, s string, v uint64, s1 string, n int, time1 time.Time)) *MockMomentRepository_AwardMoment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMomentRepository_AwardMoment_Call) Return(err error) *MockMomentRepository_AwardMoment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMomentRepository_AwardMoment_Call) RunAndReturn(run func(context1 context.Context, s string, v uint64, s1 string, n int, time1 time.Time) error) *MockMomentRepository_AwardMoment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateModerationDecision provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) CreateModerationDecision(context1 context.Context, moderationDecision *entities.ModerationDecision) (bool, error) {
	ret := _mock.Called(context1, moderationDecision)

	if len(ret) == 0 {
		panic("no return value specified for CreateModerationDecision")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.ModerationDecision) (bool, error)); ok {
		return returnFunc(context1, moderationDecision)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.ModerationDecision) bool); ok {
		r0 = returnFunc(context1, moderationDecision)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.ModerationDecision) error); ok {
		r1 = returnFunc(context1, moderationDecision)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_CreateModerationDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateModerationDecision'
type MockMomentRepository_CreateModerationDecision_Call struct {
	*mock.Call
}

// CreateModerationDecision is a helper method to define mock.On call
//   - context1 context.Context
//   - moderationDecision *entities.ModerationDecision
func (_e *MockMomentRepository_Expecter) CreateModerationDecision(context1 interface{}, moderationDecision interface{}) *MockMomentRepository_CreateModerationDecision_Call {
	return &MockMomentRepository_CreateModerationDecision_Call{Call: _e.mock.On("CreateModerationDecision", context1, moderationDecision)}
}

func (_c *MockMomentRepository_CreateModerationDecision_Call) Run(run func(context1 context.Context, moderationDecision *entities.ModerationDecision)) *MockMomentRepository_CreateModerationDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.ModerationDecision
		if args[1] != nil {
			arg1 = args[1].(*entities.ModerationDecision)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMomentRepository_CreateModerationDecision_Call) Return(b bool, err error) *MockMomentRepository_CreateModerationDecision_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockMomentRepository_CreateModerationDecision_Call) RunAndReturn(run func(context1 context.Context, moderationDecision *entities.ModerationDecision) (bool, error)) *MockMomentRepository_CreateModerationDecision_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMoment provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) CreateMoment(context1 context.Context, moment *entities.Moment) error {
	ret := _mock.Called(context1, moment)

	if len(ret) == 0 {
		panic("no return value specified for CreateMoment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Moment) error); ok {
		r0 = returnFunc(context1, moment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMomentRepository_CreateMoment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMoment'
type MockMomentRepository_CreateMoment_Call struct {
	*mock.Call
}

// CreateMoment is a helper method to define mock.On call
//   - context1 context.Context
//   - moment *entities.Moment
func (_e *MockMomentRepository_Expecter) CreateMoment(context1 interface{}, moment interface{}) *MockMomentRepository_CreateMoment_Call {
	return &MockMomentRepository_CreateMoment_Call{Call: _e.mock.On("CreateMoment", context1, moment)}
}

func (_c *MockMomentRepository_CreateMoment_Call) Run(run func(context1 context.Context, moment *entities.Moment)) *MockMomentRepository_CreateMoment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Moment
		if args[1] != nil {
			arg1 = args[1].(*entities.Moment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMomentRepository_CreateMoment_Call) Return(err error) *MockMomentRepository_CreateMoment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMomentRepository_CreateMoment_Call) RunAndReturn(run func(context1 context.Context, moment *entities.Moment) error) *MockMomentRepository_CreateMoment_Call {
	_c.Call.Return(run)
	return _c
}

// FindActivityForUpdate provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) FindActivityForUpdate(context1 context.Context, s string) (string, bool, *time.Time, *time.Time, int, string, *string, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindActivityForUpdate")
	}

	var r0 string
	var r1 bool
	var r2 *time.Time
	var r3 *time.Time
	var r4 int
	var r5 string
	var r6 *string
	var r7 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, bool, *time.Time, *time.Time, int, string, *string, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) *time.Time); ok {
		r2 = returnFunc(context1, s)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string) *time.Time); ok {
		r3 = returnFunc(context1, s)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(4).(func(context.Context, string) int); ok {
		r4 = returnFunc(context1, s)
	} else {
		r4 = ret.Get(4).(int)
	}
	if returnFunc, ok := ret.Get(5).(func(context.Context, string) string); ok {
		r5 = returnFunc(context1, s)
	} else {
		r5 = ret.Get(5).(string)
	}
	if returnFunc, ok := ret.Get(6).(func(context.Context, string) *string); ok {
		r6 = returnFunc(context1, s)
	} else {
		if ret.Get(6) != nil {
			r6 = ret.Get(6).(*string)
		}
	}
	if returnFunc, ok := ret.Get(7).(func(context.Context, string) error); ok {
		r7 = returnFunc(context1, s)
	} else {
		r7 = ret.Error(7)
	}
	return r0, r1, r2, r3, r4, r5, r6, r7
}

// MockMomentRepository_FindActivityForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActivityForUpdate'
type MockMomentRepository_FindActivityForUpdate_Call struct {
	*mock.Call
}

// FindActivityForUpdate is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockMomentRepository_Expecter) FindActivityForUpdate(context1 interface{}, s interface{}) *MockMomentRepository_FindActivityForUpdate_Call {
	return &MockMomentRepository_FindActivityForUpdate_Call{Call: _e.mock.On("FindActivityForUpdate", context1, s)}
}

func (_c *MockMomentRepository_FindActivityForUpdate_Call) Run(run func(context1 context.Context, s string)) *MockMomentRepository_FindActivityForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMomentRepository_FindActivityForUpdate_Call) Return(s1 string, b bool, time1 *time.Time, time11 *time.Time, n int, s2 string, s3 *string, err error) *MockMomentRepository_FindActivityForUpdate_Call {
	_c.Call.Return(s1, b, time1, time11, n, s2, s3, err)
	return _c
}

func (_c *MockMomentRepository_FindActivityForUpdate_Call) RunAndReturn(run func(context1 context.Context, s string) (string, bool, *time.Time, *time.Time, int, string, *string, error)) *MockMomentRepository_FindActivityForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindMoment provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) FindMoment(context1 context.Context, s string, v uint64, b bool) (*entities.Moment, error) {
	ret := _mock.Called(context1, s, v, b)

	if len(ret) == 0 {
		panic("no return value specified for FindMoment")
	}

	var r0 *entities.Moment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool) (*entities.Moment, error)); ok {
		return returnFunc(context1, s, v, b)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool) *entities.Moment); ok {
		r0 = returnFunc(context1, s, v, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Moment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, bool) error); ok {
		r1 = returnFunc(context1, s, v, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_FindMoment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMoment'
type MockMomentRepository_FindMoment_Call struct {
	*mock.Call
}

// FindMoment is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - v uint64
//   - b bool
func (_e *MockMomentRepository_Expecter) FindMoment(context1 interface{}, s interface{}, v interface{}, b interface{}) *MockMomentRepository_FindMoment_Call {
	return &MockMomentRepository_FindMoment_Call{Call: _e.mock.On("FindMoment", context1, s, v, b)}
}

func (_c *MockMomentRepository_FindMoment_Call) Run(run func(context1 context.Context, s string, v uint64, b bool)) *MockMomentRepository_FindMoment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMomentRepository_FindMoment_Call) Return(moment *entities.Moment, err error) *MockMomentRepository_FindMoment_Call {
	_c.Call.Return(moment, err)
	return _c
}

func (_c *MockMomentRepository_FindMoment_Call) RunAndReturn(run func(context1 context.Context, s string, v uint64, b bool) (*entities.Moment, error)) *MockMomentRepository_FindMoment_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipationForUpdate provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) FindParticipationForUpdate(context1 context.Context, s string) (*entities1.Participation, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipationForUpdate")
	}

	var r0 *entities1.Participation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities1.Participation, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities1.Participation); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities1.Participation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_FindParticipationForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipationForUpdate'
type MockMomentRepository_FindParticipationForUpdate_Call struct {
	*mock.Call
}

// FindParticipationForUpdate is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockMomentRepository_Expecter) FindParticipationForUpdate(context1 interface{}, s interface{}) *MockMomentRepository_FindParticipationForUpdate_Call {
	return &MockMomentRepository_FindParticipationForUpdate_Call{Call: _e.mock.On("FindParticipationForUpdate", context1, s)}
}

func (_c *MockMomentRepository_FindParticipationForUpdate_Call) Run(run func(context1 context.Context, s string)) *MockMomentRepository_FindParticipationForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMomentRepository_FindParticipationForUpdate_Call) Return(participation *entities1.Participation, err error) *MockMomentRepository_FindParticipationForUpdate_Call {
	_c.Call.Return(participation, err)
	return _c
}

func (_c *MockMomentRepository_FindParticipationForUpdate_Call) RunAndReturn(run func(context1 context.Context, s string) (*entities1.Participation, error)) *MockMomentRepository_FindParticipationForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// ListModeration provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) ListModeration(context1 context.Context, s string, v uint64, time1 time.Time) (*entities.ModerationPage, error) {
	ret := _mock.Called(context1, s, v, time1)

	if len(ret) == 0 {
		panic("no return value specified for ListModeration")
	}

	var r0 *entities.ModerationPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, time.Time) (*entities.ModerationPage, error)); ok {
		return returnFunc(context1, s, v, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, time.Time) *entities.ModerationPage); ok {
		r0 = returnFunc(context1, s, v, time1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ModerationPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, time.Time) error); ok {
		r1 = returnFunc(context1, s, v, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_ListModeration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModeration'
type MockMomentRepository_ListModeration_Call struct {
	*mock.Call
}

// ListModeration is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - v uint64
//   - time1 time.Time
func (_e *MockMomentRepository_Expecter) ListModeration(context1 interface{}, s interface{}, v interface{}, time1 interface{}) *MockMomentRepository_ListModeration_Call {
	return &MockMomentRepository_ListModeration_Call{Call: _e.mock.On("ListModeration", context1, s, v, time1)}
}

func (_c *MockMomentRepository_ListModeration_Call) Run(run func(context1 context.Context, s string, v uint64, time1 time.Time)) *MockMomentRepository_ListModeration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMomentRepository_ListModeration_Call) Return(moderationPage *entities.ModerationPage, err error) *MockMomentRepository_ListModeration_Call {
	_c.Call.Return(moderationPage, err)
	return _c
}

func (_c *MockMomentRepository_ListModeration_Call) RunAndReturn(run func(context1 context.Context, s string, v uint64, time1 time.Time) (*entities.ModerationPage, error)) *MockMomentRepository_ListModeration_Call {
	_c.Call.Return(run)
	return _c
}

// ListMoments provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) ListMoments(context1 context.Context, s string, v uint64, v1 *uint64, cursor *entities.Cursor, time1 time.Time) (*entities.Page, error) {
	ret := _mock.Called(context1, s, v, v1, cursor, time1)

	if len(ret) == 0 {
		panic("no return value specified for ListMoments")
	}

	var r0 *entities.Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, *uint64, *entities.Cursor, time.Time) (*entities.Page, error)); ok {
		return returnFunc(context1, s, v, v1, cursor, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, *uint64, *entities.Cursor, time.Time) *entities.Page); ok {
		r0 = returnFunc(context1, s, v, v1, cursor, time1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Page)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, *uint64, *entities.Cursor, time.Time) error); ok {
		r1 = returnFunc(context1, s, v, v1, cursor, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_ListMoments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMoments'
type MockMomentRepository_ListMoments_Call struct {
	*mock.Call
}

// ListMoments is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - v uint64
//   - v1 *uint64
//   - cursor *entities.Cursor
//   - time1 time.Time
func (_e *MockMomentRepository_Expecter) ListMoments(context1 interface{}, s interface{}, v interface{}, v1 interface{}, cursor interface{}, time1 interface{}) *MockMomentRepository_ListMoments_Call {
	return &MockMomentRepository_ListMoments_Call{Call: _e.mock.On("ListMoments", context1, s, v, v1, cursor, time1)}
}

func (_c *MockMomentRepository_ListMoments_Call) Run(run func(context1 context.Context, s string, v uint64, v1 *uint64, cursor *entities.Cursor, time1 time.Time)) *MockMomentRepository_ListMoments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 *entities.Cursor
		if args[4] != nil {
			arg4 = args[4].(*entities.Cursor)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMomentRepository_ListMoments_Call) Return(page *entities.Page, err error) *MockMomentRepository_ListMoments_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockMomentRepository_ListMoments_Call) RunAndReturn(run func(context1 context.Context, s string, v uint64, v1 *uint64, cursor *entities.Cursor, time1 time.Time) (*entities.Page, error)) *MockMomentRepository_ListMoments_Call {
	_c.Call.Return(run)
	return _c
}

// ReverseMomentAward provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) ReverseMomentAward(context1 context.Context, s string, v uint64, time1 time.Time) (bool, error) {
	ret := _mock.Called(context1, s, v, time1)

	if len(ret) == 0 {
		panic("no return value specified for ReverseMomentAward")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, time.Time) (bool, error)); ok {
		return returnFunc(context1, s, v, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, time.Time) bool); ok {
		r0 = returnFunc(context1, s, v, time1)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, time.Time) error); ok {
		r1 = returnFunc(context1, s, v, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMomentRepository_ReverseMomentAward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReverseMomentAward'
type MockMomentRepository_ReverseMomentAward_Call struct {
	*mock.Call
}

// ReverseMomentAward is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - v uint64
//   - time1 time.Time
func (_e *MockMomentRepository_Expecter) ReverseMomentAward(context1 interface{}, s interface{}, v interface{}, time1 interface{}) *MockMomentRepository_ReverseMomentAward_Call {
	return &MockMomentRepository_ReverseMomentAward_Call{Call: _e.mock.On("ReverseMomentAward", context1, s, v, time1)}
}

func (_c *MockMomentRepository_ReverseMomentAward_Call) Run(run func(context1 context.Context, s string, v uint64, time1 time.Time)) *MockMomentRepository_ReverseMomentAward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMomentRepository_ReverseMomentAward_Call) Return(b bool, err error) *MockMomentRepository_ReverseMomentAward_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockMomentRepository_ReverseMomentAward_Call) RunAndReturn(run func(context1 context.Context, s string, v uint64, time1 time.Time) (bool, error)) *MockMomentRepository_ReverseMomentAward_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleLike provides a mock function for the type MockMomentRepository
func (_mock *MockMomentRepository) ToggleLike(context1 context.Context, s string, v uint64, time1 time.Time) (bool, int, error) {
	ret := _mock.Called(context1, s, v, time1)

	if len(ret) == 0 {
		panic("no return value specified for ToggleLike")
	}

	var r0 bool
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, time.Time) (bool, int, error)); ok {
		return returnFunc(context1, s, v, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, time.Time) bool); ok {
		r0 = returnFunc(context1, s, v, time1)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, time.Time) int); ok {
		r1 = returnFunc(context1, s, v, time1)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, uint64, time.Time) error); ok {
		r2 = returnFunc(context1, s, v, time1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMomentRepository_ToggleLike_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleLike'
type MockMomentRepository_ToggleLike_Call struct {
	*mock.Call
}

// ToggleLike is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - v uint64
//   - time1 time.Time
func (_e *MockMomentRepository_Expecter) ToggleLike(context1 interface{}, s interface{}, v interface{}, time1 interface{}) *MockMomentRepository_ToggleLike_Call {
	return &MockMomentRepository_ToggleLike_Call{Call: _e.mock.On("ToggleLike", context1, s, v, time1)}
}

func (_c *MockMomentRepository_ToggleLike_Call) Run(run func(context1 context.Context, s string, v uint64, time1 time.Time)) *MockMomentRepository_ToggleLike_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMomentRepository_ToggleLike_Call) Return(b bool, n int, err error) *MockMomentRepository_ToggleLike_Call {
	_c.Call.Return(b, n, err)
	return _c
}

func (_c *MockMomentRepository_ToggleLike_Call) RunAndReturn(run func(context1 context.Context, s string, v uint64, time1 time.Time) (bool, int, error)) *MockMomentRepository_ToggleLike_Call {
	_c.Call.Return(run)
	return _c
}
