// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/dnjtechteam/dnj-game-api/internal/app/messages"
	"github.com/dnjtechteam/dnj-game-api/internal/domain/notification/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationRepository is an autogenerated mock type for the Repository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// CountUnread provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) CountUnread(ctx context.Context, userID uint64) (uint64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUnread")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (uint64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_CountUnread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUnread'
type MockNotificationRepository_CountUnread_Call struct {
	*mock.Call
}

// CountUnread is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockNotificationRepository_Expecter) CountUnread(ctx interface{}, userID interface{}) *MockNotificationRepository_CountUnread_Call {
	return &MockNotificationRepository_CountUnread_Call{Call: _e.mock.On("CountUnread", ctx, userID)}
}

func (_c *MockNotificationRepository_CountUnread_Call) Run(run func(ctx context.Context, userID uint64)) *MockNotificationRepository_CountUnread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_CountUnread_Call) Return(v uint64, err error) *MockNotificationRepository_CountUnread_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockNotificationRepository_CountUnread_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (uint64, error)) *MockNotificationRepository_CountUnread_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBroadcast provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) CreateBroadcast(ctx context.Context, notifications []*entities.Notification) error {
	ret := _mock.Called(ctx, notifications)

	if len(ret) == 0 {
		panic("no return value specified for CreateBroadcast")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.Notification) error); ok {
		r0 = returnFunc(ctx, notifications)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_CreateBroadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBroadcast'
type MockNotificationRepository_CreateBroadcast_Call struct {
	*mock.Call
}

// CreateBroadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - notifications []*entities.Notification
func (_e *MockNotificationRepository_Expecter) CreateBroadcast(ctx interface{}, notifications interface{}) *MockNotificationRepository_CreateBroadcast_Call {
	return &MockNotificationRepository_CreateBroadcast_Call{Call: _e.mock.On("CreateBroadcast", ctx, notifications)}
}

func (_c *MockNotificationRepository_CreateBroadcast_Call) Run(run func(ctx context.Context, notifications []*entities.Notification)) *MockNotificationRepository_CreateBroadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.Notification
		if args[1] != nil {
			arg1 = args[1].([]*entities.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_CreateBroadcast_Call) Return(err error) *MockNotificationRepository_CreateBroadcast_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_CreateBroadcast_Call) RunAndReturn(run func(ctx context.Context, notifications []*entities.Notification) error) *MockNotificationRepository_CreateBroadcast_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOperation provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) CreateOperation(ctx context.Context, operation *entities.Operation) error {
	ret := _mock.Called(ctx, operation)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Operation) error); ok {
		r0 = returnFunc(ctx, operation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_CreateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOperation'
type MockNotificationRepository_CreateOperation_Call struct {
	*mock.Call
}

// CreateOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - operation *entities.Operation
func (_e *MockNotificationRepository_Expecter) CreateOperation(ctx interface{}, operation interface{}) *MockNotificationRepository_CreateOperation_Call {
	return &MockNotificationRepository_CreateOperation_Call{Call: _e.mock.On("CreateOperation", ctx, operation)}
}

func (_c *MockNotificationRepository_CreateOperation_Call) Run(run func(ctx context.Context, operation *entities.Operation)) *MockNotificationRepository_CreateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Operation
		if args[1] != nil {
			arg1 = args[1].(*entities.Operation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_CreateOperation_Call) Return(err error) *MockNotificationRepository_CreateOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_CreateOperation_Call) RunAndReturn(run func(ctx context.Context, operation *entities.Operation) error) *MockNotificationRepository_CreateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDAndUser provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) FindByIDAndUser(ctx context.Context, id string, userID uint64) (*entities.Notification, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDAndUser")
	}

	var r0 *entities.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) (*entities.Notification, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) *entities.Notification); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_FindByIDAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDAndUser'
type MockNotificationRepository_FindByIDAndUser_Call struct {
	*mock.Call
}

// FindByIDAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID uint64
func (_e *MockNotificationRepository_Expecter) FindByIDAndUser(ctx interface{}, id interface{}, userID interface{}) *MockNotificationRepository_FindByIDAndUser_Call {
	return &MockNotificationRepository_FindByIDAndUser_Call{Call: _e.mock.On("FindByIDAndUser", ctx, id, userID)}
}

func (_c *MockNotificationRepository_FindByIDAndUser_Call) Run(run func(ctx context.Context, id string, userID uint64)) *MockNotificationRepository_FindByIDAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_FindByIDAndUser_Call) Return(notification *entities.Notification, err error) *MockNotificationRepository_FindByIDAndUser_Call {
	_c.Call.Return(notification, err)
	return _c
}

func (_c *MockNotificationRepository_FindByIDAndUser_Call) RunAndReturn(run func(ctx context.Context, id string, userID uint64) (*entities.Notification, error)) *MockNotificationRepository_FindByIDAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindOperation provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) FindOperation(ctx context.Context, actorID uint64, key string) (*entities.Operation, error) {
	ret := _mock.Called(ctx, actorID, key)

	if len(ret) == 0 {
		panic("no return value specified for FindOperation")
	}

	var r0 *entities.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (*entities.Operation, error)); ok {
		return returnFunc(ctx, actorID, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) *entities.Operation); ok {
		r0 = returnFunc(ctx, actorID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(ctx, actorID, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_FindOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOperation'
type MockNotificationRepository_FindOperation_Call struct {
	*mock.Call
}

// FindOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uint64
//   - key string
func (_e *MockNotificationRepository_Expecter) FindOperation(ctx interface{}, actorID interface{}, key interface{}) *MockNotificationRepository_FindOperation_Call {
	return &MockNotificationRepository_FindOperation_Call{Call: _e.mock.On("FindOperation", ctx, actorID, key)}
}

func (_c *MockNotificationRepository_FindOperation_Call) Run(run func(ctx context.Context, actorID uint64, key string)) *MockNotificationRepository_FindOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_FindOperation_Call) Return(operation *entities.Operation, err error) *MockNotificationRepository_FindOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockNotificationRepository_FindOperation_Call) RunAndReturn(run func(ctx context.Context, actorID uint64, key string) (*entities.Operation, error)) *MockNotificationRepository_FindOperation_Call {
	_c.Call.Return(run)
	return _c
}

// FindPreferences provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) FindPreferences(ctx context.Context, userID uint64) (*entities.Preferences, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindPreferences")
	}

	var r0 *entities.Preferences
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entities.Preferences, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entities.Preferences); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Preferences)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_FindPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPreferences'
type MockNotificationRepository_FindPreferences_Call struct {
	*mock.Call
}

// FindPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockNotificationRepository_Expecter) FindPreferences(ctx interface{}, userID interface{}) *MockNotificationRepository_FindPreferences_Call {
	return &MockNotificationRepository_FindPreferences_Call{Call: _e.mock.On("FindPreferences", ctx, userID)}
}

func (_c *MockNotificationRepository_FindPreferences_Call) Run(run func(ctx context.Context, userID uint64)) *MockNotificationRepository_FindPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_FindPreferences_Call) Return(preferences *entities.Preferences, err error) *MockNotificationRepository_FindPreferences_Call {
	_c.Call.Return(preferences, err)
	return _c
}

func (_c *MockNotificationRepository_FindPreferences_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (*entities.Preferences, error)) *MockNotificationRepository_FindPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) List(ctx context.Context, userID uint64, page uint64) (*messages.PaginatedResponse[entities.Notification], error) {
	ret := _mock.Called(ctx, userID, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *messages.PaginatedResponse[entities.Notification]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*messages.PaginatedResponse[entities.Notification], error)); ok {
		return returnFunc(ctx, userID, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) *messages.PaginatedResponse[entities.Notification]); ok {
		r0 = returnFunc(ctx, userID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.PaginatedResponse[entities.Notification])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNotificationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - page uint64
func (_e *MockNotificationRepository_Expecter) List(ctx interface{}, userID interface{}, page interface{}) *MockNotificationRepository_List_Call {
	return &MockNotificationRepository_List_Call{Call: _e.mock.On("List", ctx, userID, page)}
}

func (_c *MockNotificationRepository_List_Call) Run(run func(ctx context.Context, userID uint64, page uint64)) *MockNotificationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_List_Call) Return(paginatedResponse *messages.PaginatedResponse[entities.Notification], err error) *MockNotificationRepository_List_Call {
	_c.Call.Return(paginatedResponse, err)
	return _c
}

func (_c *MockNotificationRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID uint64, page uint64) (*messages.PaginatedResponse[entities.Notification], error)) *MockNotificationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) MarkRead(ctx context.Context, id string, userID uint64, now time.Time) (*entities.Notification, error) {
	ret := _mock.Called(ctx, id, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 *entities.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, time.Time) (*entities.Notification, error)); ok {
		return returnFunc(ctx, id, userID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, time.Time) *entities.Notification); ok {
		r0 = returnFunc(ctx, id, userID, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, time.Time) error); ok {
		r1 = returnFunc(ctx, id, userID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockNotificationRepository_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID uint64
//   - now time.Time
func (_e *MockNotificationRepository_Expecter) MarkRead(ctx interface{}, id interface{}, userID interface{}, now interface{}) *MockNotificationRepository_MarkRead_Call {
	return &MockNotificationRepository_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, id, userID, now)}
}

func (_c *MockNotificationRepository_MarkRead_Call) Run(run func(ctx context.Context, id string, userID uint64, now time.Time)) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_MarkRead_Call) Return(notification *entities.Notification, err error) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Return(notification, err)
	return _c
}

func (_c *MockNotificationRepository_MarkRead_Call) RunAndReturn(run func(ctx context.Context, id string, userID uint64, now time.Time) (*entities.Notification, error)) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveAnnouncementRecipients provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) ResolveAnnouncementRecipients(ctx context.Context, explicitUserIDs []uint64) ([]uint64, error) {
	ret := _mock.Called(ctx, explicitUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAnnouncementRecipients")
	}

	var r0 []uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint64) ([]uint64, error)); ok {
		return returnFunc(ctx, explicitUserIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint64) []uint64); ok {
		r0 = returnFunc(ctx, explicitUserIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = returnFunc(ctx, explicitUserIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_ResolveAnnouncementRecipients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAnnouncementRecipients'
type MockNotificationRepository_ResolveAnnouncementRecipients_Call struct {
	*mock.Call
}

// ResolveAnnouncementRecipients is a helper method to define mock.On call
//   - ctx context.Context
//   - explicitUserIDs []uint64
func (_e *MockNotificationRepository_Expecter) ResolveAnnouncementRecipients(ctx interface{}, explicitUserIDs interface{}) *MockNotificationRepository_ResolveAnnouncementRecipients_Call {
	return &MockNotificationRepository_ResolveAnnouncementRecipients_Call{Call: _e.mock.On("ResolveAnnouncementRecipients", ctx, explicitUserIDs)}
}

func (_c *MockNotificationRepository_ResolveAnnouncementRecipients_Call) Run(run func(ctx context.Context, explicitUserIDs []uint64)) *MockNotificationRepository_ResolveAnnouncementRecipients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint64
		if args[1] != nil {
			arg1 = args[1].([]uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_ResolveAnnouncementRecipients_Call) Return(uint64s []uint64, err error) *MockNotificationRepository_ResolveAnnouncementRecipients_Call {
	_c.Call.Return(uint64s, err)
	return _c
}

func (_c *MockNotificationRepository_ResolveAnnouncementRecipients_Call) RunAndReturn(run func(ctx context.Context, explicitUserIDs []uint64) ([]uint64, error)) *MockNotificationRepository_ResolveAnnouncementRecipients_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPreferences provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) UpsertPreferences(ctx context.Context, prefs *entities.Preferences) (*entities.Preferences, error) {
	ret := _mock.Called(ctx, prefs)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPreferences")
	}

	var r0 *entities.Preferences
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Preferences) (*entities.Preferences, error)); ok {
		return returnFunc(ctx, prefs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Preferences) *entities.Preferences); ok {
		r0 = returnFunc(ctx, prefs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Preferences)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Preferences) error); ok {
		r1 = returnFunc(ctx, prefs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_UpsertPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPreferences'
type MockNotificationRepository_UpsertPreferences_Call struct {
	*mock.Call
}

// UpsertPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - prefs *entities.Preferences
func (_e *MockNotificationRepository_Expecter) UpsertPreferences(ctx interface{}, prefs interface{}) *MockNotificationRepository_UpsertPreferences_Call {
	return &MockNotificationRepository_UpsertPreferences_Call{Call: _e.mock.On("UpsertPreferences", ctx, prefs)}
}

func (_c *MockNotificationRepository_UpsertPreferences_Call) Run(run func(ctx context.Context, prefs *entities.Preferences)) *MockNotificationRepository_UpsertPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Preferences
		if args[1] != nil {
			arg1 = args[1].(*entities.Preferences)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_UpsertPreferences_Call) Return(preferences *entities.Preferences, err error) *MockNotificationRepository_UpsertPreferences_Call {
	_c.Call.Return(preferences, err)
	return _c
}

func (_c *MockNotificationRepository_UpsertPreferences_Call) RunAndReturn(run func(ctx context.Context, prefs *entities.Preferences) (*entities.Preferences, error)) *MockNotificationRepository_UpsertPreferences_Call {
	_c.Call.Return(run)
	return _c
}
