// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnjtechteam/dnj-game-api/internal/domain/operationaudit/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperationAuditRepositoryInterface creates a new instance of MockOperationAuditRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationAuditRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationAuditRepositoryInterface {
	mock := &MockOperationAuditRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperationAuditRepositoryInterface is an autogenerated mock type for the OperationAuditRepositoryInterface type
type MockOperationAuditRepositoryInterface struct {
	mock.Mock
}

type MockOperationAuditRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationAuditRepositoryInterface) EXPECT() *MockOperationAuditRepositoryInterface_Expecter {
	return &MockOperationAuditRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOperationAuditRepositoryInterface
func (_mock *MockOperationAuditRepositoryInterface) Create(ctx context.Context, audit *entities.OperationAudit) (*entities.OperationAudit, error) {
	ret := _mock.Called(ctx, audit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.OperationAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.OperationAudit) (*entities.OperationAudit, error)); ok {
		return returnFunc(ctx, audit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.OperationAudit) *entities.OperationAudit); ok {
		r0 = returnFunc(ctx, audit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OperationAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.OperationAudit) error); ok {
		r1 = returnFunc(ctx, audit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationAuditRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOperationAuditRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - audit *entities.OperationAudit
func (_e *MockOperationAuditRepositoryInterface_Expecter) Create(ctx interface{}, audit interface{}) *MockOperationAuditRepositoryInterface_Create_Call {
	return &MockOperationAuditRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, audit)}
}

func (_c *MockOperationAuditRepositoryInterface_Create_Call) Run(run func(ctx context.Context, audit *entities.OperationAudit)) *MockOperationAuditRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.OperationAudit
		if args[1] != nil {
			arg1 = args[1].(*entities.OperationAudit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperationAuditRepositoryInterface_Create_Call) Return(operationAudit *entities.OperationAudit, err error) *MockOperationAuditRepositoryInterface_Create_Call {
	_c.Call.Return(operationAudit, err)
	return _c
}

func (_c *MockOperationAuditRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, audit *entities.OperationAudit) (*entities.OperationAudit, error)) *MockOperationAuditRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByActorAndIdempotencyKey provides a mock function for the type MockOperationAuditRepositoryInterface
func (_mock *MockOperationAuditRepositoryInterface) FindByActorAndIdempotencyKey(ctx context.Context, actorUserID uint64, key string) (*entities.OperationAudit, error) {
	ret := _mock.Called(ctx, actorUserID, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByActorAndIdempotencyKey")
	}

	var r0 *entities.OperationAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (*entities.OperationAudit, error)); ok {
		return returnFunc(ctx, actorUserID, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) *entities.OperationAudit); ok {
		r0 = returnFunc(ctx, actorUserID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OperationAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(ctx, actorUserID, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByActorAndIdempotencyKey'
type MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call struct {
	*mock.Call
}

// FindByActorAndIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID uint64
//   - key string
func (_e *MockOperationAuditRepositoryInterface_Expecter) FindByActorAndIdempotencyKey(ctx interface{}, actorUserID interface{}, key interface{}) *MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call {
	return &MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call{Call: _e.mock.On("FindByActorAndIdempotencyKey", ctx, actorUserID, key)}
}

func (_c *MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call) Run(run func(ctx context.Context, actorUserID uint64, key string)) *MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call) Return(operationAudit *entities.OperationAudit, err error) *MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call {
	_c.Call.Return(operationAudit, err)
	return _c
}

func (_c *MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, actorUserID uint64, key string) (*entities.OperationAudit, error)) *MockOperationAuditRepositoryInterface_FindByActorAndIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}
