// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnjtechteam/dnj-game-api/internal/app/interfaces"
	"github.com/dnjtechteam/dnj-game-api/internal/app/messages"
	"github.com/dnjtechteam/dnj-game-api/internal/domain/user/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthServiceInterface creates a new instance of MockAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type MockAuthServiceInterface struct {
	mock.Mock
}

type MockAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterface_Expecter {
	return &MockAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// Onboarding provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) Onboarding(ctx context.Context, request *messages.OnboardingRequestDTO) (*messages.OnboardingResponseDTO, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Onboarding")
	}

	var r0 *messages.OnboardingResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.OnboardingRequestDTO) (*messages.OnboardingResponseDTO, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.OnboardingRequestDTO) *messages.OnboardingResponseDTO); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.OnboardingResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messages.OnboardingRequestDTO) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceInterface_Onboarding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Onboarding'
type MockAuthServiceInterface_Onboarding_Call struct {
	*mock.Call
}

// Onboarding is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.OnboardingRequestDTO
func (_e *MockAuthServiceInterface_Expecter) Onboarding(ctx interface{}, request interface{}) *MockAuthServiceInterface_Onboarding_Call {
	return &MockAuthServiceInterface_Onboarding_Call{Call: _e.mock.On("Onboarding", ctx, request)}
}

func (_c *MockAuthServiceInterface_Onboarding_Call) Run(run func(ctx context.Context, request *messages.OnboardingRequestDTO)) *MockAuthServiceInterface_Onboarding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.OnboardingRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.OnboardingRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_Onboarding_Call) Return(onboardingResponseDTO *messages.OnboardingResponseDTO, err error) *MockAuthServiceInterface_Onboarding_Call {
	_c.Call.Return(onboardingResponseDTO, err)
	return _c
}

func (_c *MockAuthServiceInterface_Onboarding_Call) RunAndReturn(run func(ctx context.Context, request *messages.OnboardingRequestDTO) (*messages.OnboardingResponseDTO, error)) *MockAuthServiceInterface_Onboarding_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyCode provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) VerifyCode(ctx context.Context, request *messages.VerificationCodeRequestDTO) (*messages.VerificationCodeResponseDTO, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCode")
	}

	var r0 *messages.VerificationCodeResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.VerificationCodeRequestDTO) (*messages.VerificationCodeResponseDTO, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.VerificationCodeRequestDTO) *messages.VerificationCodeResponseDTO); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.VerificationCodeResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messages.VerificationCodeRequestDTO) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceInterface_VerifyCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCode'
type MockAuthServiceInterface_VerifyCode_Call struct {
	*mock.Call
}

// VerifyCode is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.VerificationCodeRequestDTO
func (_e *MockAuthServiceInterface_Expecter) VerifyCode(ctx interface{}, request interface{}) *MockAuthServiceInterface_VerifyCode_Call {
	return &MockAuthServiceInterface_VerifyCode_Call{Call: _e.mock.On("VerifyCode", ctx, request)}
}

func (_c *MockAuthServiceInterface_VerifyCode_Call) Run(run func(ctx context.Context, request *messages.VerificationCodeRequestDTO)) *MockAuthServiceInterface_VerifyCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.VerificationCodeRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.VerificationCodeRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_VerifyCode_Call) Return(verificationCodeResponseDTO *messages.VerificationCodeResponseDTO, err error) *MockAuthServiceInterface_VerifyCode_Call {
	_c.Call.Return(verificationCodeResponseDTO, err)
	return _c
}

func (_c *MockAuthServiceInterface_VerifyCode_Call) RunAndReturn(run func(ctx context.Context, request *messages.VerificationCodeRequestDTO) (*messages.VerificationCodeResponseDTO, error)) *MockAuthServiceInterface_VerifyCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailServiceInterface creates a new instance of MockEmailServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailServiceInterface {
	mock := &MockEmailServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailServiceInterface is an autogenerated mock type for the EmailServiceInterface type
type MockEmailServiceInterface struct {
	mock.Mock
}

type MockEmailServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailServiceInterface) EXPECT() *MockEmailServiceInterface_Expecter {
	return &MockEmailServiceInterface_Expecter{mock: &_m.Mock}
}

// SendVerificationCodeEmail provides a mock function for the type MockEmailServiceInterface
func (_mock *MockEmailServiceInterface) SendVerificationCodeEmail(ctx context.Context, email string, verificationCode string) error {
	ret := _mock.Called(ctx, email, verificationCode)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationCodeEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, verificationCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailServiceInterface_SendVerificationCodeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerificationCodeEmail'
type MockEmailServiceInterface_SendVerificationCodeEmail_Call struct {
	*mock.Call
}

// SendVerificationCodeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - verificationCode string
func (_e *MockEmailServiceInterface_Expecter) SendVerificationCodeEmail(ctx interface{}, email interface{}, verificationCode interface{}) *MockEmailServiceInterface_SendVerificationCodeEmail_Call {
	return &MockEmailServiceInterface_SendVerificationCodeEmail_Call{Call: _e.mock.On("SendVerificationCodeEmail", ctx, email, verificationCode)}
}

func (_c *MockEmailServiceInterface_SendVerificationCodeEmail_Call) Run(run func(ctx context.Context, email string, verificationCode string)) *MockEmailServiceInterface_SendVerificationCodeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailServiceInterface_SendVerificationCodeEmail_Call) Return(err error) *MockEmailServiceInterface_SendVerificationCodeEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailServiceInterface_SendVerificationCodeEmail_Call) RunAndReturn(run func(ctx context.Context, email string, verificationCode string) error) *MockEmailServiceInterface_SendVerificationCodeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoogleIDTokenVerifierInterface creates a new instance of MockGoogleIDTokenVerifierInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoogleIDTokenVerifierInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoogleIDTokenVerifierInterface {
	mock := &MockGoogleIDTokenVerifierInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGoogleIDTokenVerifierInterface is an autogenerated mock type for the GoogleIDTokenVerifierInterface type
type MockGoogleIDTokenVerifierInterface struct {
	mock.Mock
}

type MockGoogleIDTokenVerifierInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoogleIDTokenVerifierInterface) EXPECT() *MockGoogleIDTokenVerifierInterface_Expecter {
	return &MockGoogleIDTokenVerifierInterface_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockGoogleIDTokenVerifierInterface
func (_mock *MockGoogleIDTokenVerifierInterface) Verify(ctx context.Context, idToken string, audience string) (*interfaces.GooglePayload, error) {
	ret := _mock.Called(ctx, idToken, audience)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *interfaces.GooglePayload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*interfaces.GooglePayload, error)); ok {
		return returnFunc(ctx, idToken, audience)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *interfaces.GooglePayload); ok {
		r0 = returnFunc(ctx, idToken, audience)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.GooglePayload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, idToken, audience)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoogleIDTokenVerifierInterface_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockGoogleIDTokenVerifierInterface_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - idToken string
//   - audience string
func (_e *MockGoogleIDTokenVerifierInterface_Expecter) Verify(ctx interface{}, idToken interface{}, audience interface{}) *MockGoogleIDTokenVerifierInterface_Verify_Call {
	return &MockGoogleIDTokenVerifierInterface_Verify_Call{Call: _e.mock.On("Verify", ctx, idToken, audience)}
}

func (_c *MockGoogleIDTokenVerifierInterface_Verify_Call) Run(run func(ctx context.Context, idToken string, audience string)) *MockGoogleIDTokenVerifierInterface_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGoogleIDTokenVerifierInterface_Verify_Call) Return(googlePayload *interfaces.GooglePayload, err error) *MockGoogleIDTokenVerifierInterface_Verify_Call {
	_c.Call.Return(googlePayload, err)
	return _c
}

func (_c *MockGoogleIDTokenVerifierInterface_Verify_Call) RunAndReturn(run func(ctx context.Context, idToken string, audience string) (*interfaces.GooglePayload, error)) *MockGoogleIDTokenVerifierInterface_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupServiceInterface creates a new instance of MockGroupServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupServiceInterface {
	mock := &MockGroupServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupServiceInterface is an autogenerated mock type for the GroupServiceInterface type
type MockGroupServiceInterface struct {
	mock.Mock
}

type MockGroupServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupServiceInterface) EXPECT() *MockGroupServiceInterface_Expecter {
	return &MockGroupServiceInterface_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type MockGroupServiceInterface
func (_mock *MockGroupServiceInterface) Search(ctx context.Context, query string) ([]*messages.GroupSummaryDTO, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*messages.GroupSummaryDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*messages.GroupSummaryDTO, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*messages.GroupSummaryDTO); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*messages.GroupSummaryDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupServiceInterface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockGroupServiceInterface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockGroupServiceInterface_Expecter) Search(ctx interface{}, query interface{}) *MockGroupServiceInterface_Search_Call {
	return &MockGroupServiceInterface_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockGroupServiceInterface_Search_Call) Run(run func(ctx context.Context, query string)) *MockGroupServiceInterface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupServiceInterface_Search_Call) Return(groupSummaryDTOs []*messages.GroupSummaryDTO, err error) *MockGroupServiceInterface_Search_Call {
	_c.Call.Return(groupSummaryDTOs, err)
	return _c
}

func (_c *MockGroupServiceInterface_Search_Call) RunAndReturn(run func(ctx context.Context, query string) ([]*messages.GroupSummaryDTO, error)) *MockGroupServiceInterface_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdentityServiceInterface creates a new instance of MockIdentityServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityServiceInterface {
	mock := &MockIdentityServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdentityServiceInterface is an autogenerated mock type for the IdentityServiceInterface type
type MockIdentityServiceInterface struct {
	mock.Mock
}

type MockIdentityServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityServiceInterface) EXPECT() *MockIdentityServiceInterface_Expecter {
	return &MockIdentityServiceInterface_Expecter{mock: &_m.Mock}
}

// AuthenticateGoogle provides a mock function for the type MockIdentityServiceInterface
func (_mock *MockIdentityServiceInterface) AuthenticateGoogle(ctx context.Context, request *messages.GoogleAuthRequestDTO) (*messages.IdentitySessionResponseDTO, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateGoogle")
	}

	var r0 *messages.IdentitySessionResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.GoogleAuthRequestDTO) (*messages.IdentitySessionResponseDTO, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.GoogleAuthRequestDTO) *messages.IdentitySessionResponseDTO); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.IdentitySessionResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messages.GoogleAuthRequestDTO) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityServiceInterface_AuthenticateGoogle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateGoogle'
type MockIdentityServiceInterface_AuthenticateGoogle_Call struct {
	*mock.Call
}

// AuthenticateGoogle is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.GoogleAuthRequestDTO
func (_e *MockIdentityServiceInterface_Expecter) AuthenticateGoogle(ctx interface{}, request interface{}) *MockIdentityServiceInterface_AuthenticateGoogle_Call {
	return &MockIdentityServiceInterface_AuthenticateGoogle_Call{Call: _e.mock.On("AuthenticateGoogle", ctx, request)}
}

func (_c *MockIdentityServiceInterface_AuthenticateGoogle_Call) Run(run func(ctx context.Context, request *messages.GoogleAuthRequestDTO)) *MockIdentityServiceInterface_AuthenticateGoogle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.GoogleAuthRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.GoogleAuthRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentityServiceInterface_AuthenticateGoogle_Call) Return(identitySessionResponseDTO *messages.IdentitySessionResponseDTO, err error) *MockIdentityServiceInterface_AuthenticateGoogle_Call {
	_c.Call.Return(identitySessionResponseDTO, err)
	return _c
}

func (_c *MockIdentityServiceInterface_AuthenticateGoogle_Call) RunAndReturn(run func(ctx context.Context, request *messages.GoogleAuthRequestDTO) (*messages.IdentitySessionResponseDTO, error)) *MockIdentityServiceInterface_AuthenticateGoogle_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteOnboarding provides a mock function for the type MockIdentityServiceInterface
func (_mock *MockIdentityServiceInterface) CompleteOnboarding(ctx context.Context, request *messages.CompleteOnboardingRequestDTO) (*messages.CurrentSessionResponseDTO, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOnboarding")
	}

	var r0 *messages.CurrentSessionResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.CompleteOnboardingRequestDTO) (*messages.CurrentSessionResponseDTO, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.CompleteOnboardingRequestDTO) *messages.CurrentSessionResponseDTO); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.CurrentSessionResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messages.CompleteOnboardingRequestDTO) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityServiceInterface_CompleteOnboarding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOnboarding'
type MockIdentityServiceInterface_CompleteOnboarding_Call struct {
	*mock.Call
}

// CompleteOnboarding is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.CompleteOnboardingRequestDTO
func (_e *MockIdentityServiceInterface_Expecter) CompleteOnboarding(ctx interface{}, request interface{}) *MockIdentityServiceInterface_CompleteOnboarding_Call {
	return &MockIdentityServiceInterface_CompleteOnboarding_Call{Call: _e.mock.On("CompleteOnboarding", ctx, request)}
}

func (_c *MockIdentityServiceInterface_CompleteOnboarding_Call) Run(run func(ctx context.Context, request *messages.CompleteOnboardingRequestDTO)) *MockIdentityServiceInterface_CompleteOnboarding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.CompleteOnboardingRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.CompleteOnboardingRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentityServiceInterface_CompleteOnboarding_Call) Return(currentSessionResponseDTO *messages.CurrentSessionResponseDTO, err error) *MockIdentityServiceInterface_CompleteOnboarding_Call {
	_c.Call.Return(currentSessionResponseDTO, err)
	return _c
}

func (_c *MockIdentityServiceInterface_CompleteOnboarding_Call) RunAndReturn(run func(ctx context.Context, request *messages.CompleteOnboardingRequestDTO) (*messages.CurrentSessionResponseDTO, error)) *MockIdentityServiceInterface_CompleteOnboarding_Call {
	_c.Call.Return(run)
	return _c
}

// Current provides a mock function for the type MockIdentityServiceInterface
func (_mock *MockIdentityServiceInterface) Current(ctx context.Context) (*messages.CurrentSessionResponseDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 *messages.CurrentSessionResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*messages.CurrentSessionResponseDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *messages.CurrentSessionResponseDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.CurrentSessionResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityServiceInterface_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type MockIdentityServiceInterface_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIdentityServiceInterface_Expecter) Current(ctx interface{}) *MockIdentityServiceInterface_Current_Call {
	return &MockIdentityServiceInterface_Current_Call{Call: _e.mock.On("Current", ctx)}
}

func (_c *MockIdentityServiceInterface_Current_Call) Run(run func(ctx context.Context)) *MockIdentityServiceInterface_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIdentityServiceInterface_Current_Call) Return(currentSessionResponseDTO *messages.CurrentSessionResponseDTO, err error) *MockIdentityServiceInterface_Current_Call {
	_c.Call.Return(currentSessionResponseDTO, err)
	return _c
}

func (_c *MockIdentityServiceInterface_Current_Call) RunAndReturn(run func(ctx context.Context) (*messages.CurrentSessionResponseDTO, error)) *MockIdentityServiceInterface_Current_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockIdentityServiceInterface
func (_mock *MockIdentityServiceInterface) Logout(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdentityServiceInterface_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockIdentityServiceInterface_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockIdentityServiceInterface_Expecter) Logout(ctx interface{}, refreshToken interface{}) *MockIdentityServiceInterface_Logout_Call {
	return &MockIdentityServiceInterface_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockIdentityServiceInterface_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockIdentityServiceInterface_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentityServiceInterface_Logout_Call) Return(err error) *MockIdentityServiceInterface_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdentityServiceInterface_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *MockIdentityServiceInterface_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockIdentityServiceInterface
func (_mock *MockIdentityServiceInterface) Refresh(ctx context.Context, refreshToken string) (*messages.IdentitySessionResponseDTO, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *messages.IdentitySessionResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*messages.IdentitySessionResponseDTO, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *messages.IdentitySessionResponseDTO); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.IdentitySessionResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityServiceInterface_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockIdentityServiceInterface_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockIdentityServiceInterface_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *MockIdentityServiceInterface_Refresh_Call {
	return &MockIdentityServiceInterface_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *MockIdentityServiceInterface_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *MockIdentityServiceInterface_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentityServiceInterface_Refresh_Call) Return(identitySessionResponseDTO *messages.IdentitySessionResponseDTO, err error) *MockIdentityServiceInterface_Refresh_Call {
	_c.Call.Return(identitySessionResponseDTO, err)
	return _c
}

func (_c *MockIdentityServiceInterface_Refresh_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*messages.IdentitySessionResponseDTO, error)) *MockIdentityServiceInterface_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwtServiceInterface creates a new instance of MockJwtServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtServiceInterface {
	mock := &MockJwtServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwtServiceInterface is an autogenerated mock type for the JwtServiceInterface type
type MockJwtServiceInterface struct {
	mock.Mock
}

type MockJwtServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtServiceInterface) EXPECT() *MockJwtServiceInterface_Expecter {
	return &MockJwtServiceInterface_Expecter{mock: &_m.Mock}
}

// GenerateIdentityToken provides a mock function for the type MockJwtServiceInterface
func (_mock *MockJwtServiceInterface) GenerateIdentityToken(ctx context.Context, user *entities.User) (string, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateIdentityToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) (string, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtServiceInterface_GenerateIdentityToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateIdentityToken'
type MockJwtServiceInterface_GenerateIdentityToken_Call struct {
	*mock.Call
}

// GenerateIdentityToken is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockJwtServiceInterface_Expecter) GenerateIdentityToken(ctx interface{}, user interface{}) *MockJwtServiceInterface_GenerateIdentityToken_Call {
	return &MockJwtServiceInterface_GenerateIdentityToken_Call{Call: _e.mock.On("GenerateIdentityToken", ctx, user)}
}

func (_c *MockJwtServiceInterface_GenerateIdentityToken_Call) Run(run func(ctx context.Context, user *entities.User)) *MockJwtServiceInterface_GenerateIdentityToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwtServiceInterface_GenerateIdentityToken_Call) Return(s string, err error) *MockJwtServiceInterface_GenerateIdentityToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJwtServiceInterface_GenerateIdentityToken_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) (string, error)) *MockJwtServiceInterface_GenerateIdentityToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionWebhookServiceInterface creates a new instance of MockSubscriptionWebhookServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionWebhookServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionWebhookServiceInterface {
	mock := &MockSubscriptionWebhookServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionWebhookServiceInterface is an autogenerated mock type for the SubscriptionWebhookServiceInterface type
type MockSubscriptionWebhookServiceInterface struct {
	mock.Mock
}

type MockSubscriptionWebhookServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionWebhookServiceInterface) EXPECT() *MockSubscriptionWebhookServiceInterface_Expecter {
	return &MockSubscriptionWebhookServiceInterface_Expecter{mock: &_m.Mock}
}

// Ingest provides a mock function for the type MockSubscriptionWebhookServiceInterface
func (_mock *MockSubscriptionWebhookServiceInterface) Ingest(ctx context.Context, rawPayload map[string]any) error {
	ret := _mock.Called(ctx, rawPayload)

	if len(ret) == 0 {
		panic("no return value specified for Ingest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any) error); ok {
		r0 = returnFunc(ctx, rawPayload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionWebhookServiceInterface_Ingest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ingest'
type MockSubscriptionWebhookServiceInterface_Ingest_Call struct {
	*mock.Call
}

// Ingest is a helper method to define mock.On call
//   - ctx context.Context
//   - rawPayload map[string]any
func (_e *MockSubscriptionWebhookServiceInterface_Expecter) Ingest(ctx interface{}, rawPayload interface{}) *MockSubscriptionWebhookServiceInterface_Ingest_Call {
	return &MockSubscriptionWebhookServiceInterface_Ingest_Call{Call: _e.mock.On("Ingest", ctx, rawPayload)}
}

func (_c *MockSubscriptionWebhookServiceInterface_Ingest_Call) Run(run func(ctx context.Context, rawPayload map[string]any)) *MockSubscriptionWebhookServiceInterface_Ingest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionWebhookServiceInterface_Ingest_Call) Return(err error) *MockSubscriptionWebhookServiceInterface_Ingest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionWebhookServiceInterface_Ingest_Call) RunAndReturn(run func(ctx context.Context, rawPayload map[string]any) error) *MockSubscriptionWebhookServiceInterface_Ingest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskServiceInterface creates a new instance of MockTaskServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskServiceInterface {
	mock := &MockTaskServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskServiceInterface is an autogenerated mock type for the TaskServiceInterface type
type MockTaskServiceInterface struct {
	mock.Mock
}

type MockTaskServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskServiceInterface) EXPECT() *MockTaskServiceInterface_Expecter {
	return &MockTaskServiceInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) Create(ctx context.Context, request *messages.CreateTaskRequestDTO) (*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.CreateTaskRequestDTO) (*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messages.CreateTaskRequestDTO) *messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messages.CreateTaskRequestDTO) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request *messages.CreateTaskRequestDTO
func (_e *MockTaskServiceInterface_Expecter) Create(ctx interface{}, request interface{}) *MockTaskServiceInterface_Create_Call {
	return &MockTaskServiceInterface_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockTaskServiceInterface_Create_Call) Run(run func(ctx context.Context, request *messages.CreateTaskRequestDTO)) *MockTaskServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messages.CreateTaskRequestDTO
		if args[1] != nil {
			arg1 = args[1].(*messages.CreateTaskRequestDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_Create_Call) Return(taskResponseDTO *messages.TaskResponseDTO, err error) *MockTaskServiceInterface_Create_Call {
	_c.Call.Return(taskResponseDTO, err)
	return _c
}

func (_c *MockTaskServiceInterface_Create_Call) RunAndReturn(run func(ctx context.Context, request *messages.CreateTaskRequestDTO) (*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) Delete(ctx context.Context, id uint64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockTaskServiceInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskServiceInterface_Delete_Call {
	return &MockTaskServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskServiceInterface_Delete_Call) Run(run func(ctx context.Context, id uint64)) *MockTaskServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_Delete_Call) Return(err error) *MockTaskServiceInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskServiceInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint64) error) *MockTaskServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) Get(ctx context.Context, id uint64) (*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTaskServiceInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockTaskServiceInterface_Expecter) Get(ctx interface{}, id interface{}) *MockTaskServiceInterface_Get_Call {
	return &MockTaskServiceInterface_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTaskServiceInterface_Get_Call) Run(run func(ctx context.Context, id uint64)) *MockTaskServiceInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_Get_Call) Return(taskResponseDTO *messages.TaskResponseDTO, err error) *MockTaskServiceInterface_Get_Call {
	_c.Call.Return(taskResponseDTO, err)
	return _c
}

func (_c *MockTaskServiceInterface_Get_Call) RunAndReturn(run func(ctx context.Context, id uint64) (*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) List(ctx context.Context) ([]*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTaskServiceInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskServiceInterface_Expecter) List(ctx interface{}) *MockTaskServiceInterface_List_Call {
	return &MockTaskServiceInterface_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTaskServiceInterface_List_Call) Run(run func(ctx context.Context)) *MockTaskServiceInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_List_Call) Return(taskResponseDTOs []*messages.TaskResponseDTO, err error) *MockTaskServiceInterface_List_Call {
	_c.Call.Return(taskResponseDTOs, err)
	return _c
}

func (_c *MockTaskServiceInterface_List_Call) RunAndReturn(run func(ctx context.Context) ([]*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) Update(ctx context.Context, id uint64, request *messages.UpdateTaskRequestDTO) (*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateTaskRequestDTO) (*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx, id, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateTaskRequestDTO) *messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *messages.UpdateTaskRequestDTO) error); ok {
		r1 = returnFunc(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskServiceInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
//   - request *messages.UpdateTaskRequestDTO
func (_e *MockTaskServiceInterface_Expecter) Update(ctx interface{}, id interface{}, request interface{}) *MockTaskServiceInterface_Update_Call {
	return &MockTaskServiceInterface_Update_Call{Call: _e.mock.On("Update", ctx, id, request)}
}

func (_c *MockTaskServiceInterface_Update_Call) Run(run func(ctx context.Context, id uint64, request *messages.UpdateTaskRequestDTO)) *MockTaskServiceInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *messages.UpdateTaskRequestDTO
		if args[2] != nil {
			arg2 = args[2].(*messages.UpdateTaskRequestDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_Update_Call) Return(taskResponseDTO *messages.TaskResponseDTO, err error) *MockTaskServiceInterface_Update_Call {
	_c.Call.Return(taskResponseDTO, err)
	return _c
}

func (_c *MockTaskServiceInterface_Update_Call) RunAndReturn(run func(ctx context.Context, id uint64, request *messages.UpdateTaskRequestDTO) (*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockTaskServiceInterface
func (_mock *MockTaskServiceInterface) UpdateStatus(ctx context.Context, id uint64, request *messages.UpdateTaskStatusRequestDTO) (*messages.TaskResponseDTO, error) {
	ret := _mock.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *messages.TaskResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateTaskStatusRequestDTO) (*messages.TaskResponseDTO, error)); ok {
		return returnFunc(ctx, id, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateTaskStatusRequestDTO) *messages.TaskResponseDTO); ok {
		r0 = returnFunc(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.TaskResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *messages.UpdateTaskStatusRequestDTO) error); ok {
		r1 = returnFunc(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskServiceInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTaskServiceInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
//   - request *messages.UpdateTaskStatusRequestDTO
func (_e *MockTaskServiceInterface_Expecter) UpdateStatus(ctx interface{}, id interface{}, request interface{}) *MockTaskServiceInterface_UpdateStatus_Call {
	return &MockTaskServiceInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, request)}
}

func (_c *MockTaskServiceInterface_UpdateStatus_Call) Run(run func(ctx context.Context, id uint64, request *messages.UpdateTaskStatusRequestDTO)) *MockTaskServiceInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *messages.UpdateTaskStatusRequestDTO
		if args[2] != nil {
			arg2 = args[2].(*messages.UpdateTaskStatusRequestDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskServiceInterface_UpdateStatus_Call) Return(taskResponseDTO *messages.TaskResponseDTO, err error) *MockTaskServiceInterface_UpdateStatus_Call {
	_c.Call.Return(taskResponseDTO, err)
	return _c
}

func (_c *MockTaskServiceInterface_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uint64, request *messages.UpdateTaskStatusRequestDTO) (*messages.TaskResponseDTO, error)) *MockTaskServiceInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceInterface creates a new instance of MockUserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type MockUserServiceInterface struct {
	mock.Mock
}

type MockUserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterface_Expecter {
	return &MockUserServiceInterface_Expecter{mock: &_m.Mock}
}

// UpdateGroup provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) UpdateGroup(ctx context.Context, userID uint64, request *messages.UpdateUserGroupRequestDTO) (*messages.UserResponseDTO, error) {
	ret := _mock.Called(ctx, userID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 *messages.UserResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateUserGroupRequestDTO) (*messages.UserResponseDTO, error)); ok {
		return returnFunc(ctx, userID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *messages.UpdateUserGroupRequestDTO) *messages.UserResponseDTO); ok {
		r0 = returnFunc(ctx, userID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.UserResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *messages.UpdateUserGroupRequestDTO) error); ok {
		r1 = returnFunc(ctx, userID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockUserServiceInterface_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - request *messages.UpdateUserGroupRequestDTO
func (_e *MockUserServiceInterface_Expecter) UpdateGroup(ctx interface{}, userID interface{}, request interface{}) *MockUserServiceInterface_UpdateGroup_Call {
	return &MockUserServiceInterface_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, userID, request)}
}

func (_c *MockUserServiceInterface_UpdateGroup_Call) Run(run func(ctx context.Context, userID uint64, request *messages.UpdateUserGroupRequestDTO)) *MockUserServiceInterface_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *messages.UpdateUserGroupRequestDTO
		if args[2] != nil {
			arg2 = args[2].(*messages.UpdateUserGroupRequestDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_UpdateGroup_Call) Return(userResponseDTO *messages.UserResponseDTO, err error) *MockUserServiceInterface_UpdateGroup_Call {
	_c.Call.Return(userResponseDTO, err)
	return _c
}

func (_c *MockUserServiceInterface_UpdateGroup_Call) RunAndReturn(run func(ctx context.Context, userID uint64, request *messages.UpdateUserGroupRequestDTO) (*messages.UserResponseDTO, error)) *MockUserServiceInterface_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookPayloadTranslatorInterface creates a new instance of MockWebhookPayloadTranslatorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookPayloadTranslatorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookPayloadTranslatorInterface {
	mock := &MockWebhookPayloadTranslatorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebhookPayloadTranslatorInterface is an autogenerated mock type for the WebhookPayloadTranslatorInterface type
type MockWebhookPayloadTranslatorInterface struct {
	mock.Mock
}

type MockWebhookPayloadTranslatorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookPayloadTranslatorInterface) EXPECT() *MockWebhookPayloadTranslatorInterface_Expecter {
	return &MockWebhookPayloadTranslatorInterface_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function for the type MockWebhookPayloadTranslatorInterface
func (_mock *MockWebhookPayloadTranslatorInterface) Translate(payload map[string]any) ([]*interfaces.TranslatedSubscription, error) {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 []*interfaces.TranslatedSubscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(map[string]any) ([]*interfaces.TranslatedSubscription, error)); ok {
		return returnFunc(payload)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]any) []*interfaces.TranslatedSubscription); ok {
		r0 = returnFunc(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*interfaces.TranslatedSubscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]any) error); ok {
		r1 = returnFunc(payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebhookPayloadTranslatorInterface_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockWebhookPayloadTranslatorInterface_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - payload map[string]any
func (_e *MockWebhookPayloadTranslatorInterface_Expecter) Translate(payload interface{}) *MockWebhookPayloadTranslatorInterface_Translate_Call {
	return &MockWebhookPayloadTranslatorInterface_Translate_Call{Call: _e.mock.On("Translate", payload)}
}

func (_c *MockWebhookPayloadTranslatorInterface_Translate_Call) Run(run func(payload map[string]any)) *MockWebhookPayloadTranslatorInterface_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]any
		if args[0] != nil {
			arg0 = args[0].(map[string]any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebhookPayloadTranslatorInterface_Translate_Call) Return(translatedSubscriptions []*interfaces.TranslatedSubscription, err error) *MockWebhookPayloadTranslatorInterface_Translate_Call {
	_c.Call.Return(translatedSubscriptions, err)
	return _c
}

func (_c *MockWebhookPayloadTranslatorInterface_Translate_Call) RunAndReturn(run func(payload map[string]any) ([]*interfaces.TranslatedSubscription, error)) *MockWebhookPayloadTranslatorInterface_Translate_Call {
	_c.Call.Return(run)
	return _c
}
