// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnjtechteam/dnj-game-api/internal/app/messages"
	"github.com/dnjtechteam/dnj-game-api/internal/domain/space/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSpaceRepositoryInterface creates a new instance of MockSpaceRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpaceRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpaceRepositoryInterface {
	mock := &MockSpaceRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpaceRepositoryInterface is an autogenerated mock type for the SpaceRepositoryInterface type
type MockSpaceRepositoryInterface struct {
	mock.Mock
}

type MockSpaceRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpaceRepositoryInterface) EXPECT() *MockSpaceRepositoryInterface_Expecter {
	return &MockSpaceRepositoryInterface_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockSpaceRepositoryInterface
func (_mock *MockSpaceRepositoryInterface) List(ctx context.Context, page uint64) (*messages.PaginatedResponse[entities.Space], error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *messages.PaginatedResponse[entities.Space]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*messages.PaginatedResponse[entities.Space], error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *messages.PaginatedResponse[entities.Space]); ok {
		r0 = returnFunc(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.PaginatedResponse[entities.Space])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpaceRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSpaceRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint64
func (_e *MockSpaceRepositoryInterface_Expecter) List(ctx interface{}, page interface{}) *MockSpaceRepositoryInterface_List_Call {
	return &MockSpaceRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, page)}
}

func (_c *MockSpaceRepositoryInterface_List_Call) Run(run func(ctx context.Context, page uint64)) *MockSpaceRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSpaceRepositoryInterface_List_Call) Return(paginatedResponse *messages.PaginatedResponse[entities.Space], err error) *MockSpaceRepositoryInterface_List_Call {
	_c.Call.Return(paginatedResponse, err)
	return _c
}

func (_c *MockSpaceRepositoryInterface_List_Call) RunAndReturn(run func(ctx context.Context, page uint64) (*messages.PaginatedResponse[entities.Space], error)) *MockSpaceRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}
