// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnjtechteam/dnj-game-api/internal/domain/subscriptionwebhook/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriptionWebhookRepositoryInterface creates a new instance of MockSubscriptionWebhookRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionWebhookRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionWebhookRepositoryInterface {
	mock := &MockSubscriptionWebhookRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionWebhookRepositoryInterface is an autogenerated mock type for the SubscriptionWebhookRepositoryInterface type
type MockSubscriptionWebhookRepositoryInterface struct {
	mock.Mock
}

type MockSubscriptionWebhookRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionWebhookRepositoryInterface) EXPECT() *MockSubscriptionWebhookRepositoryInterface_Expecter {
	return &MockSubscriptionWebhookRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSubscriptionWebhookRepositoryInterface
func (_mock *MockSubscriptionWebhookRepositoryInterface) Create(ctx context.Context, webhook *entities.SubscriptionWebhook) (*entities.SubscriptionWebhook, error) {
	ret := _mock.Called(ctx, webhook)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.SubscriptionWebhook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.SubscriptionWebhook) (*entities.SubscriptionWebhook, error)); ok {
		return returnFunc(ctx, webhook)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.SubscriptionWebhook) *entities.SubscriptionWebhook); ok {
		r0 = returnFunc(ctx, webhook)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.SubscriptionWebhook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.SubscriptionWebhook) error); ok {
		r1 = returnFunc(ctx, webhook)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionWebhookRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubscriptionWebhookRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - webhook *entities.SubscriptionWebhook
func (_e *MockSubscriptionWebhookRepositoryInterface_Expecter) Create(ctx interface{}, webhook interface{}) *MockSubscriptionWebhookRepositoryInterface_Create_Call {
	return &MockSubscriptionWebhookRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, webhook)}
}

func (_c *MockSubscriptionWebhookRepositoryInterface_Create_Call) Run(run func(ctx context.Context, webhook *entities.SubscriptionWebhook)) *MockSubscriptionWebhookRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.SubscriptionWebhook
		if args[1] != nil {
			arg1 = args[1].(*entities.SubscriptionWebhook)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionWebhookRepositoryInterface_Create_Call) Return(subscriptionWebhook *entities.SubscriptionWebhook, err error) *MockSubscriptionWebhookRepositoryInterface_Create_Call {
	_c.Call.Return(subscriptionWebhook, err)
	return _c
}

func (_c *MockSubscriptionWebhookRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, webhook *entities.SubscriptionWebhook) (*entities.SubscriptionWebhook, error)) *MockSubscriptionWebhookRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}
