all: false
force-file-write: true
formatter: goimports
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: mocks
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/dnjtechteam/dnj-game-api/internal/app/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: service_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/common/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: common_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/user/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: user_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/task/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: task_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/group/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: group_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/subscriptionwebhook/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: subscription_webhook_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/subscriptionwebhookverificationcode/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: subscription_webhook_verification_code_domain_mocks.go
