all: false
force-file-write: true
formatter: goimports
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: mocks
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/dnjtechteam/dnj-game-api/internal/domain/adminoperation/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: admin_operation_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/app/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: service_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/common/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: common_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/user/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: user_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/space/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: space_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/activity/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: activity_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/favorite/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: favorite_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/game/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: game_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/media/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: media_domain_mocks.go
      structname: 'MockMedia{{.InterfaceName}}'
  github.com/dnjtechteam/dnj-game-api/internal/domain/moment/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: moment_domain_mocks.go
      structname: 'MockMoment{{.InterfaceName}}'
  github.com/dnjtechteam/dnj-game-api/internal/domain/operationaudit/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: operation_audit_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/task/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: task_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/group/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: group_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/groupmembership/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: group_membership_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/groupinvite/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: group_invite_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/identity/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: identity_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/refreshsession/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: refresh_session_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/subscriptionwebhook/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: subscription_webhook_domain_mocks.go
  github.com/dnjtechteam/dnj-game-api/internal/domain/subscriptionwebhookverificationcode/interfaces:
    config:
      all: true
      dir: './internal/mocks'
      filename: subscription_webhook_verification_code_domain_mocks.go
