// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	api2 "github.com/dnjtechteam/dnj-game-api/internal/infrastructure/di/api"
	"github.com/dnjtechteam/dnj-game-api/internal/infrastructure/di/db"
	"github.com/dnjtechteam/dnj-game-api/internal/infrastructure/di/db/repositories"
	"github.com/dnjtechteam/dnj-game-api/internal/infrastructure/di/services"
	"github.com/dnjtechteam/dnj-game-api/internal/presentation/api"
	"github.com/dnjtechteam/dnj-game-api/internal/presentation/api/handlers"
)

// Injectors from wire.go:

func InitializeServer() *api.API {
	engine := api2.ProvideEngine()
	gormDB := db.ProvideDB()
	healthcheckHandler := &handlers.HealthcheckHandler{
		DB: gormDB,
	}
	transactionManagerInterface := db.ProvideTransactionManager(gormDB)
	baseService := services.ProvideBaseService(transactionManagerInterface)
	subscriptionWebhookVerificationCodeRepositoryInterface := repositories.ProvideSubscriptionWebhookVerificationCodeRepository(gormDB)
	userRepositoryInterface := repositories.ProvideUserRepository(gormDB)
	groupRepositoryInterface := repositories.ProvideGroupRepository(gormDB)
	jwtServiceInterface := services.ProvideJwtService(baseService)
	emailServiceInterface := services.ProvideEmailService()
	authServiceInterface := services.ProvideAuthService(baseService, subscriptionWebhookVerificationCodeRepositoryInterface, userRepositoryInterface, groupRepositoryInterface, jwtServiceInterface, emailServiceInterface)
	authHandler := &handlers.AuthHandler{
		AuthService: authServiceInterface,
	}
	googleIdentityRepositoryInterface := repositories.ProvideGoogleIdentityRepository(gormDB)
	refreshSessionRepositoryInterface := repositories.ProvideRefreshSessionRepository(gormDB)
	googleIDTokenVerifierInterface := services.ProvideGoogleIDTokenVerifier()
	identityServiceInterface := services.ProvideIdentityService(baseService, userRepositoryInterface, groupRepositoryInterface, googleIdentityRepositoryInterface, refreshSessionRepositoryInterface, jwtServiceInterface, googleIDTokenVerifierInterface)
	identityHandler := &handlers.IdentityHandler{
		IdentityService: identityServiceInterface,
	}
	subscriptionWebhookRepositoryInterface := repositories.ProvideSubscriptionWebhookRepository(gormDB)
	webhookPayloadTranslatorInterface := services.ProvideWebhookPayloadTranslator()
	subscriptionWebhookServiceInterface := services.ProvideSubscriptionWebhookService(baseService, subscriptionWebhookRepositoryInterface, subscriptionWebhookVerificationCodeRepositoryInterface, groupRepositoryInterface, webhookPayloadTranslatorInterface)
	subscriptionWebhookHandler := &handlers.SubscriptionWebhookHandler{
		SubscriptionWebhookService: subscriptionWebhookServiceInterface,
	}
	groupServiceInterface := services.ProvideGroupService(baseService, groupRepositoryInterface)
	groupHandler := &handlers.GroupHandler{
		GroupService: groupServiceInterface,
	}
	userServiceInterface := services.ProvideUserService(baseService, userRepositoryInterface, groupRepositoryInterface)
	userHandler := &handlers.UserHandler{
		UserService: userServiceInterface,
	}
	taskRepositoryInterface := repositories.ProvideTaskRepository(gormDB)
	taskServiceInterface := services.ProvideTaskService(baseService, taskRepositoryInterface)
	taskHandler := &handlers.TaskHandler{
		TaskService: taskServiceInterface,
	}
	handlersHandlers := &handlers.Handlers{
		HealthcheckHandler:         healthcheckHandler,
		AuthHandler:                authHandler,
		IdentityHandler:            identityHandler,
		SubscriptionWebhookHandler: subscriptionWebhookHandler,
		GroupHandler:               groupHandler,
		UserHandler:                userHandler,
		TaskHandler:                taskHandler,
	}
	router := api2.ProvideRouter(engine, handlersHandlers)
	apiAPI := &api.API{
		Router: router,
	}
	return apiAPI
}
